SAAS-596 organization creation form
percona-platform/saas-ui pull request #103
Opened 2021-08-12 15:38 UTC by nicolalamacchia

![image](https://user-images.githubusercontent.com/2530868/129223392-1eed6f62-9df0-48bb-8559-c193eba44cb7.png)
![image](https://user-images.githubusercontent.com/2530868/129223469-1870fcae-33af-4b63-ac05-b368a69488c1.png)

Minor style adjustment will be done later on (like the look of the tabs bar, which will stay as it is unless we write our own tabs bar component).

2021-08-12 19:26 UTC, fabio-silva requested changes

2021-08-13 09:25 UTC, tiagomotasantos commented on src/pages/GettingStarted/GettingStarted.messages.ts
> +  createOrganizationDescription: 'Creating your organization is going to allow you to invite others.',
others what? Members? Organizations?

2021-08-13 09:25 UTC, tiagomotasantos commented on src/pages/ManageOrganization/OrganizationTab/OrganizationTab.styles.ts
> +        height: 145px;
Does this styles work well in mobile too?

2021-08-13 09:25 UTC, tiagomotasantos commented on src/pages/ManageOrganization/OrganizationTab/OrganizationTab.tsx
> +            <TextInputField className={styles.orgNameInput} label="Organization Name" placeholder={Messages.orgNamePlaceholder} name="organizationName" validators={[validators.required]} />
Label should go to messages file?

2021-08-13 09:44 UTC, fabio-silva commented on src/pages/ManageOrganization/OrganizationTab/OrganizationTab.styles.ts
> +        height: 145px;
I was checking it and this part in particular should be ok. The problem is our `PublicLayout`/`PrivateLayout` that wrap our pages, because they have a `2em` padding. Because the font is not being reduced for smaller screens, this padding in fact will remain the same at all sizes, meaning some layouts break, creating horizontal scroll. We should probably open a ticket to fix this responsiveness problem.

2021-08-13 09:47 UTC, fabio-silva commented on src/pages/ManageOrganization/OrganizationTab/OrganizationTab.tsx
> +            <TextInputField className={styles.orgNameInput} label="Organization Name" placeholder={Messages.orgNamePlaceholder} name="organizationName" validators={[validators.required]} />
👍

2021-08-13 10:25 UTC, tiagomotasantos commented on src/pages/ManageOrganization/OrganizationTab/OrganizationTab.styles.ts
> +        height: 145px;
Got it, if the rest is ok yeah maybe that should be addressed separately.

2021-08-13 10:26 UTC, tiagomotasantos commented on src/pages/GettingStarted/GettingStarted.messages.ts
> +  createOrganizationDescription: 'Creating your organization is going to allow you to invite others.',
```suggestion
  createOrganizationDescription: 'Creating your organization is going to allow you to invite other members.',
```

Maybe something like this then? Seems easier to understand to me

2021-08-13 10:30 UTC, fabio-silva commented on src/pages/GettingStarted/GettingStarted.messages.ts
> +  createOrganizationDescription: 'Creating your organization is going to allow you to invite others.',
Agreed 👍

2021-08-13 18:33 UTC, atymchuk requested changes

2021-08-13 18:33 UTC, atymchuk commented on src/pages/ManageOrganization/ManageOrganization.test.tsx
> +    render(
This render is not used anywhere, therefore can be removed

2021-08-13 18:33 UTC, atymchuk commented on src/pages/ManageOrganization/ManageOrganization.tsx
> +                // TODO: research why css prop is needed and how to remove it
By upgrading to latest @grafana/ui

2021-08-16 16:51 UTC, fabio-silva commented on src/pages/ManageOrganization/ManageOrganization.test.tsx
> +    render(
good one 👍

2021-08-17 09:40 UTC, tiagomotasantos submitted a review, later dismissed

2021-08-23 08:30 UTC, nicolalamacchia commented on src/pages/ManageOrganization/OrganizationTab/OrganizationTab.styles.ts
> +        height: 145px;
> Does these styles work well in mobile too?
@tiagomotasantos not necessarily, we're delivering desktop only for now

2021-09-07 09:26 UTC, fabio-silva submitted a review, later dismissed

2021-09-07 09:26 UTC, fabio-silva commented on src/pages/ManageOrganization/OrganizationTab/OrganizationTab.tsx
> +  }, [response.ok]);
nit: shouldn't this be `response`?

2021-09-07 09:28 UTC, tiagomotasantos submitted a review, later dismissed

2021-09-07 11:12 UTC, nicolalamacchia commented on src/pages/ManageOrganization/OrganizationTab/OrganizationTab.tsx
> +  }, [response.ok]);
@fabio-silva, actually I just want to check for `response.ok` instead of the whole `response` object

2021-09-29 15:24 UTC, tiagomotasantos approved these changes

2021-09-29 15:25 UTC, fabio-silva submitted a review, later dismissed

2021-09-30 09:06 UTC, tiagomotasantos approved these changes

2021-09-30 09:11 UTC, fabio-silva approved these changes

2021-09-30 09:13 UTC, merged