SAAS-633 show org details
percona-platform/saas-ui pull request #109
Opened 2021-09-10 08:55 UTC by nicolalamacchia

![image](https://user-images.githubusercontent.com/2530868/132828194-c2cc9a63-8065-42b0-b9aa-d46854a76761.png)
![image](https://user-images.githubusercontent.com/2530868/132828201-a34f4421-b0f2-4961-bcb2-33703710eecc.png)

2021-09-10 09:35 UTC, fabio-silva requested changes

2021-09-10 09:35 UTC, fabio-silva commented on src/pages/GettingStarted/GettingStarted.tsx
> +  const { error, data = {} } = useFetch(`http://localhost:5000/${LIST_ORGANIZATION_URL}`, { method: 'POST' }, []);
Why are we hardcoding localhost and port here?

2021-09-10 09:35 UTC, fabio-silva commented on src/pages/ManageOrganization/OrganizationTab/OrganizationView/OrganizationView.tsx
> +    setOrgCreationDate(new Date(data?.created_at).toLocaleDateString());
Do we want to set the date without doing any checks? This can easily go "Invalid Date", which means the check you have on the render (`orgName && orgCreationDate`) can cause a false positive, even though the date isn't valid.

2021-09-10 09:35 UTC, fabio-silva commented on src/pages/ManageOrganization/OrganizationTab/OrganizationTab.tsx
> +      {orgId!! ? <OrganizationView orgId={orgId!} /> : <OrganizationCreate />}
Isn't one exclamation mark enough?
Anyway, if we are adding `!!` to tell the compiler the var can't be null/undefined, why the ternary?
Shouldn't it be `{orgId ? <OrganizationView orgId={orgId} /> : <OrganizationCreate />}` ?

2021-09-10 09:52 UTC, nicolalamacchia commented on src/pages/GettingStarted/GettingStarted.tsx
> +  const { error, data = {} } = useFetch(`http://localhost:5000/${LIST_ORGANIZATION_URL}`, { method: 'POST' }, []);
Oops, fixed it!

2021-09-10 09:58 UTC, nicolalamacchia commented on src/pages/ManageOrganization/OrganizationTab/OrganizationTab.tsx
> +      {orgId!! ? <OrganizationView orgId={orgId!} /> : <OrganizationCreate />}
No, it's not enough because orgId could be undefined, but by checking that it exists before (ternary condition) we can safely tell TypeScript that `orgId` in the params is not undefined. The `!!` is not telling the compiler it can't be null/undefined, it's casting to boolean (which as a side effect not to be null/undefined), to be explicit the second `!` in params is needed.

2021-09-10 09:58 UTC, nicolalamacchia commented on src/pages/ManageOrganization/OrganizationTab/OrganizationView/OrganizationView.tsx
> +    setOrgCreationDate(new Date(data?.created_at).toLocaleDateString());
We trust the back end to send correct data, the creation date must exist by requirement, so it's ok to just convert it

2021-09-10 10:03 UTC, fabio-silva commented on src/pages/ManageOrganization/OrganizationTab/OrganizationTab.tsx
> +      {orgId!! ? <OrganizationView orgId={orgId!} /> : <OrganizationCreate />}
I see, but then I guess it should be `!!orgId`, right? And by doing that, the exclamation mark on the left-side expression can be removed.

2021-09-10 10:03 UTC, fabio-silva commented on src/pages/ManageOrganization/OrganizationTab/OrganizationView/OrganizationView.tsx
> +    setOrgCreationDate(new Date(data?.created_at).toLocaleDateString());
Roger 👍

2021-09-10 21:05 UTC, tiagomotasantos commented on src/pages/ManageOrganization/OrganizationTab/OrganizationCreate/OrganizationCreate.messages.ts
> +  orgNamePlaceholder: 'Your organization name',
Some word start with capital letters while others don't. Can we change too "Create organization" and "Organization name" or does it really need to be like this?

2021-09-12 09:43 UTC, atymchuk commented on src/pages/ManageOrganization/OrganizationTab/OrganizationCreate/OrganizationCreate.tsx
> +            <TextInputField className={styles.orgNameInput} label={Messages.organizationName} placeholder={Messages.orgNamePlaceholder} name="organizationName" validators={[validators.required]} />
This needs to be wrapped, like the Loader is below

2021-09-12 09:43 UTC, atymchuk commented on src/pages/ManageOrganization/OrganizationTab/OrganizationTab.tsx
> +      {orgId!! ? <OrganizationView orgId={orgId!} /> : <OrganizationCreate />}
Agree, looks strange. Can you provide any reference to TS docs to see if this is known/best practice/etc?

2021-09-13 08:05 UTC, nicolalamacchia commented on src/pages/ManageOrganization/OrganizationTab/OrganizationTab.tsx
> +      {orgId!! ? <OrganizationView orgId={orgId!} /> : <OrganizationCreate />}
oh, sorry, now I get it, you mean that `!!` is redundant, right? yes, it's just more explicit, but I consider this a nit. The second one is still needed, otherwise TS complains.

2021-09-13 08:06 UTC, nicolalamacchia commented on src/pages/ManageOrganization/OrganizationTab/OrganizationCreate/OrganizationCreate.messages.ts
> +  orgNamePlaceholder: 'Your organization name',
@tiagomotasantos because some of them are titles and some other are not

2021-09-13 08:09 UTC, nicolalamacchia commented on src/pages/ManageOrganization/OrganizationTab/OrganizationCreate/OrganizationCreate.tsx
> +            <TextInputField className={styles.orgNameInput} label={Messages.organizationName} placeholder={Messages.orgNamePlaceholder} name="organizationName" validators={[validators.required]} />
Can you please explain more in details what you mean?

2021-09-14 15:12 UTC, nicolalamacchia commented on src/pages/ManageOrganization/OrganizationTab/OrganizationCreate/OrganizationCreate.tsx
> +            <TextInputField className={styles.orgNameInput} label={Messages.organizationName} placeholder={Messages.orgNamePlaceholder} name="organizationName" validators={[validators.required]} />
done

2021-09-14 15:12 UTC, nicolalamacchia commented on src/pages/ManageOrganization/OrganizationTab/OrganizationTab.tsx
> +      {orgId!! ? <OrganizationView orgId={orgId!} /> : <OrganizationCreate />}
done

2021-09-14 16:08 UTC, tiagomotasantos approved these changes

2021-09-29 16:04 UTC, merged