Okta: get user info into store
percona-platform/saas-ui pull request #121
Opened 2021-11-05 15:42 UTC by fabio-silva

- Cleaned login / logout unused actions
- `useUserInfo` hook takes care of calling Okta's endpoint and fill in the store the first time

2021-11-05 16:56 UTC, atymchuk requested changes

2021-11-05 16:56 UTC, atymchuk commented on src/core/hooks/useUserInfo.ts
> +import { authGetProfileAction, authUpdateProfileAction, getAuth } from '../../store/auth';
```suggestion
import { authGetProfileAction, authUpdateProfileAction, getAuth } from 'store/auth';
```
nit

2021-11-05 16:56 UTC, atymchuk commented on src/core/hooks/useUserInfo.ts
> +  const { freshData } = user;
`freshData` reads somewhat weird )
Is it us or Okta who came up with that prop name?

2021-11-05 16:56 UTC, atymchuk commented on src/store/auth/auth.reducer.ts
> +  freshData: true,
How can `freshData` be true by default? Not sure it's even needed )

2021-11-05 16:56 UTC, atymchuk commented on src/core/hooks/useUserInfo.ts
> +          const { email: oktaEmail, family_name, given_name } = await oktaAuth.getUser();
```suggestion
          const { email, family_name, given_name } = await oktaAuth.getUser();
```

2021-11-05 16:56 UTC, atymchuk commented on src/core/hooks/useUserInfo.ts
> +            email: oktaEmail,
```suggestion
            email,
```

2021-11-05 16:56 UTC, atymchuk commented on src/core/hooks/useUserInfo.ts
> +          const { email: oktaEmail, family_name, given_name } = await oktaAuth.getUser();
No need to be renamed, the email is not Okta's.

2021-11-08 10:12 UTC, nicolalamacchia submitted a review, later dismissed
just found some nits @atymchuk already pointed to

2021-11-08 10:37 UTC, fabio-silva commented on src/core/hooks/useUserInfo.ts
> +import { authGetProfileAction, authUpdateProfileAction, getAuth } from '../../store/auth';
👍

2021-11-08 10:37 UTC, fabio-silva commented on src/core/hooks/useUserInfo.ts
> +  const { freshData } = user;
removed flag

2021-11-08 10:38 UTC, fabio-silva commented on src/core/hooks/useUserInfo.ts
> +          const { email: oktaEmail, family_name, given_name } = await oktaAuth.getUser();
I renamed this var. It must have another name, as we already got `email` some lines above (`const { email } = user;`)

2021-11-08 10:45 UTC, atymchuk requested changes

2021-11-08 10:45 UTC, atymchuk commented on src/core/hooks/useUserInfo.ts
> +          const { email: oktaUserEmail, family_name, given_name } = await oktaAuth.getUser();
```suggestion
          const { email, family_name, given_name } = await oktaAuth.getUser();
```

2021-11-08 10:45 UTC, atymchuk commented on src/core/hooks/useUserInfo.ts
> +            email: oktaUserEmail,
```suggestion
            email,
```

2021-11-08 10:45 UTC, atymchuk commented on src/core/hooks/useUserInfo.ts
> +          const { email: oktaUserEmail, family_name, given_name } = await oktaAuth.getUser();
it's a nit, but why do we have to attach the word "okta" to the properties? It is a user's email after all

2021-11-08 10:52 UTC, fabio-silva commented on src/core/hooks/useUserInfo.ts
> +          const { email: oktaUserEmail, family_name, given_name } = await oktaAuth.getUser();
good one 👍

2021-11-08 10:56 UTC, atymchuk approved these changes

2021-11-08 10:56 UTC, atymchuk commented on src/core/hooks/useUserInfo.ts
> +  return [{ ...user }, setUser];
No need to copy imho, it will always return a new reference whenever things change in the user's state

2021-11-18 22:06 UTC, closed without merging