Fix logout error message
percona-platform/saas-ui pull request #130
Opened 2021-11-17 16:36 UTC by nicolalamacchia

2021-11-17 16:37 UTC, fabio-silva submitted a review, later dismissed

2021-11-17 16:53 UTC, tiagomotasantos submitted a review, later dismissed

2021-11-18 07:55 UTC, atymchuk commented
@nicolalamacchia This is a bug, and there is a ticket open. Let's stick to the branch naming convention.

2021-11-18 08:36 UTC, atymchuk requested changes

2021-11-18 08:36 UTC, atymchuk commented on src/components/MenuBar/MenuBar.tsx
> -      dispatch(authLogoutAction.success());
This is not the right cure, because if we do not dispatch the `authLogoutAction.success()` action, the redux state is going to have `authenticated: true`, which is absolutely not the case (see [here](https://github.com/percona-platform/saas-ui/blob/main/src/store/auth/auth.reducer.ts#L72-L78)).

Solution: we should rely on the `authenticated` state from Okta auth, rather than our own.

2021-11-18 08:42 UTC, atymchuk commented on src/components/MenuBar/MenuBar.tsx
> -      dispatch(authLogoutAction.success());
I suggest that [this](https://github.com/percona-platform/saas-ui/blob/5a7231094f603905a0074d6c0371caa267ed0221/src/store/types/auth.ts#L3) be removed from the store, it's a relatively small refactoring.

2021-11-18 09:19 UTC, nicolalamacchia commented on src/components/MenuBar/MenuBar.tsx
> -      dispatch(authLogoutAction.success());
@atymchuk if you inspect the state with redux devtools, you will see that the state gets reset after logout, because of the refresh. so the `authenticated` state will be `false`.

2021-11-18 09:22 UTC, nicolalamacchia commented on src/components/MenuBar/MenuBar.tsx
> -      dispatch(authLogoutAction.success());
That's not the right it's a hotfix which will need a proper fix

2021-11-18 09:23 UTC, atymchuk commented on src/components/MenuBar/MenuBar.tsx
> -      dispatch(authLogoutAction.success());
> @atymchuk if you inspect the state with redux devtools, you will see that the state gets reset after logout, because of the refresh. so the `authenticated` state will be `false`.

Do we want to rely on a side effect? How can one reason reason about it going forward?

2021-11-18 09:27 UTC, nicolalamacchia commented on src/components/MenuBar/MenuBar.tsx
> -      dispatch(authLogoutAction.success());
I agree it's confusing, but this is supposed to be a quick fix for the demo. Again, it will require a proper fix and investigation which needs to be prioritized. If there will be some refactoring needed as a result of that investigation, it will be addressed.

2021-11-18 09:53 UTC, closed without merging