SAAS-641 edit member role
percona-platform/saas-ui pull request #131
Opened 2021-11-19 12:46 UTC by nicolalamacchia

2021-11-25 10:25 UTC, fabio-silva requested changes

2021-11-25 10:25 UTC, fabio-silva commented on src/pages/ManageOrganization/MembersList/MemberActions/MemberActions.tsx
> +              <Label className={styles.label}>{Messages.email}</Label>
can't we just use the `label` prop from `TextInputField`?
If this is because we want a bigger font for the label, we can still use the `fieldClassName` prop and target the label

2021-11-25 10:32 UTC, nicolalamacchia commented on src/pages/ManageOrganization/MembersList/MemberActions/MemberActions.tsx
> +              <Label className={styles.label}>{Messages.email}</Label>
Good point! Done.

2021-11-25 10:39 UTC, tiagomotasantos approved these changes

2021-11-25 10:39 UTC, tiagomotasantos commented on src/pages/ManageOrganization/MembersList/MemberActions/MemberActions.tsx
> +        <Form onSubmit={handleEditMemberSubmit} initialValues={{ role: role as any }}>
```suggestion
        <Form onSubmit={handleEditMemberSubmit} initialValues={{ role: role as MemberRole }}>
```

This doesn't work?

2021-11-25 12:03 UTC, nicolalamacchia commented on src/pages/ManageOrganization/MembersList/MemberActions/MemberActions.tsx
> +        <Form onSubmit={handleEditMemberSubmit} initialValues={{ role: role as any }}>
Nope, I need to look into it, but looks like we'll solve that by having our own select field

2021-11-25 12:22 UTC, fabio-silva submitted a review, later dismissed

2021-11-26 12:58 UTC, solovevayaroslavna approved these changes

2021-11-26 14:23 UTC, tiagomotasantos approved these changes

2021-11-26 14:28 UTC, fabio-silva approved these changes

2021-11-26 15:04 UTC, tiagomotasantos approved these changes

2021-11-27 06:44 UTC, solovevayaroslavna approved these changes

2021-11-29 10:57 UTC, merged