SAAS-714: org tickets list
percona-platform/saas-ui pull request #133
Opened 2021-11-22 12:09 UTC by fabio-silva

https://jira.percona.com/browse/SAAS-714

2021-11-22 14:45 UTC, solovevayaroslavna submitted a review, later dismissed

2021-11-22 15:28 UTC, fabio-silva commented
> Great job, Fabio! I don't see anything that I want to fix, but it makes sense to wait for someone else's review since I might miss something that is standard for you that I don't know about.

Thanks @solovevayaroslavna  !😄

2021-11-23 16:14 UTC, tiagomotasantos requested changes
Good job @fabio-silva 🚀  Pls consider my comments as possible improvements if we have time for it and not as a must do.

2021-11-23 16:14 UTC, tiagomotasantos commented on src/pages/Dashboard/TicketList/TicketList.tsx
> +        Cell: ({ value }) => format(new Date(value), 'd MMM yyyy'),
Can we put the format in a constant file to share it across other places?

2021-11-23 16:14 UTC, tiagomotasantos commented on src/pages/Dashboard/TicketList/TicketList.tsx
> +        Cell: ({ value }) => format(new Date(value), 'd MMM yyyy'),
Also do we really need date-fns? We could use the locale date format with `toLocaleDateString` or parse it ourselves with methods such as `getMonth` from `Date`.

2021-11-23 16:14 UTC, tiagomotasantos commented on src/pages/Dashboard/TicketList/TicketList.tsx
> +  ) as any;
Why any? Should it be an array of `Column` type from react-table?

2021-11-25 18:55 UTC, atymchuk requested changes

2021-11-25 18:55 UTC, atymchuk commented on src/pages/Dashboard/TicketList/TicketList.service.ts
> +  const { data: orgData = { orgs: [] } } = await searchOrgs();
Do we want to handle errors? It can be a 500, a 502 or pretty much anything.

2021-11-25 18:55 UTC, atymchuk commented on src/pages/Dashboard/TicketList/TicketList.utils.ts
> +export const formatOrgTickets = (tickets: OrganizationTicketsResponse[]): OrgTicket[] =>
Are really formatting here, or are we mapping one to another? If the latter, then maybe `mapOrgTickets`?

2021-11-25 18:55 UTC, atymchuk commented on src/pages/Dashboard/TicketList/TicketStatus/TicketStatus.styles.ts
> +export const getStyles = stylesFactory((theme: GrafanaTheme, status: OrgTicketStatus) => ({
```suggestion
export const getStyles = stylesFactory(({ palette, typography }: GrafanaTheme, status: OrgTicketStatus) => ({
```

2021-11-25 18:55 UTC, atymchuk commented on src/pages/Dashboard/TicketList/TicketStatus/TicketStatus.styles.ts
> +export const getStyles = stylesFactory((theme: GrafanaTheme, status: OrgTicketStatus) => ({
nit

2021-11-25 18:56 UTC, atymchuk commented on src/pages/Dashboard/TicketList/TicketList.service.ts
> +  const { data: orgData = { orgs: [] } } = await searchOrgs();
It will be discovered by QA, I'm almost sure :)

2021-11-25 22:51 UTC, fabio-silva commented on src/pages/Dashboard/TicketList/TicketList.tsx
> +        Cell: ({ value }) => format(new Date(value), 'd MMM yyyy'),
Yeah, I guess you're right, we can go with `toLocaleDateString ` for now.

2021-11-25 22:53 UTC, fabio-silva commented on src/pages/Dashboard/TicketList/TicketList.tsx
> +  ) as any;
Just typed `columns` as `Column<any>[]`. We're getting a typing error if we don't do this: `'Column<OrgTicket>[]' is not assignable to type 'Column<{}>[]'`. I believe we have to fix this typing in core (i.e. in `TableProps`, defining `columns: Column<any>[];`), as in Grafana we never had this error.

2021-11-25 22:55 UTC, fabio-silva commented on src/pages/Dashboard/TicketList/TicketList.service.ts
> +  const { data: orgData = { orgs: [] } } = await searchOrgs();
The error handling (try/catch) is on `TicketList.tsx`, in the effect.
Here we're just making sure our code doesn't break in the event no orgs are present. For some API design reason I can't understand, the absence of orgs comes as `{}` instead of `{ orgs: [] }`.

2021-11-25 22:56 UTC, fabio-silva commented on src/pages/Dashboard/TicketList/TicketList.utils.ts
> +export const formatOrgTickets = (tickets: OrganizationTicketsResponse[]): OrgTicket[] =>
good one 👍

2021-11-25 22:56 UTC, fabio-silva commented on src/pages/Dashboard/TicketList/TicketStatus/TicketStatus.styles.ts
> +export const getStyles = stylesFactory((theme: GrafanaTheme, status: OrgTicketStatus) => ({
👍

2021-11-26 14:10 UTC, nicolalamacchia approved these changes

2021-11-26 14:13 UTC, atymchuk commented on src/pages/Dashboard/TicketList/TicketList.service.ts
> +  const { data: orgData = { orgs: [] } } = await searchOrgs();
Strange. Did you try to talk to BE devs or @maxkondr ?

2021-11-26 14:16 UTC, atymchuk approved these changes

2021-11-26 18:57 UTC, tiagomotasantos approved these changes

2021-11-30 09:15 UTC, solovevayaroslavna submitted a review, later dismissed

2021-11-30 16:56 UTC, tiagomotasantos approved these changes

2021-12-02 09:09 UTC, merged