SAAS-640 remove member
percona-platform/saas-ui pull request #148
Opened 2021-12-01 16:48 UTC by nicolalamacchia

2021-12-01 21:45 UTC, atymchuk requested changes

2021-12-01 21:45 UTC, atymchuk commented on src/pages/ManageOrganization/MembersList/MemberActions/MemberActions.tsx
>  import { ManageOrganizationProvider } from '../../ManageOrganization.provider';
When did we start using context?

2021-12-01 21:45 UTC, atymchuk commented on src/pages/ManageOrganization/ManageOrganization.tsx
> +    await deleteReq(`${ORGANIZATIONS_URL}/${orgId}/${ORGANIZATION_MEMBER_URL_CHUNK}/${memberId}`);
In this particular case, the endpoint called `deleteOrgMember` would look like the following:
`
{ deleteOrgMember: (orgId, memberId) => '/v1/orgs/${orgId}/members/${memberId}', }
`

so that using it becomes a breeze: `ENDPOINTS.Org.deleteOrgMember(orgId, memberId)`,

... and [those lines](https://github.com/percona-platform/saas-ui/blob/661cfedc87b19f1602ae1cf1e9093c942e65a9f3/src/pages/ManageOrganization/ManageOrganization.constants.ts#L4-L7) will have to be moved to [endpoints.ts](https://github.com/percona-platform/saas-ui/blob/d7ddc1d8e199b5e3e2e3cbeded186f540dff965d/src/core/api/endpoints.ts)

And does `ORGANIZATION_MEMBER_URL_CHUNK` need to be a constant? Seems like absolutely not necessary...

And this is not about freedom, but about consistency and maintainability of the code.

2021-12-02 09:53 UTC, nicolalamacchia commented on src/pages/ManageOrganization/ManageOrganization.tsx
> +    await deleteReq(`${ORGANIZATIONS_URL}/${orgId}/${ORGANIZATION_MEMBER_URL_CHUNK}/${memberId}`);
Good point, I can address that in this PR

2021-12-02 09:53 UTC, nicolalamacchia commented on src/pages/ManageOrganization/MembersList/MemberActions/MemberActions.tsx
>  import { ManageOrganizationProvider } from '../../ManageOrganization.provider';
What's the problem with context?

2021-12-02 10:20 UTC, atymchuk commented on src/pages/ManageOrganization/MembersList/MemberActions/MemberActions.tsx
>  import { ManageOrganizationProvider } from '../../ManageOrganization.provider';
> 

The problem is that it promotes bad code organization patterns IMO. In this particular case `loading`, `userInfo` and `userRole` are all parts of the global state, whose management must be delegated to redux. So it's unclear how it ended up being passed via Context.

2021-12-02 10:39 UTC, tiagomotasantos commented on src/pages/ManageOrganization/MembersList/MemberActions/MemberActions.tsx
>  import { ManageOrganizationProvider } from '../../ManageOrganization.provider';
I agree that we should do a proper use of the store and avoid context API (plus other things like unify how we do API calls and do a proper responsive design), but we can focus on that after December 7th IMO so we can deliver the most features until then. We could even create tickets for this now and make it high priority.

2021-12-02 10:41 UTC, tiagomotasantos approved these changes
@nicolalamacchia can you pls provide an image/video of this feature in the description?

2021-12-02 10:53 UTC, nicolalamacchia commented on src/pages/ManageOrganization/MembersList/MemberActions/MemberActions.tsx
>  import { ManageOrganizationProvider } from '../../ManageOrganization.provider';
I agree that some variables can be taken from the store, but that wouldn't solve props drilling of functions (see for example: https://github.com/percona-platform/saas-ui/pull/148/files#diff-1e3e5abd472938380a6c69de8e54854928f6e2798b40a8a3e049a797d6643f3aR202). I can take care of that unification during our hackaton.

2021-12-02 10:56 UTC, atymchuk commented on src/pages/ManageOrganization/MembersList/MemberActions/MemberActions.tsx
>  import { ManageOrganizationProvider } from '../../ManageOrganization.provider';
I think it shouldn't be a problem, i.e. a different component structure would allow to avoid it. But I need to dig deeper to showcase it (kinda need to prepare an different look at things).

2021-12-02 11:03 UTC, atymchuk commented on src/pages/ManageOrganization/MembersList/MemberActions/MemberActions.tsx
>  import { ManageOrganizationProvider } from '../../ManageOrganization.provider';
I'm resolving this, since we need to have a UI squad discussion. We will land tickets to address the issues mentioned above.

2021-12-02 18:49 UTC, nicolalamacchia commented on src/pages/ManageOrganization/ManageOrganization.tsx
> +    await deleteReq(`${ORGANIZATIONS_URL}/${orgId}/${ORGANIZATION_MEMBER_URL_CHUNK}/${memberId}`);
Done

2021-12-02 18:50 UTC, nicolalamacchia commented
> @nicolalamacchia can you pls provide an image/video of this feature in the description?

Done, @tiagomotasantos

2021-12-03 14:46 UTC, tiagomotasantos approved these changes

2021-12-06 08:20 UTC, atymchuk approved these changes

2021-12-06 13:51 UTC, atymchuk commented
@nicolalamacchia That delete modal doesn't really comply with our standards, so we'll need to make if more usable please.

2021-12-06 15:18 UTC, tiagomotasantos approved these changes

2021-12-06 15:32 UTC, solovevayaroslavna approved these changes

2021-12-06 15:37 UTC, nicolalamacchia commented
> @nicolalamacchia That delete modal doesn't really comply with our standards, so we'll need to make if more usable please.

@atymchuk can you please clarify that? Which standards are you referring to?

2021-12-06 17:20 UTC, merged

2021-12-06 19:56 UTC, atymchuk commented
> > @nicolalamacchia That delete modal doesn't really comply with our standards, so we'll need to make if more usable please.
> 
> @atymchuk can you please clarify that? Which standards are you referring to?

I'm referring to the look and feel and UX we already provided in many places. I'll drop here two links for you to familiarize yourself if not already.

Link 1 - https://www.figma.com/file/Fk9p1JX7sYAOzBjoR9u8WU/Backup-Management?node-id=1069%3A599
Link 2 - https://www.figma.com/file/ybEkoie2ppFp6tCEVOTOoh/Integrated-Alerting-Architecture-v3?node-id=730%3A591