SAAS-794 migrate to redux toolkit
percona-platform/saas-ui pull request #160
Opened 2021-12-15 22:37 UTC by atymchuk

Notable things:
* typescript downgraded to match the core-ui
* redux-logger added, but devtools are also present

2022-02-09 12:16 UTC, atymchuk commented
@nicolalamacchia Awesome, LGTM.
Let's se what we can do with unit tests.

2022-02-11 11:19 UTC, fabio-silva requested changes
Just some things:
- Some errors along the code, regarding unused/non-defined vars;
- We are excluding some tests. Is there a reason for that?

2022-02-14 18:43 UTC, nicolalamacchia commented on src/pages/Login/Login.test.tsx
> +xdescribe('Portal Login', () => {
> Just some things:
> 
> * Some errors along the code, regarding unused/non-defined vars;
> * We are excluding some tests. Is there a reason for that?

Yes, we are excluding that because they all need to be upgraded, but it's better to do so after the implementation of a possible new way of making API calls, which will come separately.

2022-02-15 12:45 UTC, tiagomotasantos commented on src/store/auth/auth.actions.ts
> +export const startUserInfoAction = createAction<void>('USER:INFO/START');
Why are user related actions on the auth file? Maybe we should leave only login/logout here and move user actions to another file (e.g. user.actions)?

2022-02-15 12:45 UTC, tiagomotasantos commented on src/store/auth/auth.actions.ts
> +  { rejectValue: unknown }
Does the API return the errors in a specific format? If so we could create a type for errors here

2022-02-15 13:23 UTC, nicolalamacchia commented on src/store/auth/auth.actions.ts
> +  { rejectValue: unknown }
@atymchuk did you look into that already?

2022-02-15 13:26 UTC, nicolalamacchia commented on src/store/auth/auth.actions.ts
> +export const startUserInfoAction = createAction<void>('USER:INFO/START');
I guess login/sign-up/logout are still use related, IMO you have a good point about the name though. Although this is a nit, we can consider changing the name. cc @atymchuk

2022-02-15 14:31 UTC, tiagomotasantos submitted a review, later dismissed

2022-02-15 15:47 UTC, fabio-silva approved these changes

2022-03-16 11:03 UTC, tiagomotasantos approved these changes

2022-03-16 11:04 UTC, fabio-silva submitted a review, later dismissed

2022-03-17 10:06 UTC, fabio-silva approved these changes

2022-03-17 10:07 UTC, fabio-silva approved these changes

2022-03-23 09:18 UTC, closed without merging