SAAS-791 Improve entitlements view
percona-platform/saas-ui pull request #161
Opened 2021-12-16 16:16 UTC by tiagomotasantos

Improves entitlements view:

- Makes the modal header bigger
- Fixes the modal size so it doesn't grow/shrink
- Adds expiry date

Expiry date was add through css because right now the Collapse component from Grafana only allows a single text but in Grafana 8 the component already supports a ReactNode as header so we can refactor this part when we update to Grafana 8 to cleanup the css.

https://jira.percona.com/browse/SAAS-791

https://user-images.githubusercontent.com/16366502/146408221-c885569a-852b-4ac3-bfe4-15d71575d826.mov

2021-12-17 10:18 UTC, atymchuk requested changes

2021-12-17 10:18 UTC, atymchuk commented on src/pages/Dashboard/Contacts/EntitlementsModal/EntitlementsModal.styles.ts
> +    div[data-testid="modal-body"] {
@tiagomotasantos Let's see if can have a different selector so we do not depend on the test-id, which may change and we won't probably notice.

2021-12-17 10:18 UTC, atymchuk commented on src/pages/Dashboard/Contacts/EntitlementsModal/EntitlementsModal.styles.ts
> +      `div[data-testid="modal-content"] {
Is there no way to reach to those elements other than checking all the nested divs? This code doesn't look much like maintainable :)

2021-12-17 10:27 UTC, tiagomotasantos commented on src/pages/Dashboard/Contacts/EntitlementsModal/EntitlementsModal.styles.ts
> +    div[data-testid="modal-body"] {
There's no different selector unfortunately. Our modal from platform core doesn't allow to receive a className to do this. And even then we would have to play with the structure of the elements inside the modal to change width/height. The best we can do here is improve the API of the modal to handle this cases.

2021-12-17 10:28 UTC, tiagomotasantos commented on src/pages/Dashboard/Contacts/EntitlementsModal/EntitlementsModal.styles.ts
> +      `div[data-testid="modal-content"] {
There's no other way at the moment. I left a comment in the PR and in the code regarding this.
We need to add the expiry date to the collapse header, in the version of grafana we are using it only allows a string as header. In version 8 already allows a ReactNode, so when we upgrade to version 8 we can remove this code and use a custom header.

(and I also tried to do this through the content of the collapse but it gets removed from the DOM when the collapse if closed and we need this to be always shown so that's not even a option)

2021-12-17 10:32 UTC, tiagomotasantos commented on src/pages/Dashboard/Contacts/EntitlementsModal/EntitlementsModal.styles.ts
> +    div[data-testid="modal-body"] {
(of course we could use the order of the elements to get to the correct element but I think that's much worse than using testid)

2021-12-17 11:30 UTC, fabio-silva submitted a review, later dismissed

2021-12-17 11:30 UTC, fabio-silva commented on src/pages/Dashboard/Contacts/EntitlementsModal/EntitlementsModal.tsx
> +                  <Advisor label={Messages.securityAdvisor} hasAvisor={security_advisor} />
nit: is `hasAvisor` a typo?

2021-12-17 15:54 UTC, tiagomotasantos commented on src/pages/Dashboard/Contacts/EntitlementsModal/EntitlementsModal.tsx
> +                  <Advisor label={Messages.securityAdvisor} hasAvisor={security_advisor} />
Totally! Thank you, fixed!

2021-12-20 10:53 UTC, atymchuk approved these changes

2021-12-21 10:09 UTC, fabio-silva approved these changes

2021-12-23 10:24 UTC, merged