SAAS-756 list of PMM instances
percona-platform/saas-ui pull request #162
Opened 2021-12-21 00:05 UTC by nicolalamacchia

2021-12-21 10:23 UTC, fabio-silva requested changes

2021-12-21 10:23 UTC, fabio-silva commented on src/assets/pmm-server-instances.svg
> +<path d="M1.5 18.4971V12.9601C1.5 12.1321 2.171 11.4971 3 11.4971H9C9.828 11.4971 10.5 12.1321 10.5 12.9601V18.4561" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/>
can we just indent this? Our linter never complains on this one, but all other SVGs are indented

2021-12-21 10:23 UTC, fabio-silva commented on src/pages/GettingStarted/GettingStartedPmmSection/GettingStartedPmmSection.tsx
> +      disabled={!inventory?.length}
```suggestion
      disabled={!!inventory?.length}
```

2021-12-21 10:23 UTC, fabio-silva commented on src/pages/ManagePmmInstances/PmmInstanceList/PmmInstanceList.tsx
> +        accessor: ({ url }) => (
This should be `Cell: ({ value }) =>` instead, where `value` is automatically considered a `string`. I believe you must add `<Column<PmmInstance>[]>` on line 13 for this to work: `(): <Column<PmmInstance>[]>`

2021-12-22 13:23 UTC, atymchuk requested changes

2021-12-22 13:23 UTC, atymchuk commented on src/assets/pmm-server-instances.svg
> +<path d="M1.5 18.4971V12.9601C1.5 12.1321 2.171 11.4971 3 11.4971H9C9.828 11.4971 10.5 12.1321 10.5 12.9601V18.4561" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/>
Given that all other svgs are indented, I'd say we should.

2021-12-23 09:33 UTC, nicolalamacchia commented on src/pages/GettingStarted/GettingStartedPmmSection/GettingStartedPmmSection.tsx
> +      disabled={!inventory?.length}
@fabio-silva that's actually the correct logic, it has to be disabled if the length is zero.

2021-12-23 09:33 UTC, nicolalamacchia commented on src/assets/pmm-server-instances.svg
> +<path d="M1.5 18.4971V12.9601C1.5 12.1321 2.171 11.4971 3 11.4971H9C9.828 11.4971 10.5 12.1321 10.5 12.9601V18.4561" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/>
done

2021-12-23 09:37 UTC, nicolalamacchia commented on src/pages/ManagePmmInstances/PmmInstanceList/PmmInstanceList.tsx
> +        accessor: ({ url }) => (
@fabio-silva why is that? `url` has the right type in `accessor`, furthermore TS is not complaining. Is there a reason for those changes?

Re `<Column<PmmInstance>[]>`, it's already specified on line 12. It's either that or on line 13, I prefer to type `useMemo` :)

2021-12-23 10:52 UTC, fabio-silva commented on src/pages/ManagePmmInstances/PmmInstanceList/PmmInstanceList.tsx
> +        accessor: ({ url }) => (
It's here in the API: https://react-table.tanstack.com/docs/api/useTable#column-options 
- `accessor` : `The data returned by an accessor should be primitive and sortable.`;
- `Cell`: `Must return valid JSX`.

I.e. `accessor` tells the table how to reach the data field, while `Cell` dictates how to render it

2021-12-23 15:33 UTC, tiagomotasantos approved these changes

2021-12-23 16:19 UTC, fabio-silva submitted a review, later dismissed

2021-12-23 17:15 UTC, nicolalamacchia commented on src/pages/ManagePmmInstances/PmmInstanceList/PmmInstanceList.tsx
> +        accessor: ({ url }) => (
good point! done

2021-12-23 17:16 UTC, fabio-silva approved these changes

2021-12-23 17:17 UTC, tiagomotasantos approved these changes

2021-12-29 13:46 UTC, merged