SAAS-688 Add Google Analytics code
percona-platform/saas-ui pull request #165
Opened 2021-12-29 16:13 UTC by nicolalamacchia

2021-12-29 16:15 UTC, atymchuk commented on public/index.html
> +    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-343802-23"></script>
Can we disable it in the dev environment?

2021-12-29 16:41 UTC, nicolalamacchia commented on public/index.html
> +    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-343802-23"></script>
@rnovikovP told me he wanted to categorize events based on the domain (dev vs prod), so I guess it's better to keep it. Let's wait for him to confirm.

2021-12-29 16:42 UTC, atymchuk commented on public/index.html
> +    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-343802-23"></script>
That is surprising, never heard of the need to analyze the dev.

2021-12-30 09:48 UTC, fabio-silva approved these changes

2021-12-30 10:01 UTC, tiagomotasantos requested changes

2021-12-30 10:01 UTC, tiagomotasantos commented on public/index.html
> +        gtag('config', 'UA-343802-23');
Can this config be an env variable?
For example .env file contains prod tag UA-343802-23 while .env.development contains dev tag UA-343802-16.
In that case there's no need for conditions neither to have REACT_APP_PROD_DOMAIN

2021-12-30 10:41 UTC, nicolalamacchia commented on public/index.html
> +        gtag('config', 'UA-343802-23');
@tiagomotasantos those variables are replaced at build time, which is not something we want right now (it would mean two builds, one per environment).

2021-12-30 10:50 UTC, tiagomotasantos commented on public/index.html
> +        gtag('config', 'UA-343802-23');
`npm run build` creates a prod build already. We would have to find a way just to create a dev build for local development. Why we don't want that? 🤔

In any case if that's not an option I don't see the need for REACT_APP_PROD_DOMAIN, we could ate least use NODE_ENV (set it to prod where we are building it for prod and the rest of the environments can even be unset)

2021-12-30 12:00 UTC, nicolalamacchia commented on public/index.html
> +        gtag('config', 'UA-343802-23');
We would have to maintain two builds, one for the dev env and one for prod, which is something we discussed already with the team and found it's an overkill, since we'd need it just in a couple of places, where we can just use the check against the domain name at runtime (which is a common strategy).

The NODE_ENV variable gets replaced at build time as well, of course, and it requires a specific build command for dev, which we don't want for what I've mentioned before.

Consider that the dev build is not needed for local development, but for the dev environment, so it has to be pushed to the registry and requires CI to be aware of it.

2021-12-30 12:25 UTC, tiagomotasantos commented on public/index.html
> +        gtag('config', 'UA-343802-23');
Got it, thanks!

2021-12-30 12:26 UTC, tiagomotasantos approved these changes

2022-01-07 14:53 UTC, merged