Saas 817 list of support tickets UI tests
percona-platform/saas-ui pull request #172
Opened 2022-01-28 10:53 UTC by peterSirotnak

Pull request for [SAAS-817](https://jira.percona.com/browse/SAAS-817)

2022-02-01 09:44 UTC, yurkovychv requested changes

2022-02-01 09:44 UTC, yurkovychv commented on cypress/integration/customer/dashboard/dashboard.spec.js
> +          for (let i = 0; i < cells.length; i++) {
it's better to use [expect](https://docs.cypress.io/guides/references/assertions#BDD-Assertions) here too. Example: `expect([1, 2, 3]).to.include.members([3, 2])`.

2022-02-01 09:44 UTC, yurkovychv commented on cypress/integration/customer/dashboard/helper.js
> +export const isTicketTableHeaderTextCorrect = (cellText, position) => {
I believe this one is not needed if you will use `expect` from comment above

2022-02-01 09:45 UTC, yurkovychv commented
@peterSirotnak Also please add `non-SN users that are members of an organization linked with SN` test

2022-02-01 13:43 UTC, peterSirotnak commented on cypress/integration/customer/dashboard/dashboard.spec.js
> +          for (let i = 0; i < cells.length; i++) {
Okay, fixed.

2022-02-01 13:43 UTC, peterSirotnak commented on cypress/integration/customer/dashboard/helper.js
> +export const isTicketTableHeaderTextCorrect = (cellText, position) => {
Yes that is correct, removed.

2022-02-01 13:44 UTC, peterSirotnak commented
> @peterSirotnak Also please add `non-SN users that are members of an organization linked with SN` test. And test case IDs to test summary

Added that test and also added waiting for dashboard page to fully load. Ticket table is rendered after loading spinners are not present.

2022-02-01 15:24 UTC, peterSirotnak commented on cypress/integration/customer/dashboard/dashboard.spec.js
> +  it('Verify Percona Customer user is able to see tickets created for his org', () => {
Fixed

2022-02-02 09:36 UTC, yurkovychv approved these changes

2022-02-02 16:41 UTC, merged