SAAS-283 responsive app layout
percona-platform/saas-ui pull request #19
Opened 2020-09-04 18:28 UTC by atymchuk

2020-09-04 20:02 UTC, nicolalamacchia approved these changes

2020-09-07 11:17 UTC, tiagomotasantos requested changes

2020-09-07 11:17 UTC, tiagomotasantos commented on packages/platform-ui/src/pages/Login/Login.tsx
> +        store.dispatch(authLoginAction.success());
I think success and failure actions should be dispatched at the end of the request action and not here. I know there's no BE integration yet but wanted to leave this here anyway.

2020-09-07 11:25 UTC, nicolalamacchia commented on packages/platform-ui/src/core/messages.ts
> +    'Single pane of glass for managing and monitoring the performance of your MySQL, MariaDB, PostgreSQLand MongoDB databases.',
Done

2020-09-07 12:02 UTC, atymchuk commented on packages/platform-ui/src/pages/Login/Login.tsx
> +        store.dispatch(authLoginAction.success());
That's quick and dirty. Of course, we will not leave it forever like this )

2020-09-07 14:39 UTC, tiagomotasantos submitted a review, later dismissed

2020-09-07 20:58 UTC, atymchuk commented on packages/platform-ui/src/core/constants.ts
> +export const PLATFORM_AUTH_API_BASE_URL = process.env.REACT_APP_PLATFORM_AUTH_API_BASE_URL ?? '';
Actually, we don't need coalescing here.
```suggestion
export const PLATFORM_AUTH_API_BASE_URL = process.env.REACT_APP_PLATFORM_AUTH_API_BASE_URL;
```

2020-09-07 20:58 UTC, atymchuk commented on packages/platform-ui/src/components/Root/Main.tsx
> +      <ToastContainer
Probably not the best place for the ToastContainer, I'd move it to index.tsx

2020-09-08 07:50 UTC, nicolalamacchia commented on packages/platform-ui/src/components/Root/Main.tsx
> +      <ToastContainer
Done

2020-09-08 07:58 UTC, nicolalamacchia commented on packages/platform-ui/src/core/constants.ts
> +export const PLATFORM_AUTH_API_BASE_URL = process.env.REACT_APP_PLATFORM_AUTH_API_BASE_URL ?? '';
Why? I think it's needed, since the value can be either string or undefined, so it's either that or the exclamation mark? Otherwise TS will complain about that (and I would prefer solve this on one line, instead of on each line referring to this variable) :)

2020-09-08 08:54 UTC, atymchuk commented on packages/platform-ui/src/core/constants.ts
> +export const PLATFORM_AUTH_API_BASE_URL = process.env.REACT_APP_PLATFORM_AUTH_API_BASE_URL ?? '';
Definitely exclamation mark. What is the reason we want to pass an empty string to the API?

2020-09-08 09:36 UTC, tiagomotasantos requested changes

2020-09-08 09:36 UTC, tiagomotasantos commented on packages/platform-ui/src/components/Authenticated/Authenticated.tsx
> +            Download PMM
Move to messages file

2020-09-08 09:53 UTC, nicolalamacchia commented on packages/platform-ui/src/components/Authenticated/Authenticated.tsx
> +            Download PMM
Good catch

2020-09-08 10:01 UTC, tiagomotasantos approved these changes

2020-09-08 11:27 UTC, tiagomotasantos submitted a review, later dismissed

2020-09-08 14:40 UTC, nicolalamacchia approved these changes

2020-09-08 15:14 UTC, AlekSi approved these changes

2020-09-08 15:14 UTC, merged