SAAS-853: New Log In Page
percona-platform/saas-ui pull request #200
Opened 2022-03-28 14:29 UTC by TomasBlazek3PG

PR to create new login page using Okta sign in widget.

This is v1 of the new page. Marketing team will shortly come back to us with new updates.

Screenshots:
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/100355118/160573506-d6cf8bb6-7fcd-4db9-abe6-6aa8c530ea6a.png">
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/100355118/160573568-eeb2e151-f559-4fbf-8531-bc7dfe878541.png">

2022-03-28 14:37 UTC, atymchuk requested changes

2022-03-28 14:37 UTC, atymchuk commented on .env
> +REACT_APP_GOOGLE_IDP_ID=
These IDs are public, so we should put them here. Are they the same on dev and prod?

2022-03-28 14:52 UTC, fabio-silva commented on .env
> +REACT_APP_GOOGLE_IDP_ID=
We talked about this today and tomorrow we can touch this on our meeting, but should we have this file here with the actual values? Shouldn't the repo instead have a `.env.sample` file with random values, so that devs know they need to replace them? I guess these values get replaced during the build phase on the CI, hence my question.

2022-03-28 18:01 UTC, fabio-silva requested changes
Good one @TomasBlazek3PG 👍 
Can we have a screenshot of this? Thanks!

2022-03-29 06:34 UTC, TomasBlazek3PG commented on src/components/OktaSignInWidget/OktaSignInWidget.tsx
> +// @ts-ignore
Typescript is not supported and throws an error.
https://github.com/okta/okta-signin-widget/issues/2385

2022-03-29 06:35 UTC, TomasBlazek3PG commented on src/components/OktaSignInWidget/OktaSignInWidget.tsx
> +    if (!fieldset || !requiredLabel) return;
Ummm makes the file quite a bit longer but if its consensus on doing it I will add it.

2022-03-29 06:36 UTC, TomasBlazek3PG commented on src/pages/Login/Login.tsx
> +        <a href='#' data-testid='learn-more'>{Messages.learnMore}<img src={arrowRightCircle} width={24} height={24} alt='link icon' /></a>
I was told: not yet. We don't have page for it now but the link should stay there as a placeholder.

2022-03-29 13:05 UTC, TomasBlazek3PG commented on .env
> +REACT_APP_GOOGLE_IDP_ID=
As communicated in UI Weekly Meeting it is now movd to constants

2022-03-29 13:44 UTC, TomasBlazek3PG commented on src/components/OktaSignInWidget/OktaSignInWidget.tsx
> +
Fixed

2022-03-29 13:44 UTC, TomasBlazek3PG commented on src/components/OktaSignInWidget/OktaSignInWidget.tsx
> +      submit.classList[checked ? 'remove' : 'add'](disabledCls);
fixed

2022-03-30 09:32 UTC, fabio-silva submitted a review, later dismissed

2022-03-31 09:17 UTC, atymchuk requested changes

2022-03-31 09:17 UTC, atymchuk commented on src/core/constants.ts
> +export const GOOGLE_IDP_ID = '0oa11tralpPwtJ5lY1d7';
This may be a bad idea, since all those constant were stored in the .env file, and now they are all over the place (
IMO it's super inconvenient to have to search through the whole codebase to find the config parameters.

2022-03-31 09:17 UTC, atymchuk commented on src/pages/Login/Login.tsx
> +        <a href='https://www.percona.com/legal' data-testid='privacy'>{Messages.privacy}</a>
All these URLs should be constants I believe that we would store to a central place, i.e. https://github.com/percona-platform/saas-ui/blob/main/src/core/constants.ts

2022-03-31 10:14 UTC, fabio-silva commented on src/core/constants.ts
> +export const GOOGLE_IDP_ID = '0oa11tralpPwtJ5lY1d7';
@TomasBlazek3PG, @atymchuk and I had a talk about this. Let's leave this on `.env` for now, as its nature is related to the other vars there. Sorry for that, I wasn't also 100% aware on how the env vars work on saas-ui.

2022-03-31 11:46 UTC, TomasBlazek3PG commented on src/core/constants.ts
> +export const GOOGLE_IDP_ID = '0oa11tralpPwtJ5lY1d7';
I was told it should not be in the .ENV, because its not secret.

2022-03-31 12:42 UTC, fabio-silva approved these changes

2022-03-31 13:29 UTC, nicolalamacchia commented on src/pages/Login/Login.tsx
> +        <a href='https://www.percona.com/legal' data-testid='privacy'>{Messages.privacy}</a>
agreed

2022-03-31 13:37 UTC, nicolalamacchia commented on src/pages/Login/Login.styles.ts
> +      }
why do we need `!important` here? can't we just improve specificity of selectors? furthermore, please do not use classes or ids, try to leverage css-in-js as much as possible

2022-03-31 14:38 UTC, nicolalamacchia approved these changes
Approving this, the required changes are going to be addressed in the next iteration

2022-04-01 10:14 UTC, nicolalamacchia submitted a review, later dismissed

2022-04-05 09:06 UTC, yurkovychv commented on cypress/integration/customer/dashboard/dashboard.spec.js
> +      cy.intercept('POST', '**/members:search').as('membersSearch').wait('@membersSearch');
@peterSirotnak maybe we can move this `intercept` to before each?

2022-04-05 09:37 UTC, peterSirotnak commented on cypress/integration/customer/dashboard/dashboard.spec.js
> +      cy.intercept('POST', '**/members:search').as('membersSearch').wait('@membersSearch');
Good idea.

2022-04-05 11:04 UTC, yurkovychv submitted a review, later dismissed

2022-10-20 11:01 UTC, atymchuk commented
@TomasBlazek3PG can we close this?

2022-10-21 10:00 UTC, closed without merging