SAAS-848 simplify flow
percona-platform/saas-ui pull request #201
Opened 2022-03-29 16:26 UTC by nicolalamacchia

2022-04-01 12:17 UTC, nicolalamacchia commented on src/components/GettingStarted/GettingStarted.tsx
> +      <header className={styles.header}>{Messages.getStarted}</header>
it is set as h2 in the style sheet

2022-04-01 12:56 UTC, fabio-silva requested changes

2022-04-01 12:56 UTC, fabio-silva commented on src/pages/Dashboard/Dashboard.tsx
> +    setShowGettingStarted((!(companyName || orgId) || !inventory?.length) && !isPending);
Not sure if I'm following this right:
- If `inventory` is empty, then show `GettingStarted`, as long as `isPending` is done;
- On `GettingStartedPmmSection` we have this:
    - `isTicked={!!inventory?.length}`
    -  `disabled={!inventory?.length}`

If we already know that inventory is empty when showing `GettingStartedPmmSection`, why are we retrieving it again there? 

Again, I might be missing something here.

2022-04-04 12:20 UTC, fabio-silva submitted a review, later dismissed

2022-04-06 07:53 UTC, TomasBlazek3PG commented on src/components/GettingStarted/GettingStarted.tsx
> +      <header className={styles.header}>{Messages.getStarted}</header>
Not agree with this solution but its nothing that should block merging.

2022-04-06 08:07 UTC, TomasBlazek3PG commented on src/pages/Dashboard/Dashboard.tsx
> +    setShowGettingStarted((!(companyName || orgId) || !inventory?.length) && !isPending);
Could we write it differently for a better readability? some constants with good naming could help understand the code better.

2022-04-06 08:26 UTC, nicolalamacchia commented on src/pages/Dashboard/Dashboard.tsx
> +    setShowGettingStarted((!(companyName || orgId) || !inventory?.length) && !isPending);
That would mean adding more `useState`, which I'd like to avoid. Those are the same variables used in other similar conditions in other parts of the code, so the logic is kind of self-explanatory.

Checking for `orgId` means checking if the org exists; checking for `companyName` means checking if the company is in Service Now; checking for `inventory` means checking if there are any linked PMM instances. That information is easily inferred by the context.

The doubt Fabio had was related to why we tick the last point in the list of getting started items to then just hide the component (effectively making useless the logic of `isTicked` in the last point).

2022-04-06 08:59 UTC, TomasBlazek3PG commented on src/pages/Dashboard/Dashboard.tsx
> +    setShowGettingStarted((!(companyName || orgId) || !inventory?.length) && !isPending);
You dont need to use useState. Just to define the variables in the scope of the function. If you feel its not necessary then merge it but I would lean towards making it more readable.

2022-04-06 13:45 UTC, TomasBlazek3PG submitted a review, later dismissed

2022-04-07 15:26 UTC, fabio-silva approved these changes

2022-04-11 13:26 UTC, TomasBlazek3PG submitted a review, later dismissed

2022-04-11 13:27 UTC, nicolalamacchia commented on src/components/GettingStarted/GettingStarted.tsx
> +      <header className={styles.header}>{Messages.getStarted}</header>
the reason for this is that we don't have a global style that we control for `h*` tags, rather we use Grafana's themes, but we have to explicitly set something like `font-size: ${typography.size.h<n>}`. should we also use an `h<n>` tag, we should update both the style and the markup, this would be error-prone (I could change the type to - for example -`h3` from `h2` and forget about changing the markup which would be inconsistent) and less practical (admittedly sacrificing semantic markup for a more maintainable one). should we start maintaining our own themes, I agree with you that semantic markup would be better.

2022-04-11 13:49 UTC, fabio-silva submitted a review, later dismissed

2022-04-13 08:55 UTC, fabio-silva approved these changes

2022-04-13 09:08 UTC, merged