SAAS-735 percona portal logo
percona-platform/saas-ui pull request #202
Opened 2022-03-31 08:56 UTC by TomasBlazek3PG

Add "Percona Portal" next to logo.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/100355118/161017425-7410b6d8-80f3-41d0-a0bc-c1516ba86c61.png">

2022-03-31 10:47 UTC, tiagomotasantos requested changes
Well done, good work 🚀  just a minor request

2022-03-31 10:47 UTC, tiagomotasantos commented on src/components/MenuBar/MenuBar.styles.ts
> +    padding: 0 15px;
Can a spacing variable be used here?

2022-03-31 13:53 UTC, tiagomotasantos approved these changes
🚀

2022-04-01 13:15 UTC, nicolalamacchia approved these changes

2022-04-01 13:15 UTC, nicolalamacchia commented on src/components/MenuBar/MenuBar.styles.ts
> +    color: ${ colors.text };
nit
```suggestion
    color: ${colors.text};
```

2022-04-05 08:17 UTC, tiagomotasantos approved these changes

2022-04-05 12:56 UTC, yurkovychv approved these changes

2022-04-05 12:57 UTC, merged