SAAS-840 Side Menu Changes
percona-platform/saas-ui pull request #206
Opened 2022-04-06 11:56 UTC by TomasBlazek3PG

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/100355118/161969245-6198c74c-8525-4e2f-99c4-ddbd0abd65b7.png">

2022-04-06 12:13 UTC, fabio-silva requested changes

2022-04-06 12:13 UTC, fabio-silva commented on src/assets/percona-sidebar-help.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M22.5 45C34.9264 45 45 34.9264 45 22.5C45 10.0736 34.9264 0 22.5 0C10.0736 0 0 10.0736 0 22.5C0 34.9264 10.0736 45 22.5 45ZM20.0758 28.4829V28.6364H23
Seems like indentation isn't properly set here, can you confirm please?

2022-04-06 12:13 UTC, fabio-silva commented on src/components/MenuBar/MenuBar.styles.ts
> +      background-color: ${theme.isLight ? colors.bg3 : colors.bg1};
Since we're already destructuring `theme`, `isLight` can follow the same patttern.

2022-04-06 12:13 UTC, fabio-silva commented on src/components/MenuBar/MenuBar.styles.ts
> +      font-weight: 'regular';
```suggestion
      font-weight: ${typography.weight.regular};
```

2022-04-06 12:13 UTC, fabio-silva commented on src/components/SideMenu/SideMenu.constants.ts
> +  help: 'https://docs.percona.com/percona-platform/percona-account-help.html?fromURI=%2Fhelp%2Flogin',
Do we need to encode the query param ourselves here?

2022-04-06 12:47 UTC, TomasBlazek3PG commented on src/components/SideMenu/SideMenu.constants.ts
> +  help: 'https://docs.percona.com/percona-platform/percona-account-help.html?fromURI=%2Fhelp%2Flogin',
Thats the link I got in AC. Can remove it.

2022-04-06 13:05 UTC, fabio-silva requested changes

2022-04-06 13:05 UTC, fabio-silva commented on src/components/SideMenu/SideMenu.messages.ts
> +  help: 'Portal help',
```suggestion
  help: 'Portal Help',
```

2022-04-06 13:05 UTC, fabio-silva commented on src/components/SideMenu/SideMenu.messages.ts
> +  help: 'Portal help',
Sorry, missed this one, for the sake of consistency. Everything else is good to go.

2022-04-06 13:29 UTC, fabio-silva approved these changes
🚀

2022-04-07 12:49 UTC, fabio-silva approved these changes

2022-04-08 10:20 UTC, fabio-silva approved these changes

2022-04-11 13:23 UTC, fabio-silva approved these changes

2022-04-11 16:39 UTC, fabio-silva approved these changes

2022-04-11 16:39 UTC, merged