Saas 880 new new login page
percona-platform/saas-ui pull request #207
Opened 2022-04-08 12:24 UTC by TomasBlazek3PG

Change of design of login page (again).

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/100355118/162434897-395bc358-4009-4923-95f9-accde65a006c.png">

2022-04-08 13:16 UTC, fabio-silva requested changes
Please, also check failures from GH's code scanning.
Other than that, this new login page is 🔥

2022-04-08 13:16 UTC, fabio-silva commented on src/core/messages.ts
> +  linkToSignUp: 'Create one',
```suggestion
  linkToSignUp: 'Create One',
```

2022-04-08 13:16 UTC, fabio-silva commented on cypress/integration/auth/logout.spec.js
> +import signInPage from 'pages/auth/signIn.page';
Both files follow the same pattern, but one does a default export and the other a named export. Let's stick to one.

2022-04-08 13:16 UTC, fabio-silva commented on src/assets/percona-platform-logo.svg
> +<svg width="365" height="51" viewBox="0 0 365 51" fill="none" xmlns="http://www.w3.org/2000/svg">
Missing indentation for SVGs

2022-04-08 13:21 UTC, TomasBlazek3PG commented on src/core/messages.ts
> +  linkToSignUp: 'Create one',
Are you sure? It looked this way better next to the sentence.

2022-04-08 13:22 UTC, TomasBlazek3PG commented on cypress/integration/auth/logout.spec.js
> +import signInPage from 'pages/auth/signIn.page';
Oh this and the scan is part of cypress file problems. @peterSirotnak will surely look at it.

2022-04-08 13:24 UTC, TomasBlazek3PG commented on src/assets/percona-platform-logo.svg
> +<svg width="365" height="51" viewBox="0 0 365 51" fill="none" xmlns="http://www.w3.org/2000/svg">
Hmm dont know why figma exports it that way. Will fix it! :)

2022-04-08 13:25 UTC, fabio-silva commented on src/core/messages.ts
> +  linkToSignUp: 'Create one',
Oh, it comes after another sentence? Then disregard my comment, didn't realize it, thought it was a single sentence hanging there.

2022-04-08 14:06 UTC, fabio-silva requested changes

2022-04-08 14:06 UTC, fabio-silva commented on cypress/pages/auth/helpers/signIn.helper.ts
> +  if(password) cy.get(signInPage.locators.passwordInput, { timeout: timeouts.HALF_MIN })
we forgot the brackets

2022-04-08 14:06 UTC, fabio-silva commented on src/assets/bullet-point-arrow.svg
> +<path d="M20 40C31.0457 40 40 31.0457 40 20C40 8.9543 31.0457 0 20 0C8.9543 0 0 8.9543 0 20C0 31.0457 8.9543 40 20 40Z" fill="#E97E30"/>
we missed this one

2022-04-08 14:06 UTC, fabio-silva commented on src/pages/Login/Login.tsx
> +  if (!authState) return null;
and here as well

2022-04-08 14:06 UTC, fabio-silva commented on cypress/integration/auth/logout.spec.js
> +import signInPage from 'pages/auth/signIn.page';
👍

2022-04-08 14:35 UTC, fabio-silva approved these changes

2022-04-08 14:48 UTC, nicolalamacchia requested changes

2022-04-08 14:48 UTC, nicolalamacchia commented on cypress/pages/auth/helpers/signIn.helper.ts
> +  if(password) cy.get(signInPage.locators.passwordInput, { timeout: timeouts.HALF_MIN })
please, follow the practices that we're following everywhere else. leave a space after the if and always use brackets

2022-04-08 14:48 UTC, nicolalamacchia commented on cypress/pages/helpers/commonPage.helper.ts
> +    cy.findByTestId(commonPage.locators.logoutButton).click();
bad indentation (4 spaces instead of 2)

2022-04-08 14:48 UTC, nicolalamacchia commented on src/assets/bullet-point-arrow.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M24.6146 20.0026L16.4596 12.3105L15.3839 13.3259L22.4602 20.0026L15.3839 26.6794L16.4596 27.695L24.6146 20.0026Z" fill="#0A0721"/>
these need to be indented

2022-04-08 14:48 UTC, nicolalamacchia commented on src/pages/Login/Login.styles.ts
> +            background: #4C15A5;
4-space indentation mixed with 2-space indentation

2022-04-08 14:48 UTC, nicolalamacchia commented on src/pages/Login/Login.tsx
> +    console.error('error logging in', err);
just log `err` here and please use `logger` instead of `console`

2022-04-08 14:48 UTC, nicolalamacchia commented on src/pages/Login/Login.tsx
> +              <li>
missing `key` attribute

2022-04-08 14:49 UTC, nicolalamacchia commented on src/components/OktaSignInWidget/OktaSignInWidget.tsx
> +const insertToS = (context: any) => {
we said we'd change it to be more declarative in this iteration. if we can't make it more react-ish for now, at least let's follow some standards, like removing the `const d = document` etc. and open another ticket for that.

2022-04-08 14:50 UTC, nicolalamacchia requested changes

2022-04-08 14:50 UTC, nicolalamacchia commented on src/components/OktaSignInWidget/OktaSignInWidget.tsx
> +
mixed 4-space indentation and 2-space indentation (should be 2 spaces)

2022-04-08 14:58 UTC, TomasBlazek3PG commented on cypress/pages/auth/helpers/signIn.helper.ts
> +  if(password) cy.get(signInPage.locators.passwordInput, { timeout: timeouts.HALF_MIN })
This is not my code. Already tagged @peterSirotnak on it on Nicolas comment.

2022-04-08 15:00 UTC, TomasBlazek3PG commented on cypress/pages/helpers/commonPage.helper.ts
> +    cy.findByTestId(commonPage.locators.logoutButton).click();
Not my code again. I rather let Peter fix it. I can if you insist however.

2022-04-08 15:01 UTC, TomasBlazek3PG commented on src/assets/bullet-point-arrow.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M24.6146 20.0026L16.4596 12.3105L15.3839 13.3259L22.4602 20.0026L15.3839 26.6794L16.4596 27.695L24.6146 20.0026Z" fill="#0A0721"/>
This one is fixed. Weird it doesnt show you.

2022-04-11 08:31 UTC, nicolalamacchia requested changes

2022-04-11 08:31 UTC, nicolalamacchia commented on src/components/OktaSignInWidget/OktaSignInWidget.tsx
> +              &nbsp;*
nit: please don't use `nbsp`, use CSS instead

2022-04-11 08:31 UTC, nicolalamacchia commented on src/components/OktaSignInWidget/OktaSignInWidget.tsx
> +interface IToSCheckbox {
this should be `ToSCheckboxProps`, as we're doing for all the other components

2022-04-11 08:31 UTC, nicolalamacchia commented on src/components/OktaSignInWidget/OktaSignInWidget.tsx
> +const insertToS = (context: any, widgetRef: HTMLDivElement) => {
as per documentation (https://github.com/okta/okta-signin-widget#afterrender), `context` should only contain a `controller` property, which is a string, so we can avoid that `any` here.

2022-04-11 08:31 UTC, nicolalamacchia commented on src/pages/Login/Login.tsx
> +    (tokens) => {
```suggestion
  const onSuccess = useCallback((tokens) => {
```

this looks more consistent to what you did with `onError` and what we're doing elsewhere

2022-04-11 08:42 UTC, TomasBlazek3PG commented on src/pages/Login/Login.tsx
> +    (tokens) => {
Oh the prettier is not allowing me to have it this way unfortunatelly

2022-04-11 08:43 UTC, TomasBlazek3PG commented on src/components/OktaSignInWidget/OktaSignInWidget.tsx
> +              &nbsp;*
But here it makes sense. I dont want to break the line and be on the line alone.

2022-04-11 10:29 UTC, fabio-silva approved these changes

2022-04-11 16:26 UTC, fabio-silva approved these changes

2022-04-12 11:15 UTC, nicolalamacchia approved these changes

2022-04-12 11:15 UTC, merged