SAAS-338 runtime env config
percona-platform/saas-ui pull request #21
Opened 2020-09-10 20:04 UTC by nicolalamacchia

2020-09-14 03:36 UTC, atymchuk requested changes

2020-09-14 03:36 UTC, atymchuk commented on packages/platform-ui/.env
> +REACT_APP_PLATFORM_AUTH_API_BASE_URL=
This is probably not the best variable name, since it just a base url for everything, not only Auth API. Consider `REACT_APP_PLATFORM_BASE_URL`

2020-09-14 08:01 UTC, nicolalamacchia commented on packages/platform-ui/.env
> +REACT_APP_PLATFORM_AUTH_API_BASE_URL=
I agree, done

2020-09-14 08:34 UTC, atymchuk requested changes

2020-09-14 08:37 UTC, AlekSi commented on packages/platform-ui/src/react-app-env.d.ts
> +    NODE_ENV: 'development' | 'production' | 'test';
We will have more environments. For example, we will have temporary on-demand environments for integration testing.

I don't think that "API hostname" variable should be tied to NODE_ENV (IIUC what NODE_ENV is).

2020-09-14 08:38 UTC, atymchuk commented on packages/platform-ui/src/react-app-env.d.ts
> +    NODE_ENV: 'development' | 'production' | 'test';
That confirms we can add more types later when/if needed.

2020-09-14 08:39 UTC, nicolalamacchia commented on packages/platform-ui/src/react-app-env.d.ts
> +    NODE_ENV: 'development' | 'production' | 'test';
@atymchuk as per CRA's documentation, that's the default environment for unit tests

2020-09-14 08:40 UTC, AlekSi commented on packages/platform-ui/src/react-app-env.d.ts
> +    REACT_APP_PLATFORM_BASE_URL: string;
btw, do we need both `PUBLIC_URL` and `REACT_APP_PLATFORM_BASE_URL`?

2020-09-14 08:43 UTC, atymchuk commented on packages/platform-ui/src/react-app-env.d.ts
> +    NODE_ENV: 'development' | 'production' | 'test';
> I don't think that "API hostname" variable should be tied to NODE_ENV (IIUC what NODE_ENV is).
Normally, there would be a mapping between env names and domain names. @AlekSi  Do you have something in mind? If not, we will stick to this approach now and then refactor if necessary.

2020-09-14 08:44 UTC, atymchuk commented on packages/platform-ui/src/react-app-env.d.ts
> +    REACT_APP_PLATFORM_BASE_URL: string;
@nicolalamacchia  Not sure either if PUBLIC_URL should be there.

2020-09-14 08:45 UTC, AlekSi commented on packages/platform-ui/src/react-app-env.d.ts
> +    NODE_ENV: 'development' | 'production' | 'test';
What I have in mind is to avoid that mapping and use another variable (probably, REACT_APP_PLATFORM_BASE_URL defied below).

2020-09-14 08:46 UTC, nicolalamacchia commented on packages/platform-ui/src/react-app-env.d.ts
> +    REACT_APP_PLATFORM_BASE_URL: string;
`PUBLIC_URL` is the one pointing to the public folder used by CRA, this is just a namespace to have types when referring to those `process.env` variables, nothing more.

2020-09-14 08:49 UTC, nicolalamacchia commented on packages/platform-ui/src/react-app-env.d.ts
> +    NODE_ENV: 'development' | 'production' | 'test';
@AlekSi right now that variable is empty, I used it when developing: if someone wants to override it, they can create a `.env.local` file and make it point to the deployed dev environment if needed.

2020-09-14 09:29 UTC, AlekSi commented on packages/platform-ui/src/react-app-env.d.ts
> +    NODE_ENV: 'development' | 'production' | 'test';
It is okay as a stop-gap solution, but moving forward that someone should not want to override it: please use SaaS local setup for development, not dev or prod environments with disabled web security.

2020-09-14 09:59 UTC, atymchuk approved these changes

2020-09-14 10:08 UTC, nicolalamacchia commented on packages/platform-ui/src/react-app-env.d.ts
> +    NODE_ENV: 'development' | 'production' | 'test';
I agree, that should be the correct approach. @AlekSi, @atymchuk if you're positive that we won't need it, I might as well remove it (still, note that this is OT to this specific comment :))

2020-09-14 10:48 UTC, AlekSi commented on packages/platform-ui/src/react-app-env.d.ts
> +    NODE_ENV: 'development' | 'production' | 'test';
> if you're positive that we won't need it, I might as well remove it (still, note that this is OT to this specific comment :))

We are not in agreement on that (see Jira), so let's keep it for now

2020-09-14 10:49 UTC, AlekSi commented
@nicolalamacchia Please squash/merge at will

2020-09-14 11:13 UTC, nicolalamacchia commented on packages/platform-ui/src/react-app-env.d.ts
> +    REACT_APP_PLATFORM_BASE_URL: string;
Removed this code, since I think it was too confusing and wasn't adding much value :)

2020-09-15 00:24 UTC, atymchuk approved these changes

2020-09-15 07:49 UTC, merged