SAAS-899 disconnect instances
percona-platform/saas-ui pull request #221
Opened 2022-05-04 16:41 UTC by nicolalamacchia

2022-05-05 09:34 UTC, fabio-silva requested changes

2022-05-05 09:34 UTC, fabio-silva commented on src/pages/ManagePmmInstances/PmmInstanceList/PmmInstanceActions/PmmInstanceActions.tsx
> +  const handleDisconnectInstanceClick = () => {
We should probably use `useCallback` for these two as well

2022-05-05 09:34 UTC, fabio-silva commented on src/pages/ManagePmmInstances/PmmInstanceList/PmmInstanceActions/PmmInstanceDisconnectModal/PmmInstanceDisconnectModal.messages.ts
> + If your PMM is still accessible we recommend to perform disconnect via PMM Settings."`,
Maybe a comma after `accessible`?

2022-05-05 09:34 UTC, fabio-silva commented on src/pages/ManagePmmInstances/PmmInstanceList/PmmInstanceActions/PmmInstanceDisconnectModal/PmmInstanceDisconnectModal.messages.ts
> +    `Are you sure you want to remove this instance '${instanceName}'?
Not 100% sure, but it sounds better without `this`

2022-05-05 09:34 UTC, fabio-silva commented on src/pages/ManagePmmInstances/PmmInstanceList/PmmInstanceActions/PmmInstanceDisconnectModal/PmmInstanceDisconnectModal.tsx
> +                onClick={() => onClose()}
```suggestion
                onClick={onClose}
```

2022-05-05 09:57 UTC, nicolalamacchia commented on src/pages/ManagePmmInstances/PmmInstanceList/PmmInstanceActions/PmmInstanceDisconnectModal/PmmInstanceDisconnectModal.messages.ts
> + If your PMM is still accessible we recommend to perform disconnect via PMM Settings."`,
That's what I received by @catalinaadam, let's see what she thinks

2022-05-05 09:58 UTC, nicolalamacchia commented on src/pages/ManagePmmInstances/PmmInstanceList/PmmInstanceActions/PmmInstanceDisconnectModal/PmmInstanceDisconnectModal.messages.ts
> +    `Are you sure you want to remove this instance '${instanceName}'?
you're right, maybe with "the" instead of "this"

2022-05-05 10:01 UTC, nicolalamacchia commented on src/pages/ManagePmmInstances/PmmInstanceList/PmmInstanceActions/PmmInstanceActions.tsx
> +  const handleDisconnectInstanceClick = () => {
that's an interesting point. should we actually use `useCallback` for the other one? those variables are not changing, so I guess we can remove it. we are abusing `useCallback` in our codebase.

2022-05-05 10:04 UTC, nicolalamacchia commented on src/pages/ManagePmmInstances/PmmInstanceList/PmmInstanceActions/PmmInstanceDisconnectModal/PmmInstanceDisconnectModal.tsx
> +                onClick={() => onClose()}
good catch, done

2022-05-05 10:13 UTC, fabio-silva commented on src/pages/ManagePmmInstances/PmmInstanceList/PmmInstanceActions/PmmInstanceActions.tsx
> +  const handleDisconnectInstanceClick = () => {
Yeah, it depends on the use case. If they don't change and the component won't re-render often, it's ok to not use it

2022-05-05 10:14 UTC, fabio-silva approved these changes

2022-05-05 10:19 UTC, TomasBlazek3PG approved these changes

2022-05-11 19:37 UTC, fabio-silva requested changes

2022-05-11 19:37 UTC, fabio-silva commented on src/pages/ManagePmmInstances/PmmInstanceList/PmmInstanceActions/PmmInstanceActions.tsx
> +          name="minus-circle"
@nicolalamacchia can we go with fa icons? After we realized Grafana is not meant to be used outside, maybe we should avoid this SVG.

2022-05-12 09:16 UTC, nicolalamacchia commented on src/pages/ManagePmmInstances/PmmInstanceList/PmmInstanceActions/PmmInstanceActions.tsx
> +          name="minus-circle"
done

2022-05-12 09:28 UTC, fabio-silva approved these changes

2022-05-19 09:49 UTC, merged