SAAS-900 Put ToS under social login
percona-platform/saas-ui pull request #222
Opened 2022-05-05 10:15 UTC by TomasBlazek3PG

2022-05-05 10:29 UTC, fabio-silva requested changes

2022-05-05 10:29 UTC, fabio-silva commented on src/components/OktaSignInWidget/OktaSignInWidget.tsx
> +    socialToS(widgetRef);
Please declare those functions before calling them here, for two reasons:

- Both are function expressions, they are not hoisted;
- Both are `const`. Even if they were hoisted, they would have been unitialized and a reference error might be thrown.

2022-05-05 10:29 UTC, fabio-silva commented on src/components/OktaSignInWidget/OktaSignInWidget.tsx
> +      <a href={TERMS_OF_SERVICE_URL} target='_blank' rel='noreferrer'>
For compatibility reasons, please add to both anchors: `rel='noreferrer noopener'`

2022-05-05 10:29 UTC, fabio-silva commented on src/pages/Login/Login.styles.ts
> +        .tos-label a, .tos-label a {
Duplicate?

2022-05-05 11:13 UTC, TomasBlazek3PG commented on src/pages/Login/Login.styles.ts
> +        .tos-label a, .tos-label a {
Oh yeah it was suppose to be label a, p a but then I decided to use the class but forgot to get rid of the duplicate. Thanks.

2022-05-05 11:26 UTC, fabio-silva approved these changes

2022-05-05 11:26 UTC, fabio-silva commented on src/pages/Login/Login.styles.ts
> +        .tos-label a, .tos-label a {
👍

2022-05-12 12:37 UTC, nicolalamacchia requested changes

2022-05-12 12:37 UTC, nicolalamacchia commented on src/components/OktaSignInWidget/OktaSignInWidget.messages.ts
> +    // eslint-disable-next-line max-len
is this needed?

2022-05-12 12:37 UTC, nicolalamacchia commented on src/components/OktaSignInWidget/OktaSignInWidget.tsx
> +    // eslint-disable-next-line jsx-a11y/label-has-associated-control
is this needed?

2022-05-12 12:37 UTC, nicolalamacchia commented on src/components/OktaSignInWidget/OktaSignInWidget.tsx
> +  }
either use a `else if` here or return in the first if

2022-05-16 12:17 UTC, nicolalamacchia approved these changes

2022-05-23 14:01 UTC, nicolalamacchia approved these changes

2022-05-25 11:17 UTC, merged