SAAS-914 Ticket Overview
percona-platform/saas-ui pull request #226
Opened 2022-05-17 12:41 UTC by TomasBlazek3PG

https://files.slack.com/files-pri/T03FRR0BJ-F03GAFERYNL/image.png

2022-05-17 20:47 UTC, fabio-silva requested changes
Besides all the other points, I realise we're mixing `className` with `styles`. That can be avoided, like this: https://github.com/percona-platform/grafana/blob/main/public/app/percona/integrated-alerting/components/Severity/Severity.styles.ts

`stylesFactory` is considered deprecated (it does memoization), but we can still return a style object based on props without adding separate styles.

2022-05-17 20:47 UTC, fabio-silva commented on package.json
> +  "proxy": "https://portal-dev.percona.com",
I believe this is unintended

2022-05-17 20:47 UTC, fabio-silva commented on src/components/Charts/Pie/Pie.tsx
> +        {/* eslint-disable-next-line no-magic-numbers */}
Let's disable the rule for the whole file instead

2022-05-17 20:47 UTC, fabio-silva commented on src/components/SupportTicketOverview/Legend/Legend.tsx
> +            <div className={styles.colorNameNumber} key={item.department}>
Should key be here or on the parent instead?

2022-05-17 20:47 UTC, fabio-silva commented on src/components/SupportTicketOverview/Legend/Legend.tsx
> +          <div className={styles.item}>
missing key

2022-05-17 20:47 UTC, fabio-silva commented on src/components/SupportTicketOverview/SupportTicketOverview.tsx
> +  if ((!companyName || !orgId || !tickets) && !loading) return null;
Missing brackets

2022-05-17 20:47 UTC, fabio-silva commented on src/components/SupportTicketOverview/SupportTicketOverview.tsx
> +        // eslint-disable-next-line no-magic-numbers
Same as the other file for disabling the rule

2022-05-17 20:47 UTC, fabio-silva commented on src/components/SupportTicketOverview/SupportTicketOverview.tsx
> +              size={200}
Let's move these numbers to constants

2022-05-17 20:47 UTC, fabio-silva commented on src/components/SupportTicketOverview/SupportTicketOverview.tsx
> +    }, []);
Just to be sure: this `computedItems` is supposed to be the same across renders?

2022-05-26 11:53 UTC, TomasBlazek3PG commented on src/components/SupportTicketOverview/SupportTicketOverview.tsx
> +    }, []);
This is not the dependency array of useMemo. Its the accumulator of reduce function.

2022-05-27 12:28 UTC, fabio-silva requested changes

2022-05-27 12:28 UTC, fabio-silva commented on src/components/SupportTicketOverview/SupportTicketOverview.tsx
> +    }, []);
Oh, right, my bad!

2022-05-27 12:28 UTC, fabio-silva commented on src/store/orgs/org.actions.ts
> +      return transformOrganizations(data.data.orgs);
Can we remove this comment? Also, better do `result = await ...`, because `data.data` is a bit odd

2022-05-27 14:36 UTC, fabio-silva approved these changes

2022-06-14 14:45 UTC, nicolalamacchia approved these changes

2022-06-14 14:58 UTC, fabio-silva approved these changes

2022-06-15 13:09 UTC, merged