SAAS-917 fix customer org creation
percona-platform/saas-ui pull request #229
Opened 2022-05-26 09:13 UTC by nicolalamacchia

2022-05-26 09:23 UTC, fabio-silva requested changes

2022-05-26 09:23 UTC, fabio-silva commented on package.json
> +  "proxy": "https://portal-dev.percona.com",
```suggestion
```

2022-05-26 09:23 UTC, fabio-silva commented on src/store/orgs/org.actions.ts
> +      displayAndLogError(err);
Is it possible to have an API error with no status??

2022-05-26 09:23 UTC, nicolalamacchia commented on package.json
> +  "proxy": "https://portal-dev.percona.com",
Why? The proxy is only enabled in dev

2022-05-26 09:27 UTC, nicolalamacchia commented on src/store/orgs/org.actions.ts
> +      displayAndLogError(err);
yes, because the type of the error is unknown. it's not realistic, but theoretically possible

2022-05-26 09:29 UTC, fabio-silva commented on package.json
> +  "proxy": "https://portal-dev.percona.com",
Works for me. But in that case our README should be updated, as it assumes the configuration is hidden by default:

`When developing locally, you'll want to route your API requests to a dev server. To do so, add the following key to your package.json:`

2022-05-26 09:29 UTC, fabio-silva commented on src/store/orgs/org.actions.ts
> +      displayAndLogError(err);
👍

2022-05-26 09:29 UTC, fabio-silva approved these changes

2022-05-26 09:30 UTC, nicolalamacchia commented on package.json
> +  "proxy": "https://portal-dev.percona.com",
you're right, done!

2022-05-26 10:08 UTC, fabio-silva approved these changes

2022-06-16 09:53 UTC, fabio-silva approved these changes

2022-06-17 08:23 UTC, merged