SAAS-340 cypress integration
percona-platform/saas-ui pull request #24
Opened 2020-09-14 13:30 UTC by yurkovychv

2020-09-15 02:52 UTC, atymchuk commented on .github/workflows/tests.yml
> +
Consider renaming this file to `e2e.yml` - much more explicit.

2020-09-15 02:52 UTC, atymchuk commented on packages/platform-ui/cypress.json
> +  "baseUrl": "http://localhost:3000/",
That trailing slash may not be needed. Pls refer to https://docs.cypress.io/guides/references/best-practices.html#Configuration-file-cypress-json-by-default

2020-09-15 02:52 UTC, atymchuk commented on packages/platform-ui/cypress/fixtures/login.json
> +{
Does this have to be committed?

2020-09-15 11:13 UTC, yurkovychv commented on packages/platform-ui/cypress/fixtures/login.json
> +{
not for now actually, I removed it

2020-09-15 11:13 UTC, yurkovychv commented on packages/platform-ui/cypress.json
> +  "baseUrl": "http://localhost:3000/",
done, thanks

2020-09-15 11:13 UTC, yurkovychv commented on .github/workflows/tests.yml
> +
done, thanks

2020-09-16 07:40 UTC, atymchuk commented on packages/platform-ui/cypress/support/stub.services.js
> +      vary: origin,
Here `origin` seems to be a variable. Where should its value come from? If it is `window.origin`, then we should be explicit to avoid guessing.

2020-09-16 07:46 UTC, atymchuk commented on packages/platform-ui/cypress/integration/auth/constants.js
> +export const TERMS_OF_SERVICE_URL = 'https://per.co.na/pmm/platform-terms';
There is no need to copy those values, we could as well import them from where they are initially defined.

2020-09-16 07:50 UTC, atymchuk commented on packages/platform-ui/cypress/support/index.js
> +      nameParts.push(`${runnable.hookName} hook`)
```suggestion
      nameParts.push(`${runnable.hookName} hook`);
```

2020-09-16 07:50 UTC, atymchuk commented on packages/platform-ui/cypress/support/index.js
> +      item = item.parent
I see lots of code style violations here :|

2020-09-16 07:50 UTC, atymchuk commented on packages/platform-ui/cypress/support/index.js
> +      item = item.parent
```suggestion
      item = item.parent;
```

2020-09-16 07:51 UTC, atymchuk commented on packages/platform-ui/cypress/support/index.js
> +    }/${fullTestName} (failed).png`;
A space in a file name? Consider an underscore

2020-09-16 07:53 UTC, atymchuk commented on packages/platform-ui/cypress/support/index.js
> +import './commands'
```suggestion
import './commands';
```

2020-09-16 07:53 UTC, atymchuk commented on packages/platform-ui/cypress/support/index.js
> +import addContext from 'mochawesome/addContext'
```suggestion
import addContext from 'mochawesome/addContext';
```

2020-09-16 07:53 UTC, atymchuk commented on packages/platform-ui/cypress/support/index.js
> +import {configure} from '@testing-library/cypress'
```suggestion
import {configure} from '@testing-library/cypress';
```

2020-09-16 10:35 UTC, yurkovychv commented on packages/platform-ui/cypress/support/index.js
> +    }/${fullTestName} (failed).png`;
actually the final screenshot name will be something like: Login -- should be able to see the login form (failed).png

2020-09-16 10:36 UTC, yurkovychv commented on packages/platform-ui/cypress/integration/auth/constants.js
> +export const TERMS_OF_SERVICE_URL = 'https://per.co.na/pmm/platform-terms';
The intention was to make tests constants separated from the FE constants. In order to track changes and catch bugs

2020-09-16 10:37 UTC, yurkovychv commented on packages/platform-ui/cypress/support/stub.services.js
> +      vary: origin,
looks like we do not need it here, removed

2020-09-16 20:33 UTC, nicolalamacchia requested changes

2020-09-16 20:33 UTC, nicolalamacchia commented on packages/platform-ui/cypress/plugins/index.js
> +
This empty file is just an example, we shouldn't commit it now

2020-09-16 20:33 UTC, nicolalamacchia commented on packages/platform-ui/cypress/support/commands.js
> +// existing commands.
I would remove example lines and lines stating that a file is an example from these files

2020-09-16 20:33 UTC, nicolalamacchia commented on packages/platform-ui/cypress/support/index.js
> +import './commands'
This is marked as resolved, but still missing the semicolon. Same for the following lines.

2020-09-16 20:33 UTC, nicolalamacchia commented on packages/platform-ui/cypress/support/index.js
> +        .join(' -- ');
Please, add a comment explaining what this code does

2020-09-16 20:33 UTC, nicolalamacchia commented on packages/platform-ui/cypress/support/index.js
> +        .join(' -- ');
This whole block of code is pretty obscure

2020-09-16 20:33 UTC, nicolalamacchia commented on .github/workflows/e2e.yml
> +          wait-on-timeout: 120
Note that this is not necessarily the full project. We could end up having more than one package in the future. How would this scale?

2020-09-16 20:33 UTC, nicolalamacchia commented on .github/workflows/e2e.yml
> +        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
Please, give more details about the problem this solution is for

2020-09-17 07:28 UTC, yurkovychv commented on .github/workflows/e2e.yml
> +        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
`chokidar` was throwing `Error: ENOSPC: System limit for number of file watchers reached` during project startup in the workflow. For example: [in this workflow execution](https://github.com/percona-platform/saas-ui/runs/1116292311?check_suite_focus=true) in Start project and execute tests step

2020-09-17 07:30 UTC, yurkovychv commented on .github/workflows/e2e.yml
> +          wait-on-timeout: 120
All I need for starting test execution is to have the host up. As I understand we will have only one host even if we will have more packages

2020-09-17 07:32 UTC, yurkovychv commented on packages/platform-ui/cypress/plugins/index.js
> +
May I just remove the comments and leave this file as is? The project skeleton was generated by cypress. In order to avoid confusions in the future I'd leave this file

2020-09-17 07:50 UTC, yurkovychv commented on packages/platform-ui/cypress/support/index.js
> +import './commands'
It actually was provided: https://github.com/percona-platform/saas-ui/blob/85cb2bd9b47e566e4d2017c0ad47838f4482b0ba/packages/platform-ui/cypress/support/index.js#L17

2020-09-17 07:53 UTC, yurkovychv commented on packages/platform-ui/cypress/support/commands.js
> +// existing commands.
Done thanks.

2020-09-17 07:54 UTC, yurkovychv commented on packages/platform-ui/cypress/support/index.js
> +        .join(' -- ');
Done

2020-09-17 07:54 UTC, yurkovychv commented on packages/platform-ui/cypress/support/index.js
> +        .join(' -- ');
Added comments

2020-09-17 07:56 UTC, yurkovychv commented on packages/platform-ui/cypress/support/index.js
> +      item = item.parent
Could you recheck once again? Is it ok now?

2020-09-17 08:15 UTC, nicolalamacchia requested changes

2020-09-17 08:15 UTC, nicolalamacchia commented on .github/workflows/e2e.yml
> +          wait-on-timeout: 120
Not sure I understand. Each package could potentially have a `start` script, which could launch its own local server. Anyway, let's keep this for now, but let's be mindful about this.

2020-09-17 08:15 UTC, nicolalamacchia commented on .github/workflows/e2e.yml
> +        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
Could you add this to that comment please? :) Also, please consider this is a workaround and it's not documented.

2020-09-17 08:15 UTC, nicolalamacchia commented on packages/platform-ui/cypress/support/index.js
> +    }
This is still very difficutl to understand, please try to convert it in a more readable code (using for example maps and reducers) or at least document each part in detail.

2020-09-17 08:15 UTC, nicolalamacchia commented on packages/platform-ui/cypress/integration/auth/signup.spec.js
> +    cy.url().should('contain', '/login')
```suggestion
    cy.url().should('contain', '/login');
```

2020-09-17 08:15 UTC, nicolalamacchia commented on packages/platform-ui/cypress/integration/auth/locators.js
> +  termsValidation: 'qa:consent-field-error-message'
```suggestion
  termsValidation: 'qa:consent-field-error-message',
```

2020-09-17 08:15 UTC, nicolalamacchia commented on packages/platform-ui/cypress/support/index.js
> +  separator: ':'
```suggestion
  separator: ':',
```

2020-09-17 08:15 UTC, nicolalamacchia commented on packages/platform-ui/cypress/support/index.js
> +setup(config);
```suggestion

setup(config);
```

2020-09-17 08:31 UTC, nicolalamacchia commented on packages/platform-ui/cypress/plugins/index.js
> +
If that's the case, you can leave it as it is. Please notice that you removed the `/// <reference types="cypress" />
` line in a recent commit

2020-09-17 08:33 UTC, yurkovychv commented on packages/platform-ui/cypress/plugins/index.js
> +
yeah, my bad

2020-09-17 08:33 UTC, nicolalamacchia requested changes

2020-09-17 08:33 UTC, nicolalamacchia commented on packages/platform-ui/cypress/plugins/index.js
> +// This function is called when a project is opened or re-opened (e.g. due to
I think `/// <reference types="cypress" />` it's missing

2020-09-17 08:34 UTC, yurkovychv commented on packages/platform-ui/cypress/plugins/index.js
> +// This function is called when a project is opened or re-opened (e.g. due to
just checked, It wasn't there

2020-09-17 09:18 UTC, nicolalamacchia commented on packages/platform-ui/cypress/plugins/index.js
> +// This function is called when a project is opened or re-opened (e.g. due to
Mmm, that's strange, I see it here: https://github.com/percona-platform/saas-ui/commit/124de59910b5245946975fd708250e7939d1e989#diff-4d8b973b2577a8f2d0b1e06f8e0d298a

2020-09-17 09:21 UTC, yurkovychv commented on packages/platform-ui/cypress/plugins/index.js
> +// This function is called when a project is opened or re-opened (e.g. due to
Oh yeah, I replied to this in the discussion above) thought this is another file

2020-09-17 09:22 UTC, yurkovychv commented on .github/workflows/e2e.yml
> +          wait-on-timeout: 120
sure, will keep in mind

2020-09-17 09:23 UTC, yurkovychv commented on packages/platform-ui/cypress/support/index.js
> +    }
updated the code, please check it

2020-09-17 09:24 UTC, yurkovychv commented on .github/workflows/e2e.yml
> +        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
Done

2020-09-18 10:28 UTC, nicolalamacchia approved these changes

2020-09-22 12:41 UTC, atymchuk commented on packages/platform-ui/cypress/integration/auth/locators.js
> +export const authLocators = {
nit: It's generally a good idea to sort the keys in objects like this one

2020-09-22 12:43 UTC, atymchuk approved these changes

2020-09-22 15:09 UTC, merged