SAAS-988 Kubernetes cluster creation
percona-platform/saas-ui pull request #253
Opened 2022-06-23 22:31 UTC by nicolalamacchia

2022-06-27 11:37 UTC, TomasBlazek3PG submitted a review, later dismissed

2022-06-27 20:57 UTC, fabio-silva requested changes

2022-06-28 06:59 UTC, TomasBlazek3PG commented on src/pages/K8sClusterCreation/K8sClusterCreation.service.ts
> +}) as BaseQueryFn<string | FetchArgs, unknown, K8sClusterStatusError, {}>;
No you dont need to worry. We are planning on moving to RTK Query and this is just experimental usage only on one page. We are planning on using it globally.

2022-06-28 06:59 UTC, TomasBlazek3PG commented on src/pages/K8sClusterCreation/K8sClusterCreation.messages.ts
> +    'Ready to experiment with Percona Monitoring and Management DBaaS or Percona Operators? Launch and user a free temporary Kubernetes cluster.',
Good catch!

2022-08-10 09:35 UTC, fabio-silva approved these changes

2022-08-10 09:47 UTC, merged