SAAS-764 added-improvements-on-table
percona-platform/saas-ui pull request #261
Opened 2022-07-20 09:19 UTC by MaksimMalakhovSimbirsoft

- added pagination and sorting;
- prepared statusMap object for mapping in future;
- need icons and colors for different statuses to be defined, I need it to finish mapping status;
- the last column now is requested by, because it may consist of empty data;
- https://jira.percona.com/browse/SAAS-764

2022-07-20 09:24 UTC, fabio-silva requested changes

2022-07-20 09:24 UTC, fabio-silva commented on src/pages/Dashboard/TicketList/TicketStatus/TicketStatus.types.ts
> +    icon: undefined;
What is `icon` supposed to be exactly? A string? If so, please let's declare it as `icon?: string`

2022-07-20 09:24 UTC, fabio-silva commented on src/pages/Dashboard/TicketList/TicketStatus/TicketStatus.types.ts
> +  [key: string]: {
I believe the key should be  of the `OrgTicketStatus` type, right?

2022-07-20 10:02 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Dashboard/TicketList/TicketStatus/TicketStatus.types.ts
> +    icon: undefined;
Ok, I;ll change to string.

2022-07-20 10:02 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Dashboard/TicketList/TicketStatus/TicketStatus.types.ts
> +  [key: string]: {
I;ll check right now

2022-07-20 10:06 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Dashboard/TicketList/TicketStatus/TicketStatus.types.ts
> +  [key: string]: {
Well , it seems like that , now we have 
enum OrgTicketStatus {
  Open = 'Open',
  Closed = 'Closed',
  Resolved = 'Resolved',
},
I have more statuses: open, pending - awaiting customer, scheduled, new, authorized. I'll add them

2022-07-20 10:29 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Dashboard/TicketList/TicketStatus/TicketStatus.types.ts
> +    icon: undefined;
fixed

2022-07-20 11:28 UTC, fabio-silva submitted a review, later dismissed

2022-07-20 13:31 UTC, nicolalamacchia requested changes

2022-07-20 13:31 UTC, nicolalamacchia commented on src/pages/Dashboard/TicketList/TicketStatus/TicketStatus.tsx
> +
This is tho the way we use styles, please check any other `*.styles.ts` files in the repo

2022-07-21 09:36 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Dashboard/TicketList/TicketStatus/TicketStatus.tsx
> +
I removed color from StatusMap object, because we've already have getStyles and getColor functions, we give status as parameter and it works well.

2022-07-25 09:59 UTC, nicolalamacchia approved these changes

2022-07-25 10:00 UTC, fabio-silva approved these changes

2022-07-25 10:06 UTC, merged