SAAS-1019 post social sign up marketing consent
percona-platform/saas-ui pull request #262
Opened 2022-07-20 10:00 UTC by nicolalamacchia

2022-08-05 08:56 UTC, fabio-silva requested changes

2022-08-05 08:56 UTC, fabio-silva commented on src/components/MarketingBanner/MarketingBanner.messages.ts
> +  description: 'Want to know  the latest Percona Platform and Percona services news?',
```suggestion
  description: 'Want to know the latest Percona Platform and Percona services news?',
```

2022-08-05 08:56 UTC, fabio-silva commented on src/components/MarketingBanner/MarketingBanner.tsx
> +      if (typeof marketing === 'undefined') {
is there a reason why we're checking typeof instead of actually comparing to undefined?

2022-08-05 08:56 UTC, fabio-silva commented on src/components/MarketingBanner/MarketingBanner.tsx
> +      setLoading(false);
Since we're not awaiting for the dispatch to resolve, the loading will be set to false immediately

2022-08-06 03:36 UTC, MaksimMalakhovSimbirsoft submitted a review, later dismissed

2022-08-08 18:49 UTC, MaksimMalakhovSimbirsoft submitted a review, later dismissed

2022-08-09 11:33 UTC, fabio-silva approved these changes

2022-08-11 11:09 UTC, fabio-silva approved these changes

2022-08-17 18:10 UTC, MaksimMalakhovSimbirsoft approved these changes

2022-08-18 10:00 UTC, merged