SAAS-987 add query resend
percona-platform/saas-ui pull request #270
Opened 2022-08-08 08:18 UTC by MaksimMalakhovSimbirsoft

- added resend link;
- added service using RTK query, NEED FOR CORRECT ENDPOINT!!;
![SCREENFORSHARE](https://user-images.githubusercontent.com/107244329/183372257-3d1804cd-e64e-488d-9e1f-c44940dc7579.png)

2022-08-08 09:39 UTC, TomasBlazek3PG requested changes

2022-08-08 09:39 UTC, TomasBlazek3PG commented on src/pages/ManageOrganization/MembersList/MembersList.service.ts
> +  baseUrl: '',
You are missing base url

2022-08-08 09:39 UTC, TomasBlazek3PG commented on src/pages/ManageOrganization/MembersList/MembersList.service.ts
> +        // body: { organizationId, memberId },
Why is it here?

2022-08-08 09:39 UTC, TomasBlazek3PG commented on src/pages/ManageOrganization/MembersList/MembersList.tsx
> +                    <a className={styles.link} onClick={() => handleResend(orgId, memberId)}>
For this we are using `<LinkButton variant="link" />`

2022-08-08 09:55 UTC, nicolalamacchia submitted a review, later dismissed

2022-08-08 09:55 UTC, nicolalamacchia commented on src/pages/ManageOrganization/MembersList/MembersList.service.ts
> +  baseUrl: '',
that's correct, we don't need a base URL in this case, we can leave it as it is for now

2022-08-08 09:55 UTC, nicolalamacchia commented on src/pages/ManageOrganization/MembersList/MembersList.tsx
> +                    <a className={styles.link} onClick={() => handleResend(orgId, memberId)}>
that's correct, we don't need a base URL in this case, we can leave it as it is for now

2022-08-08 09:56 UTC, nicolalamacchia commented on src/pages/ManageOrganization/MembersList/MembersList.service.ts
> +  baseUrl: '',
that's correct, we don't need a base URL in this case, we can leave it as it is for now

2022-08-09 17:36 UTC, MaksimMalakhovSimbirsoft commented on src/pages/ManageOrganization/MembersList/MembersList.service.ts
> +        // body: { organizationId, memberId },
I uncommented this

2022-08-09 17:45 UTC, MaksimMalakhovSimbirsoft commented
![Снимок экрана от 2022-08-09 20-00-13](https://user-images.githubusercontent.com/107244329/183723070-4329a612-de59-49e7-96a3-f341b20c7a33.png)
added conditions to resending... You must be admin role and member status must be PROVISIONED. Well maybe for testing I could remove member status condition and this allows to check resend link

2022-08-10 07:03 UTC, TomasBlazek3PG approved these changes

2022-08-10 09:56 UTC, nicolalamacchia commented on src/core/api/endpoints.ts
> +    resendEmail: (orgId: string, memberId: string) => `/v1/orgs/${orgId}/members/${memberId}`,
Is this the correct endpoint? if so, remove the comment

2022-08-10 09:57 UTC, MaksimMalakhovSimbirsoft commented on src/core/api/endpoints.ts
> +    resendEmail: (orgId: string, memberId: string) => `/v1/orgs/${orgId}/members/${memberId}`,
Oh, sure. It is correct.

2022-08-10 10:02 UTC, MaksimMalakhovSimbirsoft commented on src/core/api/endpoints.ts
> +    resendEmail: (orgId: string, memberId: string) => `/v1/orgs/${orgId}/members/${memberId}`,
Done

2022-08-12 08:47 UTC, TomasBlazek3PG approved these changes

2022-08-18 14:54 UTC, nicolalamacchia submitted a review, later dismissed

2022-08-19 06:22 UTC, TomasBlazek3PG requested changes

2022-08-19 06:22 UTC, TomasBlazek3PG commented on src/pages/ManageOrganization/MembersList/MembersList.tsx
> +                  {orgRole === 'Admin' && status === MemberStatus.provisioned && (
Please use the admin string defined in ROLES in the constants

2022-08-19 06:40 UTC, MaksimMalakhovSimbirsoft commented on src/pages/ManageOrganization/MembersList/MembersList.tsx
> +                  {orgRole === 'Admin' && status === MemberStatus.provisioned && (
ok

2022-08-19 08:46 UTC, TomasBlazek3PG approved these changes

2022-08-22 07:09 UTC, TomasBlazek3PG approved these changes

2022-08-22 09:41 UTC, nicolalamacchia approved these changes

2022-08-22 10:14 UTC, merged