Refactor sign up page tests
percona-platform/saas-ui pull request #276
Opened 2022-08-15 19:59 UTC by VoK0

* implement short imports 
* rewrite signUp tests 
* implement Mailosaur

2022-08-17 14:44 UTC, peterSirotnak commented on ui-tests/tsconfig.json
> +      "@testtypes/*": ["support/types/*"],
please use camelCase @testTypes

2022-08-17 14:45 UTC, peterSirotnak commented on ui-tests/tests/auth/signUp.spec.ts
> +    await expect(page).toHaveURL(`${`${baseURL}/${signUpPage.links.loginAddressLink}`}`);
This url is not correct

2022-08-17 14:45 UTC, peterSirotnak commented on ui-tests/support/types/signUpFormErros.interface.ts
> +  }
new line at the end of the file

2022-08-17 14:46 UTC, peterSirotnak requested changes
Please fix comments

2022-08-18 08:52 UTC, peterSirotnak commented on ui-tests/tests/auth/signUp.spec.ts
> +      signUpPage.messages.verificationEmailSentTitle,
Test fails:
Error: expect(received).toHaveText(expected)

    Expected string: "Verification email sent"
    Received string: ""
    Call log:
      - expect.toHaveText with timeout 5000ms
      - waiting for selector "h2.title"

2022-08-24 09:01 UTC, peterSirotnak commented on ui-tests/tests/auth/signUp.spec.ts
> +    const inputErrorMessagesTexts = await signUpPage.locators.fieldFormValidatior.evaluateAll(
fieldFormValidatior -> fieldFormValidator just a typo

2022-08-24 09:02 UTC, VoK0 commented on ui-tests/tsconfig.json
> +      "@testtypes/*": ["support/types/*"],
Fixed

2022-08-24 09:03 UTC, peterSirotnak commented on ui-tests/tests/auth/signUp.spec.ts
> +    page.goto(importantLink);
please add await for page.goto(importantLink); and verification that user is on correct page.

2022-08-24 09:04 UTC, VoK0 commented on ui-tests/tests/auth/signUp.spec.ts
> +    const inputErrorMessagesTexts = await signUpPage.locators.fieldFormValidatior.evaluateAll(
Fixed

2022-08-24 09:22 UTC, VoK0 commented on ui-tests/tests/auth/signUp.spec.ts
> +      signUpPage.messages.verificationEmailSentTitle,
I am not able to replicate this issue :/

2022-08-24 09:22 UTC, VoK0 commented on ui-tests/tests/auth/signUp.spec.ts
> +    page.goto(importantLink);
Fixed.

2022-08-24 09:31 UTC, peterSirotnak commented on ui-tests/tests/auth/signUp.spec.ts
> +  let succUser: User;
plese delete this user after tests

2022-08-25 06:42 UTC, peterSirotnak approved these changes
LGTM

2022-08-25 07:13 UTC, merged