SAAS-249 Use packaged action
percona-platform/saas-ui pull request #28
Opened 2020-09-24 11:12 UTC by palash25

2020-09-24 12:28 UTC, AlekSi requested changes

2020-09-24 12:28 UTC, AlekSi commented on .github/workflows/ci.yml
> +        uses: percona-platform/extract-docker-tag-action@SAAS-249-Package-Image-Tag-Extraction
Why send PR with that branch everywhere if it will be merged soon?

2020-09-24 12:28 UTC, AlekSi commented on Makefile
>  	cd tools && go build -o ../bin/get-stale-packages ./get-stale-packages
Why keep that action?

2020-09-24 12:28 UTC, AlekSi commented on tools/go.mod
> +	github.com/stretchr/testify v1.6.1 // indirect
This line should be removed

2020-09-24 12:32 UTC, palash25 commented on .github/workflows/ci.yml
> +        uses: percona-platform/extract-docker-tag-action@SAAS-249-Package-Image-Tag-Extraction
will change it once the action gets merged, I thought I will test the action right away on all the repos at the same time

2020-09-24 12:33 UTC, AlekSi commented on .github/workflows/ci.yml
> +        uses: percona-platform/extract-docker-tag-action@SAAS-249-Package-Image-Tag-Extraction
And distract people in all repositories, and then update all PRs, and distract them again? :) Please check Slack

2020-09-24 12:35 UTC, palash25 commented on .github/workflows/ci.yml
> +        uses: percona-platform/extract-docker-tag-action@SAAS-249-Package-Image-Tag-Extraction
will keep that in mind, sorry :smiley:

2020-09-24 12:35 UTC, palash25 commented on Makefile
>  	cd tools && go build -o ../bin/get-stale-packages ./get-stale-packages
its not in this ticket's scope to remove that one

2020-09-24 12:36 UTC, AlekSi commented on Makefile
>  	cd tools && go build -o ../bin/get-stale-packages ./get-stale-packages
Yeah, it is in a scope of the ticket that is "Done". So let's not create more tickets for fixing done tickets, but just fix that instead – it will be faster

2020-09-24 15:21 UTC, artemgavrilov reviewed
Looks like we can remove `reviewdog` from Makefile and `tools` dir. There is no go code in that repo as I see.

2020-09-25 09:00 UTC, palash25 commented
@artemgavrilov removed reviewdog, I also had to delete `go.sum` since it was empty after removing reviewdog

2020-09-25 11:10 UTC, artemgavrilov commented
> @artemgavrilov removed reviewdog, I also had to delete `go.sum` since it was empty after removing reviewdog

@palash25 you can remove the whole `tools` directory, as there are no tools anymore)

2020-09-25 12:19 UTC, palash25 commented
done @artemgavrilov

2020-09-25 14:11 UTC, artemgavrilov approved these changes

2020-09-28 11:11 UTC, artemgavrilov approved these changes

2020-09-29 16:10 UTC, AlekSi approved these changes

2020-09-30 10:39 UTC, nicolalamacchia approved these changes

2020-09-30 14:47 UTC, atymchuk approved these changes

2020-09-30 16:28 UTC, merged