SAAS-1038: New activation page
percona-platform/saas-ui pull request #284
Opened 2022-08-31 13:40 UTC by TomasBlazek3PG

![image](https://user-images.githubusercontent.com/100355118/187692531-9afb75bf-5b38-4cef-bea2-76ffb57686d9.png)

2022-08-31 14:15 UTC, fabio-silva requested changes

2022-08-31 14:15 UTC, fabio-silva commented on src/core/api/endpoints.ts
> +    ActivateProfile: '/v1/auth/UpdateProfile',
same as the one above?

2022-08-31 14:15 UTC, fabio-silva commented on src/pages/Activation/Activation.messages.ts
> +      upperCase: 'Password needs to contain a uppercase letter',
```suggestion
      upperCase: 'Password needs to contain an uppercase letter',
```

2022-08-31 14:15 UTC, fabio-silva commented on src/pages/Activation/Activation.tsx
> +  const query = useMemo(() => new URLSearchParams(search), [search]);
Do we really need `useMemo` for this? It seems an overkill, given that all those `q<name>` consts are derived from it and aren't changing when it changes as well.
We're using `search` as dependency. Is it gonna change unless we actually refresh the page, in this case? If so, `useMemo` brings no value.

2022-08-31 14:15 UTC, fabio-silva commented on src/pages/Activation/Activation.tsx
> +                          <li>Not be the one of your last 4 passwords</li>
```suggestion
                          <li>Not be one of your last 4 passwords</li>
```

2022-09-09 09:35 UTC, fabio-silva submitted a review, later dismissed

2022-09-09 09:47 UTC, MaksimMalakhovSimbirsoft approved these changes

2022-09-12 13:02 UTC, MaksimMalakhovSimbirsoft approved these changes

2022-09-13 09:31 UTC, merged