SAAS-1071: Add delete modal
percona-platform/saas-ui pull request #287
Opened 2022-09-05 10:54 UTC by MaksimMalakhovSimbirsoft

![555](https://user-images.githubusercontent.com/107244329/188432741-87586ad6-f0c2-4165-beb0-369ce1560266.png);
![444](https://user-images.githubusercontent.com/107244329/188432742-b4e51058-93ed-4411-ac08-0a26f1edbeb7.png);

2022-09-05 11:07 UTC, fabio-silva requested changes

2022-09-05 11:07 UTC, fabio-silva commented on src/pages/ManageOrganization/OrganizationView/OrganizationDeleteModal/OrganizationDeleteModal.tsx
> +                <Input type="text" width={35} onInput={handleInput} />
Let's use @percona/platform-core `TextInputField`, it's made to work with react-final-form. No need to use handlers here or useState for the value. Besides `handleSubmit`, render props also contain `values`, and that's an object `{[key: string]: any}` with the form's values, where `key` is the field name (e.g. orgName).
So, for those buttons, you just need to do something like `disabled={values.orgName !== orgName}`

2022-09-05 11:07 UTC, fabio-silva commented on src/pages/ManageOrganization/OrganizationView/OrganizationDeleteModal/OrganizationDeleteModal.tsx
> +                  disabled={!(inputValue === orgName)}
```suggestion
                  disabled={inputValue !== orgName}
```

2022-09-05 11:09 UTC, fabio-silva commented
Two questions about the design:
- Is orange the color chosen by UI/UX?
- The text is starting way after the warning, in terms of padding. I don't know if there's a mock for this, but I guess the text should be left-aligned with the warning

2022-09-06 06:50 UTC, TomasBlazek3PG requested changes
Please check it if it works in dark theme as well.

Needs tests!

2022-09-06 06:50 UTC, TomasBlazek3PG commented on src/pages/ManageOrganization/OrganizationView/OrganizationDeleteModal/OrganizationDeleteModal.messages.ts
> +  deleteOrganizationWarningLabel:
DO we need to put the "deleteOrganization" in front of everything if we are in OrganizationDeleteModal?

2022-09-06 06:50 UTC, TomasBlazek3PG commented on src/pages/ManageOrganization/OrganizationView/OrganizationDeleteModal/OrganizationDeleteModal.styles.ts
> +    line-height: 20px;
This is due to no similar option in themes typography?

2022-09-06 06:50 UTC, TomasBlazek3PG commented on src/pages/ManageOrganization/OrganizationView/OrganizationDeleteModal/OrganizationDeleteModal.styles.ts
> +    font-weight: bold;
Please use themes typography fontWeight

2022-09-06 06:50 UTC, TomasBlazek3PG commented on src/pages/ManageOrganization/OrganizationView/OrganizationDeleteModal/OrganizationDeleteModal.styles.ts
> +    font-weight: bold;
The same applies to the whole file

2022-09-06 06:50 UTC, TomasBlazek3PG commented on src/pages/ManageOrganization/OrganizationView/OrganizationDeleteModal/OrganizationDeleteModal.styles.ts
> +    line-height: 20px;
The same applies to the whole file

2022-09-07 09:30 UTC, fabio-silva requested changes

2022-09-07 09:30 UTC, fabio-silva commented on src/pages/ManageOrganization/OrganizationView/OrganizationDeleteModal/OrganizationDeleteModal.tsx
> +                  disabled={values[orgName] !== orgName}
The input should be like this:
`<TextInputField name="orgName" fieldClassName={styles.inputOrg} />`

Then:
`variant={values.orgName === orgName ? "primary" : "secondary"}`
`disabled={values.orgName !== orgName}`
`buttonClassName={values.orgName === orgName ? "styles.activeColorButton" : "styles.disabledColorButton"}`

2022-09-07 09:42 UTC, MaksimMalakhovSimbirsoft commented on src/pages/ManageOrganization/OrganizationView/OrganizationDeleteModal/OrganizationDeleteModal.tsx
> +                  disabled={values[orgName] !== orgName}
Done

2022-09-07 09:45 UTC, fabio-silva requested changes

2022-09-07 09:45 UTC, fabio-silva commented on src/pages/ManageOrganization/OrganizationView/OrganizationDeleteModal/OrganizationDeleteModal.styles.ts
> +    margin-top: 32px;
I see many hardcoded margins, paddings, etc. What about the values from theme?

2022-09-07 12:48 UTC, MaksimMalakhovSimbirsoft commented on src/pages/ManageOrganization/OrganizationView/OrganizationDeleteModal/OrganizationDeleteModal.styles.ts
> +    margin-top: 32px;
Done

2022-09-07 13:06 UTC, fabio-silva requested changes

2022-09-07 13:06 UTC, fabio-silva commented on src/pages/ManageOrganization/OrganizationView/OrganizationDeleteModal/OrganizationDeleteModal.tsx
> +                  disabled={values[orgName] !== orgName}
@MaksimMalakhovSimbirsoft This fix wasn't done

2022-09-08 14:04 UTC, TomasBlazek3PG approved these changes

2022-09-08 18:12 UTC, merged