SAAS-334 get email from refresh session API response
percona-platform/saas-ui pull request #30
Opened 2020-09-28 12:14 UTC by nicolalamacchia

2020-09-28 14:16 UTC, tiagomotasantos commented on packages/platform-ui/src/store/auth/auth.reducer.ts
> +)<undefined, { email: string }, Error>();
Maybe use interface for the action payload here

2020-09-28 16:00 UTC, atymchuk requested changes

2020-09-29 14:33 UTC, nicolalamacchia commented on packages/platform-ui/src/store/auth/auth.reducer.ts
> +)<undefined, { email: string }, Error>();
Ok I did that, using `Pick<...>`

2020-09-29 15:50 UTC, tiagomotasantos approved these changes

2020-09-29 17:32 UTC, tiagomotasantos approved these changes

2020-09-29 17:40 UTC, atymchuk approved these changes

2020-09-29 18:05 UTC, merged