SAAS-1133: Add promo banner component
percona-platform/saas-ui pull request #303
Opened 2022-09-28 12:53 UTC by MaksimMalakhovSimbirsoft

![screen_1](https://user-images.githubusercontent.com/107244329/192783166-9ae931f9-5132-4505-a294-22fdd6e2b685.png)
![screen2](https://user-images.githubusercontent.com/107244329/192783176-b22c45a0-47eb-4f39-b14d-b0a343ecb6e6.png)

2022-09-30 07:57 UTC, TomasBlazek3PG commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.styles.ts
> +    flex: 0 1 calc(35% - ${spacing.lg});
What do you calculate here? isnt it possible to achieve this in a different manner?

2022-09-30 07:59 UTC, TomasBlazek3PG commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.tsx
> +  const viewEntitlements = useCallback(
This does not need to be in useCallback but its not necessary a mistake. So dont fix it.

2022-09-30 08:02 UTC, TomasBlazek3PG commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.tsx
> +          <Overlay className={styles.cardOverlay} isPending={isPending}>
What does this do? If its a loader then we should use the SVG loaders we just integrated.

2022-09-30 08:04 UTC, TomasBlazek3PG commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.tsx
> +                    onClick={viewEntitlements(true)}
Needs to be `() => viewEntitlements(true)`

2022-09-30 08:04 UTC, TomasBlazek3PG commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.tsx
> +          <EntitlementsModal entitlements={entitlements} onClose={viewEntitlements(false)} />
The same as above

2022-09-30 08:07 UTC, TomasBlazek3PG commented
I am missing tests and please make sure it works in dark theme.

2022-09-30 13:18 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.tsx
> +                    onClick={viewEntitlements(true)}
if I change to () => viewEntitlements(true) it is not works.

2022-09-30 13:20 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.tsx
> +          <EntitlementsModal entitlements={entitlements} onClose={viewEntitlements(false)} />
The same here

2022-09-30 14:11 UTC, TomasBlazek3PG commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.tsx
> +                    onClick={viewEntitlements(true)}
Please dont mark unresolved comments as resolved.
https://upmostly.com/tutorials/react-onclick-event-handling-with-examples
You cant call the setter in this manner. This function is called every time the function is rendered and not when its clicked as you desire. 
If it doesnt work when written correctly then you have a bug.

2022-09-30 19:21 UTC, fabio-silva requested changes
Fabio: - Besides the comments: are the banner and the contacts cards aligned and with the same height? Maybe it's me, but it seems they are not.

Maxim: - Seems I fixed it. If it is that u mean)

2022-09-30 19:21 UTC, fabio-silva commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.tsx
> +                    onClick={viewEntitlements(true)}
Tomas is right, Maksim. The onclick should get the function reference, not an invocation.
The bug is in your `viewEntitlements` function: your callback is returning a function, which is why luckily your code runs the way you wrote it. Please remove the extra arrow.

2022-09-30 19:21 UTC, fabio-silva commented on src/pages/Dashboard/PromoBanner/PromoBanner.messages.ts
> +    'Receive alerts via API, Slack, Email, webhook, PagerDuty, VictorOps, or over 15 other notification channels',
```suggestion
    'Receive alerts via API, Slack, Email, Webhook, PagerDuty, VictorOps, or over 15 other notification channels',
```

2022-09-30 19:21 UTC, fabio-silva commented on src/pages/Dashboard/PromoBanner/PromoBanner.messages.ts
> +  pmmAlertingLabel: 'PMM’s alerting is now ready to monitor your production databases!',
```suggestion
  pmmAlertingLabel: 'PMM’s Alerting is now ready to monitor your production databases!',
```

2022-10-01 09:25 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.tsx
> +                    onClick={viewEntitlements(true)}
Done!

2022-10-01 09:25 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.tsx
> +          <EntitlementsModal entitlements={entitlements} onClose={viewEntitlements(false)} />
Done!

2022-10-01 09:38 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.styles.ts
> +    margin-top: 56px;
The margin according to figma, just changed it to spacing.base * 7

2022-10-01 09:50 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Dashboard/PromoBanner/PromoBanner.messages.ts
> +  pmmAlertingLabel: 'PMM’s alerting is now ready to monitor your production databases!',
Changed

2022-10-01 09:50 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Dashboard/PromoBanner/PromoBanner.messages.ts
> +    'Receive alerts via API, Slack, Email, webhook, PagerDuty, VictorOps, or over 15 other notification channels',
Changed

2022-10-01 11:34 UTC, fabio-silva requested changes
Let's start using descriptive commit messages. "Hotfix" and "hotfix 2" doesn't say much to any of other devs, even less when it's open source code.

2022-10-01 11:34 UTC, fabio-silva commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.tsx
> +    setIsEntilementsVisible(!isEntitlementsVisible);
Two questions:
- Why was it `true` before and now you're toggling it?
- If it's a toggle we need, the better way is `setIsEntilementsVisible((visible) => !visible)`

2022-10-01 11:36 UTC, fabio-silva commented
@MaksimMalakhovSimbirsoft please do not edit our comments, as we can't track the answers like that. Just quote reply.

2022-10-02 16:35 UTC, fabio-silva commented
@MaksimMalakhovSimbirsoft Please address the comment before re-requesting a review

2022-10-03 09:18 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.styles.ts
> +    flex: 0 1 calc(35% - ${spacing.lg});
I removed calc

2022-10-03 09:21 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.tsx
> +          <Overlay className={styles.cardOverlay} isPending={isPending}>
Yeah, I am planning to remove it , I've prepared content loader for it,

2022-10-03 10:04 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.tsx
> +    setIsEntilementsVisible(!isEntitlementsVisible);
Fabio, I've just removes viewEntitlements, dont know why it was really need because I didnt write it, also didnt know why it was in useCallback and returning a funtion, but I've just written like this

2022-10-03 10:04 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.tsx
> +    setIsEntilementsVisible(!isEntitlementsVisible);
{isEntitlementsVisible && (
          <EntitlementsModal entitlements={entitlements} onClose={() => setIsEntilementsVisible(false)} />
        )}

2022-10-03 10:04 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Dashboard/Contacts/AccountInfo/AccountInfo.tsx
> +    setIsEntilementsVisible(!isEntitlementsVisible);
<IconButton
                    name="list-ul"
                    size="lg"
                    className={styles.icon}
                    onClick={() => setIsEntilementsVisible(true)}
                    data-testid="entitlements-button"
                  />

2022-10-03 10:41 UTC, MaksimMalakhovSimbirsoft commented
> I am missing tests and please make sure it works in dark theme.

Done, i've added screenshots

2022-10-03 10:43 UTC, MaksimMalakhovSimbirsoft commented
> Besides the comments: are the banner and the contacts cards aligned and with the same height? Maybe it's me, but it seems they are not.

It is according to figma, ![image](https://user-images.githubusercontent.com/107244329/193403327-8eefbf27-69e9-423b-83fa-6153a5164d79.png)

2022-10-03 10:45 UTC, MaksimMalakhovSimbirsoft commented
> Let's start using descriptive commit messages. "Hotfix" and "hotfix 2" doesn't say much to any of other devs, even less when it's open source code.

Ok.

2022-10-04 08:07 UTC, fabio-silva approved these changes

2022-10-04 09:25 UTC, merged