SAAS-1158: mui-profile-page
percona-platform/saas-ui pull request #308
Opened 2022-10-24 07:27 UTC by MaksimMalakhovSimbirsoft

![screen2](https://user-images.githubusercontent.com/107244329/197470793-61c0a9ff-e767-4040-ba3d-3b941759e618.png)
![profile 1](https://user-images.githubusercontent.com/107244329/197470796-1e23de00-2e8f-4456-8ffe-c5d8f4bd2a81.png)
![screen3](https://user-images.githubusercontent.com/107244329/197470798-7fd93968-951f-4d6a-9a13-089e9a848d31.png)
![screen4](https://user-images.githubusercontent.com/107244329/197470803-73468f2f-b049-4251-aef5-2eec4b3ac746.png)

2022-10-25 11:56 UTC, fabio-silva requested changes

2022-10-25 11:56 UTC, fabio-silva commented on src/pages/Profile/Profile.styles.ts
> +      margin: ${spacing.sm} 0 ${spacing.xl} 0;
We're not supposed to use Grafana's styling anymore, check Tomas' PR for an idea on spacing from MUI.

2022-10-25 11:56 UTC, fabio-silva commented on src/pages/Profile/Profile.tsx
> +const LoaderButton = styled(Button)(() => ({
I believe we should instead use Button's `sx` prop to style it.

2022-10-25 11:56 UTC, fabio-silva commented on src/pages/Profile/Profile.tsx
> +    if (value.length > MAX_NAME_LENGTH) {
Let's not do this. We're not supposed to remove react-final-form and do our own validation. RFF and Yup already do that for us.

2022-10-26 10:26 UTC, nicolalamacchia requested changes

2022-10-26 10:26 UTC, nicolalamacchia commented on src/pages/Profile/Profile.tsx
> +                // @ts-ignore
don't use @ts-ignore

2022-10-31 07:39 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Profile/Profile.tsx
> +const LoaderButton = styled(Button)(() => ({
@fabio-silva Done

2022-10-31 07:40 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Profile/Profile.styles.ts
> +      margin: ${spacing.sm} 0 ${spacing.xl} 0;
@fabio-silva Done, I ve added m,p props from MUI, and used it not in pixels

2022-10-31 07:41 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Profile/Profile.tsx
> +    if (value.length > MAX_NAME_LENGTH) {
@fabio-silva Done, I ve returned React final form and used input props for handling textfields

2022-10-31 07:42 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Profile/Profile.tsx
> +    event.preventDefault();
@nicolalamacchia Done, I ve removed it and used props from react final form

2022-10-31 07:44 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Profile/Profile.tsx
> +                // @ts-ignore
@nicolalamacchia How can I avoid ts ignoring ? I ve heard about making wrapper around component, I wrapped my textfield from MUI by field from react final form , but it is not working( we should discuss how can I solve it

2022-10-31 10:52 UTC, TomasBlazek3PG requested changes

2022-10-31 11:13 UTC, nicolalamacchia commented on src/pages/Profile/Profile.tsx
> +                // @ts-ignore
pushed a commit that remove them, PTAL

2022-10-31 15:45 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Profile/Profile.styles.ts
> +    flex: '1',
@TomasBlazek3PG Done, changed to number

2022-10-31 15:56 UTC, MaksimMalakhovSimbirsoft commented on package.json
> +    "@emotion/styled": "^11.10.4",
@TomasBlazek3PG Done

2022-11-01 05:30 UTC, closed without merging