SAAS-1162: MUI PrivateLayout redesign
percona-platform/saas-ui pull request #309
Opened 2022-10-25 06:53 UTC by TomasBlazek3PG

![image](https://user-images.githubusercontent.com/100355118/197701523-b76c25b8-50e3-434c-a785-19473cdc2c02.png)

2022-10-25 16:45 UTC, nicolalamacchia requested changes
There are a lot of inline numbers, text, styles that should go in the respective files

2022-10-25 16:45 UTC, nicolalamacchia commented on src/components/SideMenu/SideMenu.tsx
> +      }}
can we please keep using emotion for style? I don't like inline style, even if CSS-in-JS

2022-10-25 16:45 UTC, nicolalamacchia commented on src/components/SideMenu/SideMenu.tsx
> +          <img src={logo} width={24} alt="dj" />
Use constants. What's "dj"?

2022-10-25 16:45 UTC, nicolalamacchia commented on src/components/SideMenu/SideMenu.tsx
> +            Percona Portal
Use messages file

2022-10-25 16:45 UTC, nicolalamacchia commented on src/styles/global.css
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap');
why are we importing Roboto from googleapis?

2022-10-25 16:45 UTC, nicolalamacchia commented on src/components/Header/Header.tsx
> +      {(theme) => (
Can we move this outside of the component? This can become boilerplate and we have enough already

2022-10-26 06:47 UTC, TomasBlazek3PG commented on src/components/Header/Header.tsx
> +export const Header: FC = () => {
How about AppHeader? Its self explenatory and cannot be mistaken for something else. TopBar and TopMenu could be seen as a part of other components.

2022-10-26 06:48 UTC, TomasBlazek3PG commented on src/components/Header/Header.tsx
> +          </IconButton> */}
Those are gonna be used in the future so it will make someones life easier. But I will remove them.

2022-10-26 06:49 UTC, TomasBlazek3PG commented on src/components/Layouts/PrivateLayout/PrivateLayout.tsx
> +        <Box display="flex" flexGrow={1} maxWidth={1400} padding={5} mt={`${HEADER_HEIGHT}px`}>
Had to choose some number since we dont have anything defined. Will move it to constant.

2022-10-26 06:50 UTC, TomasBlazek3PG commented on src/components/SideMenu/SideMenu.tsx
> +      }}
This is something we should discuss. Since all our styling is done through props anyway it probably makes sense to use this. It's even in documentation.

2022-10-26 06:51 UTC, TomasBlazek3PG commented on src/components/SideMenu/SideMenu.tsx
> +          <img src={logo} width={24} alt="dj" />
Good catch with the alt. However I am not sure if we should use constant here if it is only applicable for the logo and nothing else anywhere in the app.

2022-10-26 06:51 UTC, TomasBlazek3PG commented on src/components/SideMenu/SideMenu.tsx
> +            Percona Portal
Good catch!

2022-10-26 06:56 UTC, TomasBlazek3PG commented on src/styles/global.css
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap');
What do you prefer?

2022-10-27 11:44 UTC, nicolalamacchia requested changes

2022-10-27 11:44 UTC, nicolalamacchia commented on src/components/SideMenu/SideMenu.tsx
> +    </ListItem>
This can be split into two components: an "external" one and a normal one

2022-10-27 11:44 UTC, nicolalamacchia commented on src/components/index.ts
> +export * from './Header';
Shouldn't this be `AppHeader`?

2022-10-27 11:44 UTC, nicolalamacchia commented on src/pages/Activation/Activation.tsx
> +      history.push(Routes.root);
why this change here?

2022-10-27 11:44 UTC, nicolalamacchia commented on src/styles/global.css
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap');
As we discussed, to use imports from NPM libraries.

2022-10-27 11:44 UTC, nicolalamacchia commented on package.json
> +    "@emotion/react": "^11.10.4",
I think this is not needed in this PR, let's add this in the next one when we're actually using it

2022-10-27 12:53 UTC, TomasBlazek3PG commented on src/pages/Activation/Activation.tsx
> +      history.push(Routes.root);
Is not needed. dashboard is on root. And /dashboard doesnt exist.

2022-10-27 16:12 UTC, nicolalamacchia requested changes

2022-10-27 16:12 UTC, nicolalamacchia commented on src/components/SideMenu/SideMenu.tsx
> +      </ListItemButton>
It's a good practice to have one component per file, no matter how small they are, so let's move these outside

2022-10-27 16:12 UTC, nicolalamacchia commented on src/pages/Activation/Activation.tsx
> +      history.push(Routes.root);
yes, but let's keep the scope clean, if this is not part of this scope let's not change it.

2022-10-27 19:01 UTC, TomasBlazek3PG commented on src/pages/Activation/Activation.tsx
> +      history.push(Routes.root);
I am sorry but I insist on this one. This would never get fixed and you could see it as part of this story since I am having a link to dashboard on the private layout.

2022-10-28 08:36 UTC, MaksimMalakhovSimbirsoft commented on src/components/Layouts/PrivateLayout/PrivateLayout.tsx
> +      <Stack display="flex" flexGrow={1} position="relative">
Are we going to take props like display="flex",flexGrow={1},margin={1} etc. to styles ?

2022-10-28 09:55 UTC, nicolalamacchia commented on src/pages/Activation/Activation.tsx
> +      history.push(Routes.root);
I don't see the point in insisting on this, since this is strictly a preference of yours, it's not affecting the business logic and was not needed in the first place. As I pointed out in other parts of this PR, let's keep the changes to the minimum possible of what's needed and worth change.

2022-10-28 10:00 UTC, nicolalamacchia commented on src/components/Layouts/PrivateLayout/PrivateLayout.tsx
> +      <Stack display="flex" flexGrow={1} position="relative">
starting from the next PRs

2022-10-31 08:23 UTC, TomasBlazek3PG commented on package.json
> +    "@emotion/styled": "^11.10.4",
done

2022-10-31 08:23 UTC, TomasBlazek3PG commented on src/components/Header/Header.tsx
> +      {(theme) => (
done

2022-10-31 08:23 UTC, TomasBlazek3PG commented on src/components/SideMenu/SideMenu.tsx
> +    </ListItem>
done

2022-10-31 08:23 UTC, TomasBlazek3PG commented on src/components/index.ts
> +export * from './Header';
done

2022-10-31 08:23 UTC, TomasBlazek3PG commented on src/pages/Activation/Activation.tsx
> +      history.push(Routes.root);
done

2022-10-31 08:23 UTC, TomasBlazek3PG commented on package.json
> +    "@emotion/react": "^11.10.4",
done

2022-10-31 08:24 UTC, TomasBlazek3PG commented on src/components/SideMenu/SideMenu.tsx
> +      </ListItemButton>
done

2022-10-31 13:33 UTC, nicolalamacchia approved these changes

2022-11-02 13:54 UTC, merged