SAAS-340 - imporved e2e tests architecture
percona-platform/saas-ui pull request #31
Opened 2020-09-28 12:31 UTC by yurkovychv

added common methods, integrated types, removed server mocking, tuned tests

2020-09-30 07:19 UTC, yurkovychv commented on packages/platform-ui/cypress/pages/auth/flows/validation.flow.ts
> +export const runVerifyFieldsValidationFlow = (page: Pages) => {
@atymchuk I think I do not understand what you mean here. Should I rename it to `runFieldsValidationFlow`?

2020-09-30 08:02 UTC, yurkovychv commented on packages/platform-ui/cypress/pages/auth/flows/validation.flow.ts
> +export const runVerifyFieldsValidationFlow = (page: Pages) => {
If you are talking about logs information if the flow fails - the report will contain the exception and this function with a specified `Page`

2020-09-30 08:02 UTC, yurkovychv commented on packages/platform-ui/cypress/pages/auth/flows/validation.flow.ts
> +export const runVerifyFieldsValidationFlow = (page: Pages) => {
so we will have enough information to search for a root cause

2020-09-30 08:16 UTC, yurkovychv commented on packages/platform-ui/cypress/pages/auth/flows/checkElements.flow.ts
> +export const runVerifyPageElementsFlow = (page: Pages) => {
renamed it to `runPageElementsFlow`

2020-09-30 08:20 UTC, yurkovychv commented on packages/platform-ui/cypress/pages/common/interfaces/IFields.d.ts
> +export type TInputField = {
renamed to Fields.d.ts in order to use `Chainable<JQuery<HTMLElement>>` types inside

2020-10-01 08:42 UTC, atymchuk requested changes

2020-10-01 08:42 UTC, atymchuk commented on packages/platform-ui/cypress/index.d.ts
> +    interface Chainable<Subject> {
Here the indentation went crazy - 4 spaces vs the usual 2 :)

2020-10-01 08:42 UTC, atymchuk commented on packages/platform-ui/cypress/pages/auth/utils/getNewUser.ts
> +import faker from 'faker'
```suggestion
import faker from 'faker';
```

2020-10-01 08:42 UTC, atymchuk commented on packages/platform-ui/cypress/pages/auth/utils/getNewUser.ts
> +import faker from 'faker'
Your IDE seems to be inconsistent when applying double quotes vs single quotes in imports. Looks like we badly need to wire up .eslint here. Or is it wired?

2020-10-01 08:42 UTC, atymchuk commented on packages/platform-ui/cypress/pages/auth/utils/getNewUser.ts
> +      email: email,
```suggestion
      email,
```
Prefer the short syntax

2020-10-01 08:43 UTC, atymchuk commented on packages/platform-ui/cypress/pages/auth/flows/validation.flow.ts
> +export const runVerifyFieldsValidationFlow = (page: Pages) => {
> @atymchuk I think I do not understand what you mean here. Should I rename it to `runFieldsValidationFlow`?

Yeah, I was not clear there :)

2020-10-01 09:21 UTC, nicolalamacchia requested changes

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/integration/auth/login.spec.ts
> +
Please, don't leave empty lines at the top of functions

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/integration/auth/signup.spec.ts
> +
Empty line

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/pages/auth/flows/checkElements.flow.ts
> +  passwordFieldLabel, signupForm, signUpLink,
Make each of these on a separate line

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/pages/common/interfaces/Auth.ts
> +}
Add semicolons

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/pages/common/interfaces/Fields.d.ts
> +}
Add semicolons

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/pages/common/view/behavior/common.ts
> +  field().clear().type(value)
```suggestion
  field().clear().type(value);
```

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/pages/common/view/behavior/common.ts
> +  field().type(value)
```suggestion
  field().type(value);
```

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/support/commands.js
> +        cy.wrap($element).should('be.visible')
```suggestion
        cy.wrap($element).should('be.visible');
```

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/support/commands.js
> +        cy.wrap($element).should('be.disabled')
```suggestion
        cy.wrap($element).should('be.disabled');
```

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/support/commands.js
> +        cy.wrap($element).should('be.enabled')
```suggestion
        cy.wrap($element).should('be.enabled');
```

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/webpack.config.js
> +            target: 'ES2019'
```suggestion
            target: 'ES2019',
```

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/webpack.config.js
> +        exclude: [/node_modules/]
```suggestion
        exclude: [/node_modules/],
```

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/webpack.config.js
> +    extensions: ['.ts', '.tsx', '.js', '.jsx', '.json']
```suggestion
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.json'],
```

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/webpack.config.js
> +    path: path.resolve(__dirname, 'dist')
```suggestion
    path: path.resolve(__dirname, 'dist'),
```

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/tsconfig.json
> +    "baseUrl": "../node_modules",
This looks a bit strange to me: why do you need to specify explicitly this?

I think that setting it to `./` would allow you to use absolute imports on all your files.

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/integration/auth/login.spec.ts
> +import {pageDetailsMap, Pages, VALID_USER} from "../../pages/common/constants";
Try to use absolute imports please (also in all the other files - see comment on `tsconfig.json`)

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/pages/auth/flows/checkElements.flow.ts
> +import {Pages} from "../../common/constants";
```suggestion
import { Pages } from "../../common/constants";
```

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/pages/auth/flows/checkElements.flow.ts
> +import {PRIVACY_POLICY_URL, TERMS_MESSAGE, TERMS_OF_SERVICE_URL} from "../constants/constants";
```suggestion
import { PRIVACY_POLICY_URL, TERMS_MESSAGE, TERMS_OF_SERVICE_URL } from "../constants/constants";
```

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/pages/auth/flows/validation.flow.ts
> +import {Pages, VALID_USER} from "../../common/constants";
Please add spaces in braces (also in other files)

2020-10-01 09:21 UTC, nicolalamacchia commented on packages/platform-ui/cypress/pages/auth/utils/getNewUser.ts
> +import {ValidUser} from "../../common/interfaces/Auth";
```suggestion
import { ValidUser } from "../../common/interfaces/Auth";
```

2020-10-01 10:52 UTC, yurkovychv commented on packages/platform-ui/cypress/index.d.ts
> +    interface Chainable<Subject> {
I think I managed to apply the project prettier config , sorry for that )

2020-10-01 10:52 UTC, yurkovychv commented on packages/platform-ui/cypress/pages/auth/utils/getNewUser.ts
> +import faker from 'faker'
should be better now

2020-10-01 10:52 UTC, yurkovychv commented on packages/platform-ui/cypress/pages/auth/utils/getNewUser.ts
> +      email: email,
done , thanks

2020-10-01 10:53 UTC, yurkovychv commented on packages/platform-ui/cypress/index.d.ts
> +    // eslint-disable-next-line
removed that one, it was unneded

2020-10-01 10:53 UTC, yurkovychv commented on packages/platform-ui/cypress/pages/auth/flows/checkElements.flow.ts
> +  passwordFieldLabel, signupForm, signUpLink,
done

2020-10-01 10:54 UTC, yurkovychv commented on packages/platform-ui/cypress/tsconfig.json
> +    "baseUrl": "../node_modules",
done, thanks for advise

2020-10-01 10:54 UTC, yurkovychv commented on packages/platform-ui/cypress/integration/auth/login.spec.ts
> +import {pageDetailsMap, Pages, VALID_USER} from "../../pages/common/constants";
done

2020-10-01 10:55 UTC, yurkovychv commented on packages/platform-ui/cypress/integration/auth/login.spec.ts
> +
removed, sorry

2020-10-01 11:53 UTC, nicolalamacchia requested changes

2020-10-01 11:53 UTC, nicolalamacchia commented on packages/platform-ui/cypress/index.d.ts
> +  }
missing semicolons, please remove unnecessary empty lines

2020-10-01 11:59 UTC, nicolalamacchia approved these changes

2020-10-01 13:51 UTC, atymchuk approved these changes

2020-10-01 14:00 UTC, merged