SAAS-1121: Show Registered Email
percona-platform/saas-ui pull request #315
Opened 2022-10-31 14:18 UTC by TomasBlazek3PG

2022-10-31 15:05 UTC, nicolalamacchia requested changes
Check warnings from the linter

2022-11-01 04:56 UTC, MaksimMalakhovSimbirsoft approved these changes

2022-11-01 09:06 UTC, TomasBlazek3PG commented on src/components/OktaSignInWidget/OktaSignInWidget.types.ts
> +  __pending__: boolean;
done

2022-11-02 12:27 UTC, nicolalamacchia approved these changes

2022-11-03 12:17 UTC, merged