SAAS-1158: muiIntegrationProfile
percona-platform/saas-ui pull request #317
Opened 2022-11-01 05:28 UTC by MaksimMalakhovSimbirsoft

![1](https://user-images.githubusercontent.com/107244329/199165169-3aa123c9-5c77-4305-b4dc-51529e917197.png)
![2](https://user-images.githubusercontent.com/107244329/199165181-8340f06b-1972-46f1-a1f5-0
![4](https://user-images.githubusercontent.com/107244329/199165210-61a0a8fe-061c-473b-a9c4-1ca7dacb05ae.png)
c2abdd905a8.png)

2022-11-03 14:34 UTC, nicolalamacchia approved these changes

2022-11-03 15:26 UTC, fabio-silva requested changes

2022-11-03 15:26 UTC, fabio-silva commented on src/components/TextInputField/TextInputField.test.tsx
> +export const dataTestId = (selector: string) => `[data-testid="${selector}"]`;
Why do we need these two when we have `queryByTestId` and such?

2022-11-03 15:26 UTC, fabio-silva commented on src/components/TextInputField/TextInputField.tsx
> +            InputLabelProps={
Probably a better way is to create our own `.d.ts` file where we extend the base typings to allow `data-testid` as part of these props. Check our Grafana fork, `public/app/percona/integrated-alerting/types.ts` or `packages/grafana-ui/src/types/react-table-config.d.ts`

2022-11-03 15:26 UTC, fabio-silva commented on src/pages/Profile/Profile.tsx
> +  const validation = useCallback(
This seems counter-productive. Do we need to write this piece of code for every single form in our app?

2022-11-03 15:26 UTC, fabio-silva commented on src/pages/Profile/Profile.tsx
> +          validate={validation()}
This is something we talked about in an earlier PR. The function shouldn't be invoked and your function should have one less arrow. It's `useCallback(async () => {...})`, not `useCallback(() => async() => {})`

2022-11-03 15:26 UTC, fabio-silva commented on src/pages/Profile/Profile.tsx
> +                margin="normal"
question: isn't "normal" the default?

2022-11-03 17:35 UTC, MaksimMalakhovSimbirsoft commented on src/components/TextInputField/TextInputField.test.tsx
> +export const dataTestId = (selector: string) => `[data-testid="${selector}"]`;
@fabio-silva just forgot to remove them

2022-11-03 17:39 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Profile/Profile.tsx
> +    lastName: yup.string().label(Messages.lastNameLabel).required().max(50),
@fabio-silva Done

2022-11-03 17:44 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Profile/Profile.tsx
> +                margin="normal"
@fabio-silva margin by default is 'none'.

2022-11-04 10:52 UTC, MaksimMalakhovSimbirsoft commented on src/pages/Profile/Profile.tsx
> +  const validation = useCallback(
@Done, validation function is added to core/utilz

2022-11-04 12:09 UTC, MaksimMalakhovSimbirsoft commented on src/components/TextInputField/TextInputField.tsx
> +            InputLabelProps={
@fabio-silva we added pages/types/material-ui.ts , added labelProps. But was a problem with helperTextProps and we decided to leave it like it is now as CustomProps

2022-11-04 12:14 UTC, fabio-silva commented
@MaksimMalakhovSimbirsoft let's just fix the tests and we're good to do

2022-11-04 13:12 UTC, fabio-silva approved these changes

2022-11-07 17:14 UTC, merged