SAAS-363 add redux saga
percona-platform/saas-ui pull request #32
Opened 2020-10-01 22:14 UTC by nicolalamacchia

2020-10-02 13:46 UTC, atymchuk requested changes

2020-10-02 13:46 UTC, atymchuk commented on packages/platform-ui/src/index.tsx
> +          <Router>
The router is not needed then. Pls see https://github.com/supasate/connected-react-router#step-3

2020-10-02 13:46 UTC, atymchuk commented on packages/platform-ui/src/store/auth/auth.sagas.ts
> +  yield call([history, history.replace], Routes.root);
This is not cosher, pls refer to https://github.com/supasate/connected-react-router/blob/master/FAQ.md#in-redux-saga

2020-10-02 14:27 UTC, nicolalamacchia commented on packages/platform-ui/src/index.tsx
> +          <Router>
I made it work without it, but had to downgrade `history` @ 4.10.1 (see https://github.com/ReactTraining/history/issues/804 and https://github.com/supasate/connected-react-router/issues/312)

2020-10-02 15:48 UTC, nicolalamacchia commented on packages/platform-ui/src/store/auth/auth.sagas.ts
> +  yield call([history, history.replace], Routes.root);
Done

2020-10-02 18:35 UTC, nicolalamacchia commented
e2e tests must be fixed, @yurkovychv let's have a discussion about that if needed

2020-10-05 15:26 UTC, yurkovychv approved these changes

2020-10-12 12:09 UTC, atymchuk requested changes

2020-10-12 12:09 UTC, atymchuk commented on packages/platform-ui/package.json
> +    "react-router": "^5.2.0",
Do we need it? It's an indirect dependency of _react-router-dom_ AFAIK, so we should probably leave it out.

2020-10-12 12:11 UTC, yurkovychv submitted a review, later dismissed

2020-10-12 12:46 UTC, nicolalamacchia commented on packages/platform-ui/package.json
> +    "react-router": "^5.2.0",
Right, it's a mistake, removed it

2020-10-12 13:35 UTC, atymchuk approved these changes

2020-10-12 14:45 UTC, merged