SAAS-1154 migrate ManageOrganization to MUI
percona-platform/saas-ui pull request #329
Opened 2022-11-11 15:44 UTC by nicolalamacchia

2022-11-25 08:25 UTC, TomasBlazek3PG requested changes
Oh and I found one visual problem:
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/100355118/203935000-7c9857f3-adb2-4d86-b955-3dbb70da21af.png">

2022-11-25 08:25 UTC, TomasBlazek3PG commented on src/pages/ManageOrganization/ManageOrganization.styles.ts
> +    h5 {
Please use a className

2022-11-25 08:25 UTC, TomasBlazek3PG commented on src/pages/ManageOrganization/ManageOrganization.styles.ts
> +      svg {
the same

2022-11-25 08:25 UTC, TomasBlazek3PG commented on src/pages/ManageOrganization/OrganizationCreate/OrganizationCreate.styles.ts
> +    svg {
Again please use classNames

2022-11-25 08:25 UTC, TomasBlazek3PG commented on src/pages/ManageOrganization/OrganizationEdit/OrganizationEdit.styles.ts
> +    svg {
classNames

2022-11-25 08:25 UTC, TomasBlazek3PG commented on src/pages/ManageOrganization/OrganizationView/OrganizationView.styles.ts
> +    & > svg {
classNames

2022-11-29 10:24 UTC, nicolalamacchia commented on src/pages/ManageOrganization/ManageOrganization.styles.ts
> +      svg {
this is pointing to the internal svg, cannot be targeted by a class

2022-11-29 10:24 UTC, nicolalamacchia commented on src/pages/ManageOrganization/OrganizationEdit/OrganizationEdit.styles.ts
> +    svg {
see above

2022-11-29 10:24 UTC, nicolalamacchia commented on src/pages/ManageOrganization/OrganizationCreate/OrganizationCreate.styles.ts
> +    svg {
see above

2022-11-29 10:24 UTC, nicolalamacchia commented on src/pages/ManageOrganization/OrganizationView/OrganizationView.styles.ts
> +    & > svg {
see above

2022-11-29 10:24 UTC, nicolalamacchia commented on src/pages/ManageOrganization/InviteMember/InviteMember.tsx
> +          .test('invalidUser', 'an error was found', (value) => {
done

2022-11-29 10:24 UTC, nicolalamacchia commented on src/pages/ManageOrganization/InviteMember/InviteMember.tsx
> +                      Cancel
done

2022-11-29 10:31 UTC, TomasBlazek3PG approved these changes

2022-11-29 10:58 UTC, merged