SAAS-369 pass html attributes to inputs
percona-platform/saas-ui pull request #33
Opened 2020-10-05 13:58 UTC by atymchuk

2020-10-21 15:53 UTC, tiagomotasantos requested changes
Well done with the utility test functions (FormWrapper and dataQa) introduced in this PR as well as the other great cleanups introduced 🎉👏

2020-10-21 15:53 UTC, tiagomotasantos commented on packages/platform-core/src/components/Checkbox/CheckboxField.tsx
> +              {...inputProps}
Should we place {...inputProps} below {...input}? Because the way it currently is I think we won't be able to override the props react final form passes by default. For example it passes onChange by default in the input so it will always override our own even if we pass it as part of inputProps.

2020-10-21 15:53 UTC, tiagomotasantos commented on .gitignore
> +.vscode
These two lines are duplicated above.

2020-10-21 20:12 UTC, atymchuk commented on packages/platform-core/src/components/Checkbox/CheckboxField.tsx
> +              {...inputProps}
I was struggling myself with it and came to a conclusion that this is not the way react-final-form is designed. Normally, if you need to hook to every change event on a particular field, you would grab the values from the render props and do what you need to do with any of the form values.

One major observation I have to make here is: we are paying a certain price of wrapping components in `Field`. As always, there are benefits and downsides. The great benefit is the ease of use - it is a pleasure to work with it compared to adapters we have in PMM. The downside is: by hiding the boilerplate it offers much less, it's opinionated. But that was exactly the purpose.

I would say, it is not universal on purpose and may only cover 90% of our needs. 

Please feel free to suggest a better design (or refactor/upgrade maybe), I'll be happy to review and I do acknowledge this one is not ideal.

2020-10-21 20:16 UTC, atymchuk commented on .gitignore
> +.vscode
Fixed

2020-10-22 10:45 UTC, tiagomotasantos commented on packages/platform-core/src/components/Checkbox/CheckboxField.tsx
> +              {...inputProps}
Ok, I understand that using onChange for example is not the final form way of doing it, I just don't understand what's the downside of changing the order of {...input} and {...inputProps}. Then we give the flexibility to the user of our library to do whatever he wants. Unless you are saying that we specifically don't want to give that flexibility, then I understand :D

2020-10-22 10:48 UTC, atymchuk commented on packages/platform-core/src/components/Checkbox/CheckboxField.tsx
> +              {...inputProps}
That was exactly it: we don't want the user to override the native `onChange`, since it breaks the component. At least, this is what I tried and failed.

2020-10-22 15:01 UTC, atymchuk commented on packages/platform-core/src/shared/logger/logger.ts
> +    console.group(level, truncate(25)(attrs[0]));
> it's not clear to me, why just the first attribute? does it have a special meaning?

Yes, it's sort of a `headline` to enable the user to quickly find the one he is looking for without forcing them to read the full log.

> what's the benefit of having a console group here? it'd be almost the same also when passing several attributes to the console function

The `console.group` nicely indents the text, so it makes the console output easier to navigate. 

> I don't really see the benefit, it just looks more verbose to me

I'll paste an example to visualize the benefit. There used to be a blue icon for `console.info`, and I no longer see it :(
I also updated the code, so it should make more sense now.

<img width="1784" alt="Screenshot 2020-10-22 at 17 55 46" src="https://user-images.githubusercontent.com/81549/96890431-4e833580-1490-11eb-9b1e-880b9959a9aa.png">

2020-10-22 15:02 UTC, atymchuk commented on packages/platform-core/src/components/Checkbox/CheckboxField.tsx
> +              {...inputProps}
We will try to weight the pros and cons in a live-coding session tomorrow before committing.

2020-10-22 15:48 UTC, nicolalamacchia commented on packages/platform-core/src/shared/logger/logger.ts
> +      loggerFunc(para);
why not `param`? :D

2020-10-22 15:49 UTC, atymchuk commented on packages/platform-core/src/shared/logger/logger.ts
> +      loggerFunc(para);
it's a typo!

2020-10-22 15:49 UTC, nicolalamacchia commented on packages/platform-core/src/shared/logger/logger.ts
> +    console.group(level, truncate(25)(attrs[0]));
Ok, now it makes more sense to have it like this :) this means one param per line though, we should document this somehow I think

2020-10-23 13:16 UTC, atymchuk commented on packages/platform-core/src/components/Checkbox/CheckboxField.tsx
> +              {...inputProps}
@nicolalamacchia The experiment showed that we can reverse the order so that {...inputProps} will win over {...input}. So, it's safe now to hook on the input's `change, blur, focus` events.

2020-10-23 13:27 UTC, atymchuk commented on packages/platform-core/src/components/Checkbox/CheckboxField.tsx
> +    <Field<boolean> {...fieldConfig} type="checkbox" name={name} validate={validate}>
@nicolalamacchia pls note, <Field> has a generic :)

2020-10-23 13:28 UTC, atymchuk commented on packages/platform-core/src/shared/logger/logger.ts
> +    console.group(level, truncate(25)(attrs[0]));
Exactly, one param per line is a feature lots of dev are looking for in a logger :)

2020-10-23 13:40 UTC, tiagomotasantos approved these changes

2020-10-23 13:49 UTC, nicolalamacchia approved these changes

2020-10-23 13:50 UTC, merged