SAAS-1192: Activity Log
percona-platform/saas-ui pull request #349
Opened 2022-12-14 08:54 UTC by TomasBlazek3PG

![image](https://user-images.githubusercontent.com/100355118/207550546-9ca78266-60dd-4ac9-b773-3f8b03d66b35.png)
![image](https://user-images.githubusercontent.com/100355118/207550581-63e44cca-cb41-499c-a19d-a6c559ac0a1b.png)

2022-12-14 09:42 UTC, nicolalamacchia approved these changes

2022-12-21 09:44 UTC, nicolalamacchia requested changes

2022-12-21 09:44 UTC, nicolalamacchia commented on src/core/api/events.service.ts
> +import { EditProfileError } from '../../components/MarketingBanner/MarketingBanner.types';
please use absolute path, `import { EditProfileError } from 'components'` should be enough

2022-12-21 09:44 UTC, nicolalamacchia commented on src/pages/ManageOrganization/ActivityLog/ActivityLog.tsx
> +  const handlePageSizeChange = (newPageSize: number) => setPageSize(newPageSize);
shouldn't this be handled automatically by DataGrid?

2022-12-21 09:44 UTC, nicolalamacchia commented on src/pages/ManageOrganization/ActivityLog/ActivityLog.tsx
> +  const handleSortModelChange = (model: GridSortModel) => setSortModel(model);
why is this needed?

2022-12-21 09:44 UTC, nicolalamacchia commented on src/pages/ManageOrganization/ActivityLog/ActivityLog.tsx
> +  };
`render...` function are a code smell, you should create separate components for those

2022-12-21 09:44 UTC, nicolalamacchia commented on src/pages/ManageOrganization/ActivityLog/ActivityLog.tsx
> +  };
what do these do?

2022-12-21 09:47 UTC, TomasBlazek3PG commented on src/pages/ManageOrganization/ActivityLog/ActivityLog.tsx
> +  };
This creates human readable details column text like "User xxx updated xxxx,xxxx,xxxx instance"

2022-12-21 09:50 UTC, TomasBlazek3PG commented on src/pages/ManageOrganization/ActivityLog/ActivityLog.tsx
> +  const handleSortModelChange = (model: GridSortModel) => setSortModel(model);
This is setting the sort model (which way and which column should be sorted). It is then used in the request to BE.

2022-12-21 09:51 UTC, TomasBlazek3PG commented on src/pages/ManageOrganization/ActivityLog/ActivityLog.tsx
> +  const handlePageSizeChange = (newPageSize: number) => setPageSize(newPageSize);
We need to know what is the size so we can add this info to the request to BE

2022-12-21 15:09 UTC, nicolalamacchia commented on src/pages/ManageOrganization/ActivityLog/ActivityLog.tsx
> +  const handlePageSizeChange = (newPageSize: number) => setPageSize(newPageSize);
right, I forgot it's paginated on the BE

2022-12-21 15:13 UTC, nicolalamacchia requested changes
Looks good, but tests are missing

2022-12-21 15:20 UTC, nicolalamacchia submitted a review, later dismissed

2022-12-27 11:45 UTC, nicolalamacchia approved these changes

2022-12-27 11:46 UTC, merged