SAAS-347 numeric input component
percona-platform/saas-ui pull request #36
Opened 2020-10-09 17:44 UTC by nicolalamacchia

2020-10-12 23:50 UTC, atymchuk requested changes

2020-10-12 23:50 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInputField.tsx
> +                    disabled={disabled}
Passing `disabled` is redundant here - it's not rendered anyway.

2020-10-12 23:50 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInputField.tsx
> +                    disabled={disabled}
`disabled` is redundant here as well.

2020-10-12 23:50 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +    &:disabled {
`disabled` may not be needed based on the comment further down.

2020-10-12 23:50 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +    color: ${theme.colors.formInputText};
```suggestion
    color: ${colors.formInputText};
```

2020-10-12 23:50 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      color: ${theme.colors.formInputDisabledText};
```suggestion
      color: ${colors.formInputDisabledText};
```

2020-10-12 23:50 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      border-width: 0 0.3em 0.3em 0.3em;
```suggestion
      border-width: 0 0.3em 0.3em;
```

2020-10-12 23:50 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      border-width: 0 0.3em 0.3em 0.3em;
Just reads the same as the line below.

2020-10-12 23:50 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      border-width: 0.3em 0.3em 0 0.3em;
```suggestion
      border-width: 0.3em 0.3em 0;
```

2020-10-12 23:50 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      bottom: 2px;
Is it legit to have both `bottom` & `top`? Which one will win?

2020-10-12 23:50 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      &:focus {
Does it make sense to take it to `/core` in case if the `:focus` styles are the same for each input?

2020-10-12 23:50 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInputField.tsx
> +import { getStyles } from './NumberInput.styles';
```suggestion
import { Field, FieldMetaState, FieldInputProps, UseFieldConfig } from 'react-final-form';
import { getStyles } from './NumberInput.styles';
```
The order of imports should be libraries first.

2020-10-12 23:50 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInputField.tsx
> +  label?: string;
Interface & object properties should be sorted a12y.

2020-10-12 23:50 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInputField.tsx
> +    inputRef.current!.dispatchEvent(event);
Isn't a property guard `?` a better choice?
```suggestion
    inputRef.current?.dispatchEvent(event);
```

2020-10-12 23:50 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInputField.tsx
> +    inputRef.current!.dispatchEvent(event);
In case of applying this change, let's make it uniform further down as well.

2020-10-12 23:50 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInput.test.tsx
> +import React, { FC } from 'react';
Bravissimo for the extensive test coverage!

2020-10-13 07:44 UTC, tiagomotasantos requested changes

2020-10-13 07:44 UTC, tiagomotasantos commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +    right: 2px;
```suggestion
    right: ${spacing.xxs};
```

2020-10-13 07:44 UTC, tiagomotasantos commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      bottom: 2px;
```suggestion
      bottom: ${spacing.xxs};
```

2020-10-13 07:44 UTC, tiagomotasantos commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      top: 2px;
```suggestion
      top: ${spacing.xxs};
```

2020-10-13 07:44 UTC, tiagomotasantos commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      top: 2px;
```suggestion
      top: ${spacing.xxs};
```

2020-10-13 07:44 UTC, tiagomotasantos commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      border-radius: 2px;
```suggestion
      border-radius: ${border.radius.sm};
```

2020-10-13 07:50 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInputField.tsx
> +                data-qa={`${name}-text-input`}
I used it consistently with other inputs: the password input and the textarea have the same. I can change it to all the other inputs.

2020-10-13 07:53 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInputField.tsx
> +                    disabled={disabled}
Good catch, removed

2020-10-13 07:53 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInputField.tsx
> +                    disabled={disabled}
Removed

2020-10-13 07:55 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +    &:disabled {
Removed

2020-10-13 07:57 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      color: ${theme.colors.formInputDisabledText};
This code has been removed

2020-10-13 08:01 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      &:focus {
Yes, it makes sense. Let's decide how to do it first

2020-10-13 08:01 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInputField.tsx
> +import { getStyles } from './NumberInput.styles';
Done

2020-10-13 08:03 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInputField.tsx
> +  label?: string;
Done

2020-10-13 08:05 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInputField.tsx
> +                data-qa={`${name}-text-input`}
No, please don't. I meant to give a number input a name of (example) `threshold-number-input` and a text input a name of `nickname-text-input`. Hope, this example will help understand.

2020-10-13 08:06 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      &:focus {
By committing a this-is-what-i-propose code )

2020-10-13 08:07 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +    right: 2px;
Done

2020-10-13 08:07 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      bottom: 2px;
Done

2020-10-13 08:07 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      top: 2px;
Done

2020-10-13 08:07 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      top: 2px;
Done

2020-10-13 08:08 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      border-radius: 2px;
Done

2020-10-13 08:11 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInputField.tsx
> +                data-qa={`${name}-text-input`}
Yes, I think I understood :) I'm saying that at this point also `PasswordInputField` should have a `data-qa` attribute like: `login-password-input`, while now it would be `login-text-input`, same goes for the textarea.

2020-10-13 08:11 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +    color: ${theme.colors.formInputText};
Done

2020-10-13 08:13 UTC, atymchuk commented on packages/platform-core/src/components/NumberInput/NumberInputField.tsx
> +                data-qa={`${name}-text-input`}
Ok, got it. Let's watch the ci tests :)

2020-10-13 08:27 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      bottom: 2px;
It is in this case, since the parent `button` has `position: absolute`, the work together to set vertical starting and ending point for the button.

2020-10-13 08:27 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      &:focus {
That would be a proposal, not a decision :) Let's have a small discussion about that

2020-10-13 09:43 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      &:focus {
This will be done in another ticket

2020-10-13 09:44 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInputField.tsx
> +    inputRef.current!.dispatchEvent(event);
Done for all the three of them

2020-10-13 09:45 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      border-width: 0 0.3em 0.3em 0.3em;
Good catch, done

2020-10-13 09:45 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInput.styles.ts
> +      border-width: 0.3em 0.3em 0 0.3em;
Done

2020-10-13 09:46 UTC, nicolalamacchia commented on packages/platform-core/src/components/NumberInput/NumberInputField.tsx
> +                data-qa={`${name}-text-input`}
Done for this component for now

2020-10-13 11:13 UTC, tiagomotasantos approved these changes

2020-10-13 14:30 UTC, atymchuk submitted a review, later dismissed

2020-10-13 14:50 UTC, atymchuk approved these changes

2020-10-13 14:59 UTC, merged