Saas 1232 update marketing optin message
percona-platform/saas-ui pull request #363
Opened 2023-01-24 05:55 UTC by YashSartanpara1

This PR is to update marketing consent message displayed on Signin and Signup page, This change will update the message to take passive consent hence the marketing checkbox from signup page will be removed.

2023-01-25 08:14 UTC, TomasBlazek3PG approved these changes

2023-02-06 13:54 UTC, nicolalamacchia requested changes

2023-02-06 13:54 UTC, nicolalamacchia commented on src/components/OktaSignInWidget/ToSCheckbox.styles.ts
> +    color: #007dc1 !important;
let's use colors from the theme whenever possible. same for font sizes.

2023-02-06 14:36 UTC, nicolalamacchia approved these changes

2023-02-06 14:38 UTC, YashSartanpara1 commented on src/components/OktaSignInWidget/ToSCheckbox.styles.ts
> +    color: #007dc1 !important;
Sure.

2023-02-06 14:40 UTC, merged