Saas 1303 mobile friendly landing page
percona-platform/saas-ui pull request #395
Opened 2023-02-24 08:06 UTC by YashSartanpara1

2023-02-27 16:11 UTC, doracretu3pillar approved these changes

2023-02-28 10:51 UTC, nicolalamacchia requested changes

2023-02-28 11:49 UTC, YashSartanpara1 commented on src/pages/LandingPage/USPCard/USPCard.styles.ts
> +    @media (max-width: 1200px) {
Sure

2023-03-01 07:50 UTC, doracretu3pillar approved these changes

2023-03-02 09:26 UTC, nicolalamacchia approved these changes

2023-03-06 11:11 UTC, merged