SASS-1101 Added interceptor in api.service.ts
percona-platform/saas-ui pull request #397
Opened 2023-03-03 09:24 UTC by doracretu3pillar

Moved the check for state.email from store.ts to an axios interceptor in api.service.ts

2023-03-06 10:15 UTC, nicolalamacchia requested changes

2023-03-06 12:36 UTC, doracretu3pillar commented on src/components/SecureRoute/SecureRoute.tsx
> +      );
fixed

2023-03-06 14:41 UTC, nicolalamacchia requested changes

2023-03-06 14:41 UTC, nicolalamacchia commented on src/components/MarketingBanner/MarketingBanner.tsx
> +interface IMarketingBanner {
```suggestion
interface MarketingBannerProps {
```

Please don't prepend interfaces with `I`

2023-03-06 14:41 UTC, nicolalamacchia commented on src/components/SecureRoute/SecureRoute.tsx
> +  const [userInfo, setUserInfo] = useState({ sub: '' });
why do we need the `{ sub: '' }` part?

2023-03-06 14:59 UTC, doracretu3pillar commented on src/components/SecureRoute/SecureRoute.tsx
> +  const [userInfo, setUserInfo] = useState({ sub: '' });
You're right, first time the userInfo is actually undefined.
Please check again.

2023-03-06 15:01 UTC, nicolalamacchia approved these changes

2023-03-09 09:51 UTC, nicolalamacchia requested changes

2023-03-09 09:51 UTC, nicolalamacchia commented on src/components/MarketingBanner/MarketingBanner.test.tsx
> +import { testRender } from '../../testUtils';
Use absolute imports

2023-03-09 09:51 UTC, nicolalamacchia commented on src/components/MarketingBanner/MarketingBanner.test.tsx
> +    // arrange
these comments are not needed, it's a good practice not to comment what's already clear from the code

2023-03-09 09:51 UTC, nicolalamacchia commented on src/components/SecureRoute/SecureRoute.test.tsx
> +    testRender(<SecureRoute />, {
Why not using the `TestContainer` we already have, which does something similar?

2023-03-09 15:37 UTC, doracretu3pillar commented on src/components/SecureRoute/SecureRoute.test.tsx
> +    testRender(<SecureRoute />, {
TestContainer returns the JSX to be rendered and export the store that doesn't the `dispatch` mocked.
I've tried with TestContainer, I've mocked the store.dispatch but it doesn't get called so the test doesn't pass (I have an explanation for that).

testUtils.jsx returns the already rendered JSX and the store . Using the store you can access `dispatch` and `getState()`. So a wider range of information can be tested.
Cannot get rid of TestContainer or refactor it without affecting all the tests. 




https://redux.js.org/usage/writing-tests
if you search `renderWithProviders()` , the Wrapper is actually the TestContainer.

2023-03-13 11:06 UTC, nicolalamacchia approved these changes

2023-03-14 14:31 UTC, nicolalamacchia approved these changes

2023-03-14 14:34 UTC, merged