SAAS-362 UI components tests
percona-platform/saas-ui pull request #40
Opened 2020-10-12 15:54 UTC by nicolalamacchia

2020-10-14 17:00 UTC, atymchuk requested changes

2020-10-14 17:00 UTC, atymchuk commented on packages/platform-core/src/components/Checkbox/Checkbox.test.tsx
> +jest.spyOn(console, 'error').mockImplementation(() => {});
There is way to avoid putting this line in every test. 
1/ export console to /shared
2/ put a mock to its __mock__ folder
3/ use it without ^ that line :)

2020-10-14 17:00 UTC, atymchuk commented on packages/platform-core/src/shared/validators/containsNumbers.test.ts
> +    expect(containsNumber('123')).toEqual(undefined);
We need to test edge cases by passing undefined, {}, [], '', etc
The validator may fail, btw. Then we should make it robust :)

2020-10-15 09:20 UTC, nicolalamacchia commented on packages/platform-core/src/shared/validators/email.test.ts
> +  // NOTE (nicolalamacchia): some of these tests were taken from Chromium's source code
None taken, actually I agree with you, done!

2020-10-15 10:03 UTC, nicolalamacchia commented on packages/platform-core/src/components/Checkbox/Checkbox.test.tsx
> +jest.spyOn(console, 'error').mockImplementation(() => {});
we will introduce a better logging system, deprecating the use of `console`

2020-10-15 10:37 UTC, atymchuk commented on packages/platform-core/src/shared/validators/containsNumbers.test.ts
> +    expect(containsNumber('123')).toEqual(undefined);
Ok, let's give it another iteration. Looks acceptable at this stage. :)

2020-10-15 10:38 UTC, nicolalamacchia commented on packages/platform-core/src/shared/validators/containsNumbers.test.ts
> +    expect(containsNumber('123')).toEqual(undefined);
We have to harden our validators first, and subsequently improve test coverage

2020-10-15 11:50 UTC, atymchuk approved these changes

2020-10-15 11:50 UTC, atymchuk commented on packages/platform-ui/src/components/Authenticated/Authenticated.tsx
> +            <b data-qa="user-email">{email}</b>
👍

2020-10-15 12:14 UTC, merged