SAAS-398 add eslint config
percona-platform/saas-ui pull request #41
Opened 2020-10-15 12:43 UTC by nicolalamacchia

2020-10-16 08:34 UTC, tiagomotasantos commented on packages/platform-core/src/components/Checkbox/CheckboxField.tsx
> +  Field, FieldInputProps, FieldMetaState, UseFieldConfig
With `only-multiline` a comma should be required here or am I wrong?

2020-10-16 08:41 UTC, nicolalamacchia commented on packages/platform-core/src/components/Checkbox/CheckboxField.tsx
> +  Field, FieldInputProps, FieldMetaState, UseFieldConfig
only if they end up being one on each line :)

2020-10-16 08:42 UTC, tiagomotasantos commented on packages/platform-core/src/components/Checkbox/CheckboxField.tsx
> +  Field, FieldInputProps, FieldMetaState, UseFieldConfig
Great :)

2020-10-16 10:29 UTC, nicolalamacchia commented on packages/platform-core/src/components/Checkbox/CheckboxField.tsx
> +  Field, FieldInputProps, FieldMetaState, UseFieldConfig
But you made me notice that there's a but, it should be `always-multiline` :D

2020-10-19 00:21 UTC, atymchuk requested changes

2020-10-19 00:21 UTC, atymchuk commented on packages/platform-ui/.eslintrc
> +    "@typescript-eslint/ban-ts-ignore": ["off"],
Consider applying the same rules an in platform-core (in case they are applied there).

2020-10-19 08:28 UTC, nicolalamacchia commented on packages/platform-core/.eslintrc
> +    "jsx-a11y/no-noninteractive-element-interactions": ["off"],
This is the same as PMM, should we switch it on there too?

2020-10-19 08:29 UTC, nicolalamacchia commented on packages/platform-core/.eslintrc
> +    "no-unused-expressions": ["off"]
No, I just copied the rules from PMM :)

2020-10-19 08:32 UTC, atymchuk commented on packages/platform-core/.eslintrc
> +    "no-unused-expressions": ["off"]
In fact, we should. To get more value out of this PR.

2020-10-19 13:44 UTC, atymchuk commented on packages/platform-core/.eslintrc
> +    "jsx-a11y/no-noninteractive-element-interactions": ["off"],
Not in PMM, we don't have to keep it in perfect sync.

2020-10-19 13:48 UTC, atymchuk approved these changes

2020-10-19 13:50 UTC, merged