SAAS-1315 advisors landing page
percona-platform/saas-ui pull request #416
Opened 2023-04-04 07:03 UTC by YashSartanpara1

2023-04-12 08:22 UTC, nicolalamacchia requested changes

2023-04-12 09:45 UTC, YashSartanpara1 commented on src/components/AlertCards/WarningAlert/WarningAlert.styles.ts
> +    margin: 0 ${spacing(1.6)} -${spacing(0.375)} 0;
done

2023-04-12 09:45 UTC, YashSartanpara1 commented on src/components/AlertCards/WarningAlert/WarningAlert.styles.ts
> +    color: #42361d !important;
done

2023-04-18 08:32 UTC, doracretu3pillar approved these changes

2023-04-18 08:39 UTC, YashSartanpara1 commented on src/pages/Advisors/JoinOrganization/JoinOrganization.styles.ts
> +    color: #42361d !important;
Done

2023-04-18 11:16 UTC, merged