Saas 1302: Advanced Advisors
percona-platform/saas-ui pull request #417
Opened 2023-04-11 17:13 UTC by doracretu3pillar

2023-04-14 05:23 UTC, YashSartanpara1 requested changes

2023-04-14 05:23 UTC, YashSartanpara1 commented on src/pages/Advisors/TabPanel/advisors.json
Please remove this file if not required.

2023-04-18 07:43 UTC, doracretu3pillar commented on src/pages/Advisors/TabPanel/advisors.json
removed

2023-04-18 07:54 UTC, YashSartanpara1 approved these changes

2023-04-18 14:19 UTC, merged