SAAS-405 dropdown component
percona-platform/saas-ui pull request #42
Opened 2020-10-20 20:25 UTC by nicolalamacchia

2020-10-24 08:47 UTC, atymchuk requested changes

2020-10-24 08:47 UTC, atymchuk commented on packages/platform-core/src/components/Dropdown/Dropdown.test.tsx
> +    expect(container.querySelector('[data-qa="dropdown-toggle"]')).not.toBe(null);
nit: Consider using `dataQa` fn for brevity sake (here and downwards)

2020-10-24 08:47 UTC, atymchuk commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +      <Toggle ref={toggleRef} onClick={handleDropdownClick} data-qa="dropdown-toggle" />
```suggestion
      <Toggle ref={toggleRef} onClick={handleDropdownClick} data-qa="dropdown-menu-toggle" />
```
Since may have other dropdown components, consider make it more specific

2020-10-24 08:47 UTC, atymchuk commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +        data-qa="dropdown-container"
```suggestion
        data-qa="dropdown-menu-container"
```
To stay consistent with the above ^

2020-10-24 08:47 UTC, atymchuk commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +            data-qa="dropdown-menu"
```suggestion
            data-qa="dropdown-menu-menu"
```
For consistency again

2020-10-24 08:47 UTC, atymchuk commented on packages/platform-core/src/components/index.ts
> +export * from './Dropdown';
nit: let's sort them ab

2020-10-26 10:08 UTC, nicolalamacchia commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +  const handleDocumentClick = (event: MouseEvent) => {
Should they really be wrapped? This function specifically is used only internally to the functional component, while the other is setting a state. I think performance won't benefit, or can even get worse

2020-10-26 10:12 UTC, nicolalamacchia commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +      event.target instanceof Node &&
That's needed mostly for type hinting on the arguments of the following `contains`. I guess we could just cast them to type `Node` if we want to get rid of that check

2020-10-26 10:20 UTC, nicolalamacchia commented on packages/platform-core/src/components/Dropdown/Dropdown.test.tsx
> +    expect(container.querySelector('[data-qa="dropdown-toggle"]')).not.toBe(null);
done

2020-10-26 10:28 UTC, nicolalamacchia commented on packages/platform-core/src/components/index.ts
> +export * from './Dropdown';
done

2020-10-26 10:44 UTC, nicolalamacchia commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +            data-qa="dropdown-menu"
done

2020-10-26 10:44 UTC, nicolalamacchia commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +        data-qa="dropdown-container"
done

2020-10-26 10:44 UTC, nicolalamacchia commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +      <Toggle ref={toggleRef} onClick={handleDropdownClick} data-qa="dropdown-toggle" />
done

2020-10-26 11:09 UTC, tiagomotasantos requested changes

2020-10-26 11:09 UTC, tiagomotasantos commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +  toggle: React.ForwardRefExoticComponent<any>;
Does it really need to be any here? Or some type like ReactNode or HTMLElement would work?

2020-10-26 11:09 UTC, tiagomotasantos commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +        {visible ? (
If you replace "?" with "&&" you can remove the unused else part of the condition here.

2020-10-26 11:12 UTC, atymchuk commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +      event.target instanceof Node &&
Agree, casting to `Node` seems to solve it.

2020-10-26 11:18 UTC, nicolalamacchia commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +        {visible ? (
I agree with you, but soon after I joined we had a discussion and decided to prefer the ternary operator to be more consistent and flexible (since you can't always use micro-branching)

2020-10-26 11:19 UTC, atymchuk commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +  const handleDocumentClick = (event: MouseEvent) => {
I agree, this conversation would have a more solid base in case we approach it with: `I profiled it and here is what I found`. But that's for the asking party, which is something I didn't plan on doing right now :) 
So yes, let's leave it as is.

2020-10-26 11:20 UTC, nicolalamacchia commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +  toggle: React.ForwardRefExoticComponent<any>;
They would, partially. The passed component needs a forwarded `ref`, otherwise we cannot refer to it in the dropdown

2020-10-26 11:22 UTC, nicolalamacchia commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +      event.target instanceof Node &&
done

2020-10-26 11:22 UTC, nicolalamacchia commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +  const handleDocumentClick = (event: MouseEvent) => {
:D ok

2020-10-26 11:51 UTC, tiagomotasantos commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +  toggle: React.ForwardRefExoticComponent<any>;
What that has to do with the any? (sorry just trying to understand if something like this would work React.ForwardRefExoticComponent<ReactNode> or React.ForwardRefExoticComponent<HTMLElement>)

2020-10-26 12:39 UTC, nicolalamacchia commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +  toggle: React.ForwardRefExoticComponent<any>;
Ohhh, sorry, I misread your first comment! I updated the type there :D

2020-10-26 13:26 UTC, tiagomotasantos commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +  toggle: React.ForwardRefExoticComponent<any>;
Oh okay 😁 got it, great!

2020-10-26 13:26 UTC, tiagomotasantos approved these changes

2020-10-27 11:14 UTC, tiagomotasantos approved these changes

2020-10-27 20:51 UTC, atymchuk approved these changes

2020-10-27 20:52 UTC, atymchuk commented
@nicolalamacchia It needs one more test to cover the keyboard nav :)

2020-10-28 09:23 UTC, nicolalamacchia commented
@atymchuk it does, but this has already gone way too far from the original estimation. We started with an investigation on a library and instead ended up developing our own dropdown. I suggest to deal with this separately.

2020-10-28 10:00 UTC, tiagomotasantos submitted a review, later dismissed

2020-10-28 10:33 UTC, atymchuk commented
> @atymchuk it does, but this has already gone way too far from the original estimation. We started with an investigation on a library and instead ended up developing our own dropdown. I suggest to deal with this separately.

1SP is arguably a good estimate for such a library component. It should be much higher given the inherent complexity of it.

2020-10-28 10:49 UTC, nicolalamacchia commented
> 1SP is arguably a good estimate for such a library component. It should be much higher given the inherent complexity of it.

For an homemade component I agree, it was a bad estimation, but again the original idea was to just research for a third party one and include it in our library :)

2020-10-28 10:59 UTC, atymchuk commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +    };
yes, I just didn't have enough stamina to do that ) 
Done!

2020-10-28 11:02 UTC, atymchuk commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +    };
> we're not listening for enter or other keyboard inputs to simulate the click on that entry.
What do you mean?

2020-10-28 11:25 UTC, atymchuk approved these changes

2020-10-28 11:42 UTC, nicolalamacchia commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +    };
well, I can scroll using arrow keys, but I cannot action on menu items. What's the point of having key navigation if the only thing I can do is to highlight menu items, but I still have to click on those with my mouse? :)

2020-10-28 11:47 UTC, atymchuk commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +    };
Wow, that's a good point! we'll need to get that implemented for sure :)

2020-10-28 12:09 UTC, atymchuk commented on packages/platform-core/src/components/Dropdown/Dropdown.tsx
> +    };
Done as well!

2020-10-28 12:10 UTC, atymchuk submitted a review, later dismissed

2020-10-28 12:56 UTC, atymchuk approved these changes

2020-10-28 18:58 UTC, merged