SAAS-393 execute e2e at minikube
percona-platform/saas-ui pull request #44
Opened 2020-10-29 09:52 UTC by yurkovychv

2020-10-29 09:59 UTC, AlekSi commented on .github/workflows/ci.yml
> +        uses: percona-platform/repository-dispatch@v1
Why not use https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch directly?

2020-10-29 10:03 UTC, AlekSi commented on .github/workflows/ci.yml
> +        uses: percona-platform/repository-dispatch@v1
Err, that's confusing :) What I really wanted to ask is why use repository_dispatch instead of workflow_dispatch?

2020-10-29 10:07 UTC, yurkovychv commented on .github/workflows/ci.yml
> +        uses: percona-platform/repository-dispatch@v1
There is no particular reason. Will try with workflow_dispatch

2020-11-03 08:43 UTC, AlekSi requested changes
We can't just clone infra repository there and copy&paste all setup instructions there – it would be very hard to keep them in sync, especially once we copy&paste in other repos too.

We need find solution that will run tests in the context of infra repo or separate cicd repo. We talked about workflow_dispatch and repository_dispatch – was there any follow up?

2020-11-03 08:43 UTC, AlekSi commented on .github/workflows/ci.yml
> +        uses: percona-platform/repository-dispatch@v1
Why that was abandoned?

2020-11-03 08:51 UTC, yurkovychv commented
I need a spike for that, I was testing it with workflow_dispatch. But it does not affect PR checks (if tests failed a PR does not indicate that, and it is not clear which exact PR triggered that workflow). It just says `Manually run by percona-robot`. The best way would be to have 1 workflow in `cicd` repo. But again we need to find a way to detect which PR triggered it (without reading logs) and indicate it in the original PR.

2020-11-03 08:52 UTC, yurkovychv commented on .github/workflows/ci.yml
> +        uses: percona-platform/repository-dispatch@v1
I replied [here](https://github.com/percona-platform/saas-ui/pull/44#issuecomment-720983995)

2020-11-03 12:14 UTC, nicolalamacchia commented on .github/workflows/e2e.yml
> +        if: ${{ always() }}
Why is this needed?

2020-11-03 12:14 UTC, nicolalamacchia commented on .github/workflows/e2e.yml
> +            */*/*/node_modules
would `**/nodemodules` work here?

2020-11-03 12:33 UTC, AlekSi approved these changes

2020-11-03 12:35 UTC, AlekSi commented on .github/workflows/e2e.yml
> +        if: ${{ always() }}
It can also be `canceled`, and it is different from being failed

2020-11-03 12:52 UTC, yurkovychv commented on .github/workflows/e2e.yml
> +        if: ${{ always() }}
Yes, we need this step to be executed anyway

2020-11-03 12:52 UTC, yurkovychv commented on .github/workflows/e2e.yml
> +            */*/*/node_modules
not sure, should I try It now? Anyway, this workflow will be moved to another repo and updated soon.

2020-11-03 13:02 UTC, nicolalamacchia approved these changes

2020-11-03 13:47 UTC, merged