PMM-6925 table toolbar
percona-platform/saas-ui pull request #57
Opened 2020-11-18 22:18 UTC by nicolalamacchia

2020-11-19 09:43 UTC, tiagomotasantos submitted a review, later dismissed

2020-11-19 09:43 UTC, tiagomotasantos commented on packages/platform-core/src/components/TableToolbar/TableToolbar.tsx
> +      {actions.map(action => {
Why not destructure the action here? 🤔

2020-11-19 09:43 UTC, tiagomotasantos commented on packages/platform-core/src/components/TableToolbar/types.ts
> +  callback: () => {};
Does the callback return an empty object or is void?

2020-11-19 10:33 UTC, nicolalamacchia commented on packages/platform-core/src/components/TableToolbar/TableToolbar.tsx
> +      {actions.map(action => {
Oops, right, done

2020-11-19 10:46 UTC, nicolalamacchia commented on packages/platform-core/src/components/TableToolbar/types.ts
> +  callback: () => {};
it's `void`, updated it :)

2020-11-19 11:55 UTC, tiagomotasantos approved these changes

2020-11-19 12:38 UTC, atymchuk requested changes

2020-11-19 12:38 UTC, atymchuk commented on packages/platform-core/src/components/Icon/Icon.tsx
> +  toolbarAdd: TableToolbarAdd,
If an icon can be used elsewhere, then it's better to give it a name that does not contain the domain (ie. `toolbar` and `table`). 
However, since the `Add` icons can be of different shapes (ex: circled, square, etc) we should hint the dev about the shape. => `AddSquare` or `AddCircle`.
Grafana got it right, good naming approach here https://developers.grafana.com/ui/latest/index.html?path=/story/docs-overview-icon--icons-overview

2020-11-19 12:38 UTC, atymchuk commented on packages/platform-core/src/components/Icon/Icon.tsx
> +export const Icon: FC<IconProps> = ({ name }) => {
What about passing basic props, for example to change the icon size? Seems relevant

2020-11-19 12:38 UTC, atymchuk commented on packages/platform-core/src/components/TableToolbar/TableToolbar.tsx
> +  const styles = useMemo(() => getStyles(), []);
This seems to be contrary to the recommendation (https://github.com/grafana/grafana/blob/master/contribute/style-guides/themes.md#usestyles-hook). useStyles is memoized. And it's probably not compatible with the theme switch.

2020-11-19 12:38 UTC, atymchuk commented on packages/platform-core/src/components/TableToolbar/TableToolbarButton.tsx
> +  const styles = useMemo(() => getStyles(theme), [theme]);
should be useStyles; both useTheme & useMemo are not necessary.

2020-11-19 12:38 UTC, atymchuk commented on packages/platform-core/src/components/TableToolbar/types.ts
> +  minItems?: number;
Sorry, how the min/max are used?

2020-11-19 14:52 UTC, nicolalamacchia commented on packages/platform-core/src/components/TableToolbar/types.ts
> +  minItems?: number;
it's the minimum/maximum number of items to be selected for the action to be enabled

2020-11-19 14:52 UTC, nicolalamacchia commented on packages/platform-core/src/components/Icon/Icon.tsx
> +export const Icon: FC<IconProps> = ({ name }) => {
I'd prefer to keep this outside of the scope of the ticket

2020-11-19 15:17 UTC, nicolalamacchia commented on packages/platform-core/src/components/TableToolbar/TableToolbar.tsx
> +  const styles = useMemo(() => getStyles(), []);
oh, I forgot about that! Fixed

2020-11-19 15:17 UTC, nicolalamacchia commented on packages/platform-core/src/components/TableToolbar/TableToolbarButton.tsx
> +  const styles = useMemo(() => getStyles(theme), [theme]);
Done

2020-11-19 15:21 UTC, atymchuk commented on packages/platform-core/src/components/TableToolbar/types.ts
> +  minItems?: number;
In this case we don't need it. There is simply no use case for anything other than `check if [...selected].length > 1`.
Let's keep it simple, which should reduce the amount of code and the testing effort.

2020-11-19 15:28 UTC, nicolalamacchia commented on packages/platform-core/src/components/TableToolbar/types.ts
> +  minItems?: number;
there might be actions needing just one element, while other needing > 1, or did I get this wrong? 😅 In that case, I'd agree with you

2020-11-19 15:55 UTC, nicolalamacchia commented on packages/platform-core/src/components/Icon/Icon.tsx
> +  toolbarAdd: TableToolbarAdd,
Good point, done!

2020-11-19 16:02 UTC, atymchuk commented on packages/platform-core/src/components/TableToolbar/types.ts
> +  minItems?: number;
By design, actions applicable for just one element would go to the `Actions` column. This is place for either mass actions, i.e. which need >= 2 records to be fired, or what we call `one-off` actions (like `Add a record`), which do not depend on the the number of records selected. 
In other words, I don't know of a use case, where `min` would be 1 or 3. It's always `two or more records` for the mass actions.

2020-11-19 16:13 UTC, atymchuk requested changes

2020-11-19 16:13 UTC, atymchuk commented on packages/platform-core/src/components/Icon/Icon.tsx
> +  selectedSquare: SelectedSquare,
From the goal standpoint, this should be `Enable`, the one below would be `Disable`. And we need them to have meaningful names :)

2020-11-19 16:13 UTC, atymchuk commented on packages/platform-core/src/components/TableToolbar/TableToolbar.tsx
> +        if (minItems < 0 || maxItems < 0) {
I'm sure we don't have this in the scope. We enable/disable the mass action icons when the number of records selected is `>1`. So the user wouldn't be able to fire a mass action otherwise, which would make the error messages redundant.

2020-11-19 17:28 UTC, nicolalamacchia commented on packages/platform-core/src/components/Icon/Icon.tsx
> +  selectedSquare: SelectedSquare,
Done

2020-11-19 17:29 UTC, nicolalamacchia commented on packages/platform-core/src/components/TableToolbar/types.ts
> +  minItems?: number;
got it, done

2020-11-20 15:40 UTC, atymchuk commented on packages/platform-core/src/components/TableToolbar/TableToolbar.tsx
> +        if (minItems < 0 || maxItems < 0) {
@nicolalamacchia so, what do you think?

2020-11-23 11:02 UTC, nicolalamacchia commented on packages/platform-core/src/components/TableToolbar/TableToolbar.tsx
> +        if (minItems < 0 || maxItems < 0) {
I already did remove the error : )

2020-11-23 11:10 UTC, tiagomotasantos approved these changes

2020-11-23 11:32 UTC, atymchuk approved these changes

2020-11-23 11:33 UTC, merged