PMM-407 demo page
percona-platform/saas-ui pull request #65
Opened 2020-12-30 20:04 UTC by nicolalamacchia

2021-01-05 14:19 UTC, tiagomotasantos approved these changes

2021-01-06 09:27 UTC, atymchuk requested changes

2021-01-06 09:27 UTC, atymchuk commented on packages/platform-ui/src/pages/UIDemo/components/FormFields/CheckboxFields.tsx
> +            src="/FormFields/CheckboxFields.tsx#L9-L29"
```suggestion
            src="/FormFields/CheckboxFields.tsx#L31-L49"
```

2021-01-06 09:27 UTC, atymchuk commented on packages/platform-ui/src/pages/UIDemo/components/FormFields/CheckboxFields.tsx
> +          <CheckboxField name="agreed" label="I agree" />
```suggestion
          <CheckboxField name="consent" label="I agree" />
```

2021-01-06 09:27 UTC, atymchuk commented on packages/platform-ui/src/pages/UIDemo/components/FormFields/CheckboxFields.tsx
> +          <CheckboxField name="agreed" label="I agree" />
Gotta be a noun )

2021-01-06 09:27 UTC, atymchuk commented on packages/platform-ui/src/pages/UIDemo/components/FormFields/CheckboxFields.tsx
> +          <CheckboxField name="enable-feature" label="Enable feature" disabled />
Grabbing a value from the form values would be cumbersome I believe, i.e. `values['enable-feature']` vs `values.enableFeature`.

2021-01-06 09:27 UTC, atymchuk commented on packages/platform-ui/src/pages/UIDemo/components/FormFields/CheckboxFields.tsx
> +          <CheckboxField name="enable-feature" label="Enable feature" disabled />
```suggestion
          <CheckboxField name="enableFeature" label="Enable feature" disabled />
```

2021-01-06 09:27 UTC, atymchuk commented on packages/platform-ui/src/pages/UIDemo/components/FormFields/CheckboxFields.tsx
> +            src="/FormFields/CheckboxFields.tsx#L73-L91"
Is the code line reference correct here?

2021-01-06 09:27 UTC, atymchuk commented on packages/platform-ui/src/pages/UIDemo/components/FormFields/TextareaInputFields.tsx
> +const RESIZE_OPTIONS: Array<SelectableValue<'vertical' | 'horizontal' | 'both'>> = [
Not bad, but what if you have a hundred values? Wouldn't `Array<SelectableValue<string>>` do the job?

2021-01-06 09:27 UTC, atymchuk commented on packages/platform-ui/src/pages/UIDemo/components/Overlays/Modals.tsx
> +        src="/Buttons/Modals.tsx#L8-L54"
Should probably be `/Overlays/Modals.tsx`

2021-01-06 09:27 UTC, atymchuk commented on packages/platform-ui/src/pages/UIDemo/components/Heading/Heading.tsx
> +    <header id={id} className={styles.heading}>
Do we really need an id here? Not the best practice, imho, since ids must be unique across the app. Can we use something else, maybe a `data-*` attribute or anything that is not an id?

2021-01-06 13:25 UTC, atymchuk requested changes

2021-01-06 16:51 UTC, nicolalamacchia commented on packages/platform-ui/src/pages/UIDemo/UIDemo.test.tsx
> +import { fireEvent } from '@testing-library/react';
Done

2021-01-06 16:51 UTC, nicolalamacchia commented on packages/platform-ui/src/pages/UIDemo/UIDemo.test.tsx
> +    container = document.createElement('div');
Done!

2021-01-06 17:01 UTC, nicolalamacchia commented on packages/platform-ui/src/pages/UIDemo/components/Buttons/LoaderButtons.tsx
> +    await new Promise((resolve) => { setTimeout(resolve, TIMEOUT); });
Done

2021-01-06 17:05 UTC, nicolalamacchia commented on packages/platform-ui/src/pages/UIDemo/components/FormFields/CheckboxFields.tsx
> +          <CheckboxField name="agreed" label="I agree" />
Yeah, and it sounds way better xD

2021-01-06 17:07 UTC, nicolalamacchia commented on packages/platform-ui/src/pages/UIDemo/components/FormFields/CheckboxFields.tsx
> +          <CheckboxField name="enable-feature" label="Enable feature" disabled />
Done

2021-01-06 17:09 UTC, nicolalamacchia commented on packages/platform-ui/src/pages/UIDemo/components/FormFields/CheckboxFields.tsx
> +            src="/FormFields/CheckboxFields.tsx#L73-L91"
Fixed

2021-01-06 17:11 UTC, nicolalamacchia commented on packages/platform-ui/src/pages/UIDemo/components/FormFields/TextareaInputFields.tsx
> +const RESIZE_OPTIONS: Array<SelectableValue<'vertical' | 'horizontal' | 'both'>> = [
You're right, but in this case we still have to specify manually the options in the object, so I don't think it's a problem here

2021-01-06 17:13 UTC, nicolalamacchia commented on packages/platform-ui/src/pages/UIDemo/components/Overlays/Modals.tsx
> +        src="/Buttons/Modals.tsx#L8-L54"
Fixed

2021-01-06 17:14 UTC, nicolalamacchia commented on packages/platform-ui/src/pages/UIDemo/components/Heading/Heading.tsx
> +    <header id={id} className={styles.heading}>
I'm using an `id` just to allow the use of fragments on the page

2021-01-06 17:52 UTC, nicolalamacchia commented on packages/platform-ui/src/pages/UIDemo/components/Buttons/Dropdowns.tsx
> +    alert('First');
Done

2021-01-08 11:55 UTC, atymchuk commented on packages/platform-ui/src/pages/UIDemo/components/Heading/Heading.tsx
> +    <header id={id} className={styles.heading}>
Sorry, how do we use the ids for fragments?

2021-01-12 10:26 UTC, atymchuk commented
Approving this, pls create a ticket for know render issues for the dark theme.

2021-01-12 10:26 UTC, atymchuk approved these changes

2021-01-12 14:00 UTC, nicolalamacchia commented on packages/platform-ui/src/pages/UIDemo/components/Heading/Heading.tsx
> +    <header id={id} className={styles.heading}>
leveraging the default native behavior of browsers when pointing to page fragments with `#`, e.g.: `#modals`, the page is scrolled down to the element with the `modals` id

2021-01-12 14:35 UTC, nicolalamacchia commented
[SAAS-471](https://jira.percona.com/browse/SAAS-471) and [SAAS-472](https://jira.percona.com/browse/SAAS-472) have been created

2021-01-13 10:25 UTC, fabio-silva approved these changes

2021-03-02 09:21 UTC, merged