Saas 385 UI 404
percona-platform/saas-ui pull request #66
Opened 2021-01-13 09:45 UTC by fabio-silva

**What this PR does / why we need it:** Adds a 404 "Not Found" page when an authenticated user tries to reach an inexistent page (not authenticated users keep being redirected to login). This page follows the theme rules, being either light or dark.

**Which issue(s) this PR fixes:** https://jira.percona.com/browse/SAAS-385

2021-01-13 18:57 UTC, nicolalamacchia requested changes

2021-01-13 18:57 UTC, nicolalamacchia commented on packages/platform-ui/src/assets/404-dark.svg
> +<svg width="532" height="442" viewBox="0 0 532 442" fill="none" xmlns="http://www.w3.org/2000/svg">
Please, format this file and the other SVG

2021-01-13 18:57 UTC, nicolalamacchia commented on packages/platform-ui/src/components/Root/Main.tsx
> +          }
Please rely on our eslint rules and our formatting rules, formatting should be consistent

2021-01-13 18:57 UTC, nicolalamacchia commented on packages/platform-ui/src/components/Root/Main.tsx
> +          }
```suggestion
          {authenticated ? <NotFound /> : <Redirect to={Routes.login} />}
```

2021-01-13 18:57 UTC, nicolalamacchia commented on packages/platform-ui/src/pages/NotFound/NotFound.styles.ts
> +  } = theme;
check formatting here as well

2021-01-13 18:57 UTC, nicolalamacchia commented on packages/platform-ui/src/pages/NotFound/NotFound.styles.ts
> +      padding: 2em; // TODO set this on core and change everywhere, as it's used several times
the comment should go on its own line

2021-01-13 18:57 UTC, nicolalamacchia commented on packages/platform-ui/src/pages/NotFound/NotFound.tsx
> +      <img data-qa={`404-image-${dataQaImgAttr}`} className={styles.logo} alt="404" src={logo} />
I suggest you use a static `data-qa` attribute, to make it more predictable, we are not going to check if the theme is dark or light here.

2021-01-13 18:57 UTC, nicolalamacchia commented on packages/platform-ui/src/styles/global.css
> +
do we really need this? if so, why?

2021-01-13 22:22 UTC, fabio-silva commented on packages/platform-ui/src/assets/404-dark.svg
> +<svg width="532" height="442" viewBox="0 0 532 442" fill="none" xmlns="http://www.w3.org/2000/svg">
👍

2021-01-13 22:23 UTC, fabio-silva commented on packages/platform-ui/src/components/Root/Main.tsx
> +          }
You're right! But the linter doesn't complain about this one. It seems we're missing the `react/jsx-curly-newline` rule. Should I open a PR adding this?

2021-01-13 22:24 UTC, fabio-silva commented on packages/platform-ui/src/pages/NotFound/NotFound.styles.ts
> +  } = theme;
Got it 👍

2021-01-13 22:24 UTC, fabio-silva commented on packages/platform-ui/src/pages/NotFound/NotFound.styles.ts
> +      padding: 2em; // TODO set this on core and change everywhere, as it's used several times
👍

2021-01-13 22:24 UTC, fabio-silva commented on packages/platform-ui/src/pages/NotFound/NotFound.tsx
> +      <img data-qa={`404-image-${dataQaImgAttr}`} className={styles.logo} alt="404" src={logo} />
Ok, if we're not checking the theme, I guess it makes sense to remove it

2021-01-13 22:28 UTC, fabio-silva commented on packages/platform-ui/src/styles/global.css
> +
So, without this rule, this is the result:

![Screenshot 2021-01-13 at 22 21 17](https://user-images.githubusercontent.com/4190654/104517622-413c9980-55ee-11eb-8265-532dcf05b84b.png)

I thought about setting it globally because usually these kind of anchor styles apply everywhere. I can tell it's being applied locally [here](https://github.com/percona-platform/saas-ui/blob/main/packages/platform-ui/src/pages/Login/Login.styles.ts#L46).
Should I keep it local?

2021-01-14 09:58 UTC, nicolalamacchia commented on packages/platform-ui/src/styles/global.css
> +
Yes, please avoid global style unless strictly needed (to reset browsers' CSS or set style for third party components that require that). That style will be refactored when a `Button` component will be created.

2021-01-14 10:02 UTC, nicolalamacchia commented on packages/platform-ui/src/components/Root/Main.tsx
> +          }
No, try to keep PRs tied to tickets as much as possible. If needed, create a separate ticket. In this case you could do it in this PR, since the change is minimal :)

2021-01-14 10:32 UTC, fabio-silva commented on packages/platform-ui/src/components/Root/Main.tsx
> +          }
Sure, agreed :))

2021-01-14 10:33 UTC, fabio-silva commented on packages/platform-ui/src/styles/global.css
> +
Ok, I guess that Button could wrap those styles afterwards 👍

2021-01-14 13:47 UTC, nicolalamacchia commented on packages/platform-ui/src/pages/NotFound/NotFound.test.tsx
> +    expect(container.querySelector('[data-qa="404-image"]')).not.toBeNull();
you can use the utility `dataQa` here from `platform-core`

2021-01-14 13:59 UTC, fabio-silva commented on packages/platform-ui/src/pages/NotFound/NotFound.test.tsx
> +    expect(container.querySelector('[data-qa="404-image"]')).not.toBeNull();
Changed here and in Main.tsx 👍

2021-01-14 16:02 UTC, tiagomotasantos requested changes

2021-01-14 16:02 UTC, tiagomotasantos commented on packages/platform-ui/src/pages/NotFound/NotFound.styles.ts
> +export const getStyles = (theme: GrafanaTheme) => {
theme can be destructured here

2021-01-14 16:13 UTC, fabio-silva commented on packages/platform-ui/src/components/Root/Main.tsx
> +          {authenticated ? <NotFound /> : <Redirect to={Routes.login} />}
Nice one! Seems reasonable

2021-01-14 20:03 UTC, nicolalamacchia commented on packages/platform-ui/src/components/Root/Main.tsx
> +          {authenticated ? <NotFound /> : <Redirect to={Routes.login} />}
That's actually the right way of doing that :D good catch @tiagomotasantos

2021-01-14 20:20 UTC, atymchuk commented on packages/platform-ui/src/pages/NotFound/NotFound.styles.ts
> +      dashboardBg,
nit: I don't think we should run the cost of too much wrapping here - it takes too long to read it.
It's totally fine not to destructure `dashboardBg` and `spacingLg` and use it in the code as `colors.dashboardBg` etc. Prefer explicit over guessing where the `dashboardBg` comes from: colors or palette.

2021-01-14 20:20 UTC, atymchuk commented on packages/platform-ui/src/pages/NotFound/NotFound.styles.ts
> +      // TODO set this on core and change everywhere, as it's used several times
What does this comment refer to? It doesn't say how, so not enough context to fix it for someone later. As a result, this will pile up and never get fixed. The core is in the same repo, so why not fix it right away?

2021-01-14 20:42 UTC, atymchuk requested changes

2021-01-14 20:42 UTC, atymchuk commented on packages/platform-ui/src/pages/NotFound/NotFound.test.tsx
> +import { render, unmountComponentAtNode } from 'react-dom';
No need to be using react-dom directly, since it's pretty low-level and requires more dance.
Pls check out best practices for [react-dom/test-utils](https://testing-library.com/docs/react-testing-library/example-intro/#full-example) and a good example [here](https://github.com/percona-platform/saas-ui/blob/main/packages/platform-ui/src/components/MenuBar/MenuBar.test.tsx).

Benefits:
1/ no need to create a container with document.createElement and to destroy it
2/ much less code, more readable
3/ fewer imports

2021-01-14 22:32 UTC, fabio-silva commented on packages/platform-ui/src/pages/NotFound/NotFound.styles.ts
> +      // TODO set this on core and change everywhere, as it's used several times
I see your point. Any recommendation regarding the level at which this padding should be defined? Because [here](https://github.com/percona-platform/saas-ui/blob/main/packages/platform-core/src/theming/default.ts) I see paddings defined both in `spacing` and as standalone properties like `panelPadding`. Or should paddings form a category of their own inside `spacing`, similar to what's done by [style-dictionary](https://github.com/amzn/style-dictionary/blob/master/examples/complete/properties/size/padding.json) ?

2021-01-14 22:32 UTC, fabio-silva commented on packages/platform-ui/src/pages/NotFound/NotFound.test.tsx
> +import { render, unmountComponentAtNode } from 'react-dom';
You're right, thanks for the tip!

2021-01-14 22:33 UTC, fabio-silva commented on packages/platform-ui/src/pages/NotFound/NotFound.styles.ts
> +      dashboardBg,
Thanks!

2021-01-15 08:01 UTC, atymchuk commented on packages/platform-ui/src/pages/NotFound/NotFound.styles.ts
> +      // TODO set this on core and change everywhere, as it's used several times
Good question. It depends on where it belongs in. For example, if this padding is part of the form elements and it provides padding around those elements, it may live in `spacing.formElementPadding` (as an example, not a true thing), but this one is part of `contentWrapper`, so I'm not event sure we would ever have the same paddings on all content wrappers, which we may have thousands of in one app.

Maybe, it is premature to pretend it can go to the core. What was your intention? How would we use it going forward? Maybe you can drop an example?

2021-02-09 15:45 UTC, nicolalamacchia commented on packages/platform-ui/src/pages/NotFound/NotFound.styles.ts
> +    `,
Spacing looks messed up here

2021-02-09 18:09 UTC, fabio-silva commented on packages/platform-ui/src/pages/NotFound/NotFound.styles.ts
> +    `,
you're right 👍

2021-02-18 17:04 UTC, tiagomotasantos submitted a review, later dismissed

2021-02-19 10:04 UTC, nicolalamacchia approved these changes

2021-02-19 12:22 UTC, atymchuk approved these changes

2021-03-03 12:23 UTC, nicolalamacchia approved these changes

2021-03-03 12:52 UTC, merged