SAAS-495 auth tests
percona-platform/saas-ui pull request #71
Opened 2021-02-26 07:47 UTC by yurkovychv

2021-02-26 09:34 UTC, nicolalamacchia commented on packages/platform-ui/cypress/pages/auth/utils/getNewUser.ts
> +
please, import a module by using `import`

2021-02-26 09:34 UTC, nicolalamacchia commented on packages/platform-ui/cypress/pages/auth/utils/getNewUser.ts
> +};
do we really need a dependency to generate fake password?

2021-02-26 09:45 UTC, yurkovychv commented on packages/platform-ui/cypress/pages/auth/utils/getNewUser.ts
> +};
why shouldn't we?

2021-02-26 09:45 UTC, yurkovychv commented on packages/platform-ui/cypress/pages/auth/utils/getNewUser.ts
> +
sure

2021-02-26 11:56 UTC, atymchuk requested changes

2021-02-26 11:56 UTC, atymchuk commented on packages/platform-ui/cypress/pages/auth/utils/getNewUser.ts
> +};
IMHO not a problem to use an external dependency, since we:
1/ save time creating it from scratch
2/ don't want to cover it with tests
3/ don't ship it (it's not part of the bundle)

2021-02-26 11:56 UTC, atymchuk commented on packages/platform-ui/cypress/pages/auth/utils/getNewUser.ts
> +    length: 15,
We should probably have the length as per the architecture docs, i.e. 8 characters long.

2021-02-26 19:48 UTC, atymchuk approved these changes

2021-03-01 09:16 UTC, nicolalamacchia approved these changes

2021-03-01 09:17 UTC, merged