Experimental modification to give additional docker tag for dev-latest
percona-platform/saas-ui pull request #77
Opened 2021-03-15 16:55 UTC by browseman

2021-03-15 20:46 UTC, atymchuk requested changes

2021-03-15 20:46 UTC, atymchuk commented on Makefile
> +	    docker push $(DOCKER_IMAGE):dev-latest;
```suggestion
	if [[ "$(DOCKER_TAG)" != "latest" ]]; then
	    docker tag $(DOCKER_IMAGE):$(DOCKER_TAG) $(DOCKER_IMAGE):dev-latest
	    docker push $(DOCKER_IMAGE):dev-latest
	fi
```
This reads better and is more straightforward )

2021-03-15 20:46 UTC, atymchuk commented on .github/workflows/ci.yml
> +        run: make docker-tag
Sound a bit misleading, the DOCKER_TAG is made elsewhere. We are pushing the dev-latest there.
```suggestion
        run: make docker-push-dev-latest
```

2021-03-15 20:46 UTC, atymchuk commented on .github/workflows/ci.yml
> +      - name: Tag Docker image with dev-latest
```suggestion
      - name: Tag Docker image with dev-latest and push to the registry
```

2021-03-15 20:46 UTC, atymchuk commented on Makefile
> +docker-tag:
```suggestion
docker-push-dev-latest:
```

2021-03-15 20:50 UTC, atymchuk commented on Makefile
> +	    docker push $(DOCKER_IMAGE):dev-latest;
It looks like we will prevent the engineers from developing in parallel, since every container in every PR will be pushed with `dev-latest` label, so the last push will overwrite the previous one. Let's discuss one more time...

2021-03-16 11:57 UTC, nicolalamacchia commented on Makefile
> +	    docker push $(DOCKER_IMAGE):dev-latest;
> This reads better and is more straightforward )

Added semicolons and backslashes to make this work :)

```suggestion
	if [[ "$(DOCKER_TAG)" == "latest" ]]; then \
		docker tag $(DOCKER_IMAGE):$(DOCKER_TAG) $(DOCKER_IMAGE):dev-latest; \
		docker push $(DOCKER_IMAGE):dev-latest; \
	fi; \
```

2021-03-16 13:08 UTC, atymchuk commented on Makefile
> +	    docker push $(DOCKER_IMAGE):dev-latest;
I guess it should be `!=` :)

2021-03-16 13:26 UTC, browseman commented on Makefile
> +	    docker push $(DOCKER_IMAGE):dev-latest;
Well it's better to be like this, for sure. As for why it's presented like that, because it's a leftover from previous attempt /experiment, was a bit quicker to add the exit :worried:

2021-03-16 13:50 UTC, browseman commented on .github/workflows/ci.yml
> +        run: make docker-tag
Well actually it perform both tasks, 'tagging' and 'pushing' in one target inside the makefile. So not 100% sure if the naming should be `docker-tag-push-dev-latest`

2021-03-16 15:04 UTC, nicolalamacchia commented on Makefile
> +	    docker push $(DOCKER_IMAGE):dev-latest;
> I guess it should be `!=`, because `== latest` was meant to exit :)

oopsie

2021-11-18 23:41 UTC, atymchuk commented
Closing this to get out of sight, we can re-open at any time.

2021-11-18 23:41 UTC, closed without merging