SAAS-491 registration with okta
percona-platform/saas-ui pull request #80
Opened 2021-03-19 10:04 UTC by nicolalamacchia

2021-03-19 15:35 UTC, tiagomotasantos requested changes

2021-03-19 15:35 UTC, tiagomotasantos commented on packages/platform-ui/src/core/api/auth.ts
> +export const signUp: SignUp = ({ email, firstName = 'First', lastName = 'Last' }) => {
Would put these default strings the messages file too.

2021-03-19 15:35 UTC, tiagomotasantos commented on packages/platform-ui/src/store/auth/auth.reducer.ts
> +)<{ email: string; firstName: string, lastName: string, password: string }, undefined, grpcWeb.Error>();
Better to use an interface here since this is getting big.

2021-03-19 17:54 UTC, atymchuk requested changes

2021-03-19 17:54 UTC, atymchuk commented on packages/platform-ui/src/core/api/auth.ts
> +export const signUp: SignUp = ({ email, firstName = 'First', lastName = 'Last' }) => {
Are those defaults? I don't see why we would put these values as defaults... If no firstName is provide, the API should just fail.

2021-03-19 17:54 UTC, atymchuk commented on packages/platform-ui/src/core/api/messages.ts
> +  signUpSucceeded: 'A confirmation email has been sent to you',
```suggestion
  signUpSucceeded: 'An account activation email has been sent to you',
```

2021-03-19 17:54 UTC, atymchuk commented on packages/platform-ui/src/core/gen/web/auth/auth_api_pb.js
> +    password: jspb.Message.getFieldWithDefault(msg, 2, ""),
Do we no longer generate the code?

2021-03-22 12:14 UTC, nicolalamacchia commented on packages/platform-ui/src/core/gen/web/auth/auth_api_pb.js
> +    password: jspb.Message.getFieldWithDefault(msg, 2, ""),
We still rely on generated code, we're going to change this soon though

2021-03-22 14:18 UTC, fabio-silva submitted a review, later dismissed

2021-03-22 15:08 UTC, nicolalamacchia commented on packages/platform-ui/src/store/auth/auth.reducer.ts
> +)<{ email: string; firstName: string, lastName: string, password: string }, undefined, grpcWeb.Error>();
Done

2021-03-22 16:28 UTC, fabio-silva submitted a review, later dismissed

2021-03-23 12:04 UTC, tiagomotasantos reviewed
Some auth related tests are failing, other then that LGTM.

2021-03-23 21:59 UTC, fabio-silva requested changes

2021-03-23 21:59 UTC, fabio-silva commented on packages/platform-ui/cypress/integration/auth/signup.spec.ts
> +  it('should not be able to login with not activated account', () => {
"not activated account" -> "inactive account"?

2021-03-23 21:59 UTC, fabio-silva commented on packages/platform-ui/cypress/integration/auth/signup.spec.ts
> +      cy.mailosaurGetMessage(Cypress.env('MAILOSAUR_SAAS_SERVER_ID'), {sentTo: userEmail}, {timeout: 20000})
some spacing missing before/after brackets

2021-03-23 21:59 UTC, fabio-silva commented on packages/platform-ui/cypress/pages/auth/flows/validation.flow.ts
> +    checkValidation({element: lastNameValidation, text: VALIDATION_MESSAGES.REQUIRED_FIELD});
spacing problem as well

2021-03-23 21:59 UTC, fabio-silva commented on packages/platform-ui/cypress/pages/auth/utils/getUser.ts
> +    activationEmailSentMessage: 'An account activation email has been sent to you',
aren't we repeating the same messages defined in `packages/platform-ui/src/core/api/messages.ts` ?

2021-03-23 22:08 UTC, nicolalamacchia commented on packages/platform-ui/cypress/integration/auth/signup.spec.ts
> +      cy.mailosaurGetMessage(Cypress.env('MAILOSAUR_SAAS_SERVER_ID'), {sentTo: userEmail}, {timeout: 20000})
@yurkovychv this is a nit, but your linter might need some adjustments ;P

2021-03-23 22:08 UTC, nicolalamacchia commented on packages/platform-ui/cypress/pages/auth/utils/getUser.ts
> +    activationEmailSentMessage: 'An account activation email has been sent to you',
Those are issues (nitpicks) that were already there or are relevant to e2e. For the sake of speed, let’s leave them for now :)

2021-03-24 06:29 UTC, yurkovychv commented on packages/platform-ui/cypress/pages/auth/utils/getUser.ts
> +    activationEmailSentMessage: 'An account activation email has been sent to you',
@nicolalamacchia @fabio-silva Agree, it was done in rush to not block FE merges. I plan to refactor those tests in a near time

2021-03-24 10:05 UTC, fabio-silva approved these changes

2021-03-24 22:05 UTC, tiagomotasantos approved these changes

2021-03-30 07:09 UTC, atymchuk approved these changes

2021-03-30 07:09 UTC, atymchuk commented on packages/platform-ui/cypress/pages/auth/flows/validation.flow.ts
> +  lastNameField, lastNameValidation,
nit: need to break it to two lines tbc

2021-03-31 12:59 UTC, merged