SAAS-490 user profile page
percona-platform/saas-ui pull request #88
Opened 2021-04-20 12:21 UTC by nicolalamacchia

2021-04-21 16:47 UTC, fabio-silva approved these changes
Just some nits, nothing much aside from that 👌

2021-04-21 16:47 UTC, fabio-silva commented on src/core/gen/web/auth/Auth_apiServiceClientPb.ts
> +      return request.serializeBinary();
nit: immediate return

2021-04-21 16:47 UTC, fabio-silva commented on src/core/gen/web/auth/Auth_apiServiceClientPb.ts
> +        this.hostname_ +
nit: string template

2021-04-21 16:47 UTC, fabio-silva commented on src/core/gen/web/auth/Auth_apiServiceClientPb.ts
> +    this.hostname_ +
nit: same as above

2021-04-21 16:47 UTC, fabio-silva commented on src/core/gen/web/auth/Auth_apiServiceClientPb.ts
> +      return request.serializeBinary();
also there are similar patterns below

2021-04-21 16:47 UTC, fabio-silva commented on src/core/gen/web/auth/Auth_apiServiceClientPb.ts
> +    metadata || {},
nit: if this is to prevent null/undefined , nullish coalescing operator could be used

2021-04-21 16:47 UTC, fabio-silva commented on src/core/gen/web/auth/Auth_apiServiceClientPb.ts
> +    metadata || {},
(also present in other parts in this code chunk)

2021-04-21 16:47 UTC, fabio-silva commented on src/pages/Profile/Profile.styles.ts
> +      & > * {
I can tell we're targeting `TextInputField`s down there. Is there a better option that `*` ?

2021-04-21 17:18 UTC, atymchuk requested changes

2021-04-21 18:33 UTC, atymchuk commented on src/core/gen/web/auth/Auth_apiServiceClientPb.ts
> +          '/percona.platform.auth.v1.AuthAPI/GetProfile',
oops, it's generated, so not much we can do )

2021-04-23 10:52 UTC, nicolalamacchia commented on src/core/gen/web/auth/Auth_apiServiceClientPb.ts
> +      return request.serializeBinary();
this is generated code

2021-04-23 10:52 UTC, nicolalamacchia commented on src/core/gen/web/auth/Auth_apiServiceClientPb.ts
> +        this.hostname_ +
this is generated code

2021-04-23 10:52 UTC, nicolalamacchia commented on src/core/gen/web/auth/Auth_apiServiceClientPb.ts
> +    this.hostname_ +
this is generated code

2021-04-23 10:53 UTC, nicolalamacchia commented on src/core/gen/web/auth/Auth_apiServiceClientPb.ts
> +    metadata || {},
this is generated code

2021-04-23 10:56 UTC, nicolalamacchia commented on src/components/MenuBar/MenuBar.tsx
> +  const goToProfilePage = async () => {
done

2021-04-23 10:57 UTC, fabio-silva commented on src/core/gen/web/auth/Auth_apiServiceClientPb.ts
> +    metadata || {},
oh, ok, didn't know about that

2021-04-23 11:00 UTC, nicolalamacchia commented on src/pages/Profile/Profile.styles.ts
> +      & > * {
`nameFields` is a wrapper around two text input fields, this is targeting those immediate children. There might be, but this should be good enough. What do you suggest?

2021-04-23 11:03 UTC, fabio-silva commented on src/pages/Profile/Profile.styles.ts
> +      & > * {
it's just something to be careful about I guess, but if that wrapper is merely for that purpose, then we can leave it I guess

2021-04-23 11:03 UTC, fabio-silva submitted a review, later dismissed

2021-04-23 11:06 UTC, nicolalamacchia commented on src/pages/Profile/Profile.styles.ts
> +      & > * {
yes, the wrapper is there to put the two fields on the same line :)

2021-04-23 13:15 UTC, atymchuk approved these changes

2021-04-23 13:15 UTC, atymchuk commented on src/core/api/__mocks__/auth.ts
> +// export const getBackendSrv = jest.fn().mockReturnValue(backendSrv);
Leftover

2021-04-23 13:15 UTC, atymchuk commented on src/core/api/__mocks__/auth.ts
> +// export const getBackendSrv = jest.fn().mockReturnValue(backendSrv);
```suggestion
```

2021-04-27 18:00 UTC, nicolalamacchia commented on src/core/api/__mocks__/auth.ts
> +// export const getBackendSrv = jest.fn().mockReturnValue(backendSrv);
Done

2021-04-27 20:53 UTC, atymchuk requested changes

2021-04-27 20:53 UTC, atymchuk commented on src/core/api/auth.ts
> +  // const apiClient = new AuthAPIClient(PLATFORM_BASE_URL, null, null);
Consider cleaning up the comments in this file.

2021-04-27 20:53 UTC, atymchuk commented on src/core/api/auth.ts
> +  // return apiClient.refreshSession(request, {});
It can't be the reason why the e2e tests fail. Let's put it back :)

2021-04-27 20:53 UTC, atymchuk commented on src/core/api/auth.ts
> +    getFirstName: () => 'Nicola',
Must have mistakenly left it here.

2021-04-27 20:58 UTC, nicolalamacchia commented on src/core/api/auth.ts
> +    getFirstName: () => 'Nicola',
I told myself: "remember to revert this"... :man_facepalming:

2021-04-27 20:59 UTC, nicolalamacchia commented on src/core/api/auth.ts
> +  // return apiClient.refreshSession(request, {});
Bad commit, fixed

2021-04-27 20:59 UTC, nicolalamacchia commented on src/core/api/auth.ts
> +  // const apiClient = new AuthAPIClient(PLATFORM_BASE_URL, null, null);
Bad commit, fixed

2021-04-28 19:36 UTC, fabio-silva submitted a review, later dismissed
Just a nit

2021-04-28 19:36 UTC, fabio-silva commented on src/pages/Profile/Profile.tsx
> +                <TextInputField validate={validators.required} label={Messages.lastNameLabel} name="lastName" />
Most of the times I believe we use `validators`, here it's `validate`. Is there a reason for that?

2021-04-29 11:42 UTC, nicolalamacchia commented on src/pages/Profile/Profile.tsx
> +                <TextInputField validate={validators.required} label={Messages.lastNameLabel} name="lastName" />
Fixed

2021-04-29 12:47 UTC, fabio-silva approved these changes

2021-04-29 14:39 UTC, tiagomotasantos requested changes

2021-04-29 14:39 UTC, tiagomotasantos commented on src/pages/Profile/Profile.tsx
> +                  Save
This "Save" could be in the Messages file like the rest

2021-04-29 14:48 UTC, nicolalamacchia commented on src/pages/Profile/Profile.tsx
> +                  Save
Fixed

2021-04-29 14:49 UTC, tiagomotasantos approved these changes

2021-04-29 17:44 UTC, atymchuk approved these changes

2021-05-04 08:49 UTC, merged